cozy/cozy-ui

demo/app/assets/index.html, demo/app/styles/app.styl, demo/app/styles/cozy-ui, src/stylus/cozy-ui/app/layouts.styl
I spent some time reading cozy-ui's code this week-end with the hope to use it for the databrowser. Here is a proposition of enhancement just to see if i understand cozy-ui a little bit.
=> Proposition of enhancement of $app-2panes-toolbar

src/stylus/cozy-ui/app/forms.styl
=> Improve checkbox

stylus/index.js
This PR fixes auto-import in CSS modules
=> Fix paths imports

stylus/ui-app/layouts.styl
=> [Feat] Add layout with sticky sidebar + refactoring

stylus/cozy-ui/defaults.styl, stylus/ui-app/alerts.styl, stylus/ui-components/button.styl
* Adds styles for an overlay
* Remove styles for icons in alerts
* Update margin/padding, etc.
* Adds styles for buttons in alerts
* Deal with CSS transition on overlay and alerts
=> [feat] Update alerts for Cozy Files v3

.stylintrc, .travis.yml, LICENSE, README.md, package.json, yarn.lock
⚠️ **DO NOT MERGE YET** ⚠️ 
Wait for config & refactoring before merging.
=> [chore] Enable linting on travis

package.json, postcss.config.js, yarn.lock
This PR adds the dependencies required to import style files in logical components in cozy-ui.
=> [chore] Added css loaders

react/Alerter/index.jsx, react/Alerter/index.styl, stylus/ui-components/alerts.styl
A basic component to display notifications!
It comes in 3 variations: error, success and info.
It auto-closes after a few seconds or you can provide a button text and callback to handle the closing elsewhere.
=> [feat] Added alerter component!

package.json
Upgrade version to 3.0.0-beta6
=> 3.0.0-beta6

react/Alerter/index.jsx
- Added an optional close callback for the alerter - turns out updating the state after the notification auto-hides is quite useful!
- Made the duration configurable via an extra prop
=> Alerter improvements

react/Modal/index.jsx, react/Modal/index.styl, stylus/ui-components/modals.styl
It's a Modal from @y-lohse model
=> Add react Modal :speech_balloon:

.travis.yml, package.json
It's like https://github.com/cozy/cozy-client-js/pull/48
=> Auto publishing to npm by Travis 🎯

react/helpers/i18n.jsx
@goldoraf pretty straightforward, I just wonder if `i18nDate` and thus `f` should be optional? With the proposed implementation, if `i18nDate` is not defined, the whole thing crashes (same as with `i18n`)
=> [feat] Adds support for formatting i18n function

stylus/ui-app/layouts.styl
That's only a part of the fix.
=> [fix] fix thead on Safari (requires updated Files & Bar)

CHANGELOG.md, stylus/ui-app/layouts.styl, stylus/ui-app/nav.styl
=> [fix] nav height on mobile was bigger than it was supposed to

react/Modal/index.jsx
On Cozy Drive we use this Modal with new parameters but we have lot of deprecated message.
This PR remove it. Message are now only display when we used deprecated parameters.
=> refactor: Remove unnecessary deprecated msg :hocho:

CHANGELOG.md, react/Tabs/index.jsx, react/Tabs/styles.styl, stylus/ui-components/tabs.styl
A simple tabs component, with default styles that can be overiden via a prop.
=> feat: tabs component

stylus/ui-app/nav.styl
https://github.com/cozy/cozy-ui/issues/97
=> fix(nav): fix overflowing text from hover. #97

stylus/cozy-ui/defaults.styl
Added layout style from Cozy-bar's.
See https://github.com/cozy/cozy-bar/pull/43 for more information about it.
=> feat: Moved layout style from Cozy-bar to UI

CHANGELOG.md, package.json
=> release: 3.0.0-beta25

react/Modal/index.jsx
In order to save @y-lohse for the next demos ;)
=> Handle closing modal by outside click and escape key

CHANGELOG.md, package.json
The 29th beta of the version 3.0.0 guys 🏆
=> release: v3.0.0beta29

stylus/ui-base/fonts.styl
=> fix: font-size bails out from converting to em if using rem

package.json, react/helpers/tracker.js, yarn.lock
This tracking helper code is now used across our apps, so it would be good to have it somewhere in common. WHile cozy-ui is not ideal, it's the only place we have right now and there are other purely js helpers here, so... ¯\_(ツ)_/¯
=> feat: add tracking helper

stylus/ui-base/animations.styl
Reverts cozy/cozy-ui#140 which at the end completely fucked up all spinners… I make a fix in Collect about the spinner ~~gate~~ issue. Sorry for the panic :disappointed:
=> Revert "CC-13 | Fix keyframes w/ css modules"

docs/react/.storybook/config.js, docs/react/.storybook/webpack.config.js, docs/react/stories/Toggle.js, index.js, package.json, react/Toggle/index.jsx, yarn.lock
It is the following of #135. It now works with webpack2 and import styles styles :fireworks:
=> chore: Add storybook to display example :newspaper:

stylus/ui-components/button.styl
used in https://github.com/cozy/cozy-drive/pull/337 (download button in public view)
=> add download button

react/Spinner/styles.styl, react/Toggle/styles.styl, stylus/cozy-ui/defaults.styl, stylus/ui-app/nav.styl, stylus/ui-app/sidebar.styl, stylus/ui-components/alerts.styl, stylus/ui-components/button.styl, stylus/ui-components/empty.styl, stylus/ui-components/forms.styl, stylus/ui-components/modals.styl, stylus/ui-components/popover.styl, stylus/ui-components/selectionbar.styl, stylus/ui-components/table.styl, stylus/ui-components/tabs.styl
```
grey-01 -> pale-grey
grey-02 -> silver
grey-03 -> silver
grey-04 -> cool-grey
grey-05 -> cool-grey
grey-06 -> cool-grey
grey-07 -> slate-grey
grey-08 -> charcoal-grey
grey-09 -> silver
grey-10 -> pale-grey
grey-11 -> cool-grey
grey-12 -> slate-grey
```
as was already specified in palette.styl
=> refactor: replace deprecated greys by their new counterpart

.gitignore, .npmignore, .travis.yml, _config.yml, docs/README.md, docs/_config.yml, package.json, yarn.lock
fix: #167 
You can see 
- [build folder](https://github.com/kosssi/cozy-ui/tree/gh-pages).
- [website](https://kosssi.github.io/cozy-ui/)
- [storybook](https://kosssi.github.io/cozy-ui/react/)
=> feat: Add react documentation 🔭

docs/react/.storybook/addons.js, docs/react/.storybook/config.js, docs/react/stories/Toggle.js, package.json, yarn.lock
I had examples of how to use `<Toggle />` and the `@storybook/addon-info` to display source code and React.PropTypes... To become a beautiful components' styleguide.
See the demo here: https://enguerran.github.io/cozy-ui/react/
=> doc: add toggle examples

stylus/ui-components/button.styl
=> fix: spinner was broken due to brute force update, my bad

docs/README.md, package.json, stylus/objects/sidebar.styl, stylus/utilities/hidden.styl, stylus/utilities/spaces.styl
=> Sidebar fixed, updated readme and spacers utilities

react/helpers/breakpoints.jsx
=> 🚑 Fix Breakpoints helper

stylus/elements/defaults.styl
=> 🎨 Fixing default html element's background color

stylus/components/button.styl
Forced `:visited` color on `c-btn` links.
=> fix: visited links color

package.json, react/ActionMenu/Readme.md, react/ActionMenu/index.jsx, react/ActionMenu/styles.styl, react/Menu/index.jsx, react/Menu/styles.styl, react/Overlay/index.jsx, stylus/components/action-menu.styl, yarn.lock
Visible at https://ptbrowne.github.io/cozy-ui/react/#actionmenu
Mostly taken from https://github.com/cozy/cozy-drive/blob/088f7b600b9a92dde3959d82a7d3c3a90a33fd7c/src/drive/components/FileActionMenu.jsx
=> Action Menu

docs/webpack.config.js, stylus/components/modals.styl
https://ptbrowne.github.io/cozy-ui/react/#modal
=> Modals improvements

stylus/settings/palette.json, stylus/settings/palette.styl
Fixing #188 
JS files can do
```
import palette from 'cozy-ui/stylus/palette.json'
```
=> ✨ feat: have the palette in json so that JS files can load it. fix #188

CODEOWNERS
Adding [code owners](https://help.github.com/articles/about-codeowners/)
* GoOz for CSS/Stylus files
* Cpatchane and me for React components
=> 🔧 chore: add code owners

package.json, react/Button/index.jsx, yarn.lock
I believe we need to provide default value for __every__ required props.
And I believe we need to set which props are required using [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html).
(I notice we speak about _default value_ in #190 too)
=> feat: default theme for button

CHANGELOG.md, package.json
- Modal : `withCross` is now `closable`. Deprecation warning. [#237](https://github.com/cozy/cozy-ui/pull/237)
- Modal : `dismissAction` property has been added and will be called when clicking outside or on the cross. For now, secondaryAction will be copied into it if it is undefined. Deprecation warning. [#237](https://github.com/cozy/cozy-ui/pull/237)
- Colors variable:
```
pale-grey -> paleGrey
cool-grey -> coolGrey
slate-grey -> slateGrey
charcoal-grey -> charcoalGrey
dodger-blue -> dodgerBlue
science-blue -> scienceBlue
puerto-rico -> puertoRico
texas-rose -> texasRose
your-pink -> yourPink
```
=> 💎 Release v5.0.2

react/Button/Readme.md, react/Button/index.jsx
See https://github.com/cozy/cozy-ui/issues/234
You can test in live here: https://enguerran.github.io/cozy-ui/react/
Or just look at how it should be displayed:
=> doc: button component with variations

stylus/components/empty.styl, stylus/elements/defaults.styl, stylus/objects/layouts.styl
Added the new layout (already setup on Cozy-Bank) and I tweaked the empty views that wasn't centered anymore due to this change.
NB:  The chunk about Cozy-bar will be moved later in order to have a progressive update and not break everything.
=> feat: adding new layout to allow minimal-ui on mobile

stylus/objects/layouts.styl
Wrong breakpoint for the cozy-bar… 😒
=> fix: cozy-bar was misplaced on tablet

react/Menu/styles.styl
=> ✨ feat: cursor pointer for menu btn

react/Spinner/index.jsx
- Add className to spinner
- Add Proptypes
=> Spinner classname

react/Spinner/Readme.md, react/Spinner/index.jsx, react/Spinner/styles.styl
=> Enhanced Spinner

react/Sidebar/index.jsx, stylus/objects/sidebar.styl
And a little refactoring on Sidebar's style
=> feat: Add className props to Sidebar

react/Spinner/index.jsx
PropType for booleans is `bool`
=> 🐝 fix: boolean -> bool

react/Textarea/Readme.md, react/Textarea/index.jsx, react/Textarea/styles.styl, stylus/components/forms.styl, stylus/cozy-ui/build.styl
Added `<Textarea />` component
Preview: https://gooz.github.io/cozy-ui/react/#textarea
=> feat: add Textarea component

docs/styleguide.config.js
Added sectioning to order things a bit because it will get messy quickly without it.
Preview: https://gooz.github.io/cozy-ui/react/
=> chore: added category for components to order things a bit

CHANGELOG.md, stylus/components/nav.styl
Remove right padding in Nav. Issue #288 
Also made some ajdustments.
=> feat: better use of spaces in nav

react/Spinner/styles.styl, stylus/components/button.styl, stylus/components/forms.styl, stylus/components/nav.styl, stylus/components/table.styl, stylus/tools/mixins.styl, test/basefont.styl
- Removed em() and font-size()
=> 🔧 chore: remove em()

stylus/objects/layouts.styl
Added a One Column layout. Well it was already kinda here already but it's more explicit this way.
=> feat: add explicitely One column layout

stylus/settings/breakpoints.styl, stylus/utilities/display.styl
Added new default breakpoint for tablet because there was a blank to fill.
=> feat: add new breakpoint for tablet

react/IntentOpener/IntentOpener.jsx
=> ✨ feat: add some proptypes for IntentOpener

react/Button/index.jsx, stylus/components/button.styl, stylus/cozy-ui/build.styl
This time, I checked, It works fine, although it's kinda pissing me off being forced to add a span. 😡
=> fix: Safari 10 buttons behave normally

stylus/components/alerts.styl
Alerts are now wider as requested by the designer.
=> fix increase alert size

stylus/components/button.styl
Miscalculation from me. My bad.
=> fix: button height

docs/utils.js, react/IntentOpener/IntentExample.jsx
- Added IntentExample with IntentHeader.
Visible on https://ptbrowne.github.io/cozy-ui/react/#intentopener
=> 🐝 fix: intent opener

react/Icon/Readme.md, react/Icon/index.jsx, react/Input/Readme.md, react/Input/index.jsx
- Input forwards props : fixes https://github.com/cozy/cozy-ui/issues/304
- Icon forwards props : fixes https://github.com/cozy/cozy-ui/issues/251
=> Forward props in containers

docs/fixtures/en.json, docs/styleguide.config.js, docs/utils.js, package.json, react/Hero/Readme.md, react/Hero/index.jsx, react/Hero/styles.styl, yarn.lock
Desktop
Mobile
Doc available here : https://ptbrowne.github.io/cozy-ui/react/#hero
Fixes https://github.com/cozy/cozy-ui/issues/171
=> ✨ feat: Hero component

react/Avatar/Readme.md, react/Avatar/index.jsx
How Avatar works now:
1. If an image is given, then show it.
2. If not, search for a text (the app chooses the order of preference if any)
5. If none of the above is there, just show the default icon.
=> feat: Expects any string for a text

react/Button/index.jsx
Makes `import Button from 'cozy-ui/react/Button'` work!
=> fix: export default button component

stylus/components/modals.styl
And furthermore, Modals get to the top of the screen instead of centered for UX pruposes.
Preview: https://gooz.github.io/cozy-ui/react/#modal
=> feat: modal sizes keep their size unless they don't have the room anymore

stylus/objects/layouts.styl
Extend mobile layout from 2 panes layout to One column layout.
Fix: #359
=> fix: One column Layout looks well on mobile

react/Toggle/README.md, react/Toggle/index.jsx
Not much to add, pretty straightforward but urgently needed...
=> Added disabled prop to Toggle

docs/styleguide.config.js, react/Button/Readme.md, react/Button/index.jsx
Following the remarks of @y-lohse [here](https://github.com/cozy/cozy-ui/issues/376).
Fixes #376 
* ✨ feat: label can be a string or a React element
*  🐝 fix: label should be passed as variable
*  🐝 fix: children should not be passed as object
*  ✨ feat: let React element be passed for Icon
=> Button improvements

react/Modal/index.jsx
I guess this one was missing too, isn't it.
=> fix: export modal buttons

package.json, react/Alerter/index.jsx, react/Avatar/index.jsx, react/Field/index.jsx, react/IntentModal/IntentIframe.jsx, react/IntentOpener/IntentExample.jsx, react/IntentOpener/IntentOpener.jsx, react/Menu/index.jsx, react/Modal/index.jsx, react/SelectionBar/index.jsx, react/Tabs/index.jsx, react/Toggle/index.jsx, react/utils.jsx, yarn.lock
Use the same config as every other apps/services.
Found some bugs in the process ✨
=> Use eslint-config-cozy-app

CHANGELOG.md, package.json
=> chore: release v7.8.0 :arrow_down_small:

codemods/button-new-api.js, codemods/utils.js
We should add codemods so they are easily reviewable and usable by others.
⚠️  I'll wait for the #384 to be merged to repair the styling issue.
=> Add button codemod to repository

react/SelectBox/index.jsx, react/SelectBox/styles.styl
With focus styles, keyboard interactions become visible!
=> fix: add focus styles on options

stylus/cozy-ui/build.styl, stylus/utilities/spaces.styl
Pour créer toutes les classes utilitaires de margin padding 0
=> Add 0 size

docs/styleguide.config.js, react/Alerter/Readme.md, react/Alerter/index.jsx, react/Alerter/styles.styl, stylus/components/alerts.styl, stylus/components/button.styl
Following up on : #263, I've essentially copied over the Alerter component from Photos, updated it and added some documentation. [Here's the preview!](http://yannick-lohse.fr/cozy-ui/react/#alerter)
=> Alerter ❗️

docs/README.md
As I was diving into Cozy-UI for the first time since a long time ago, I was looking for a documentation about how to develop components, and did not find anything. So I used the only way I know and this PR document it, if any new developer or contributor is interested.
=> doc: how to use and hack Cozy UI components 📚

stylus/components/button.styl
=> fix: button :hover styles are simpler to overwrite

react/Alerter/index.jsx
=> ✨ feat: able to customize delay of alert and auto delay

.travis.yml, CHANGELOG.md, docs/styleguide.config.js, package.json, react/IntentModal/IntentModal.jsx, react/IntentModal/test/__snapshots__/intentModal.spec.js.snap, react/IntentModal/test/intentModal.spec.js, test/__mocks__/fileMock.js, yarn.lock
This PR:
* Fixes a regression in `<IntentModal />` props.
* Adds Jest environment for components testing :tada:
* Tests `<IntentModal />`
* Adds tests to Travis
* Solves #424, actually [snapgitdist](https://github.com/styleguidist/snapguidist) cannot be used for Continuous Integration, and Jest is so simple to set up.
=> feat: fix IntentModal and add Jest tests ✨

react/Input/Readme.md, react/Input/index.jsx, react/Input/styles.styl, react/Modal/styles.styl, react/Textarea/Readme.md, react/Textarea/index.jsx, react/Textarea/styles.styl, stylus/components/forms.styl, stylus/cozy-ui/build.styl, stylus/elements/defaults.styl
=> Feat: various minor tweaks and additions

src/icons.jsx
Adding top/bottom icon
https://ptbrowne.github.io/cozy-ui/react/#icon
=> feat: add top/bottom icon

.gitignore
So it doesn't pollute the repo.
=> chore: add .changelog cachedir to gitignore

yarn.lock
Update preact and preact-portal
=> 🔧 chore: update preact and preact-portal

react/ListItemText/index.jsx
Usecase : the developer wants to add onClick/style etc..
=> feat: ListItemText forward its props

react/Alerter/Readme.md, react/Alerter/index.jsx, react/Alerter/styles.styl, stylus/components/alerts.styl, stylus/components/button.styl
- Alerts are now elastic according to its content width but won't exceed 640px.
- Now use `<Button />` component
Preview: https://gooz.github.io/cozy-ui/react/#alerter
Fix #345
=> feat: Elastic alerts + use of Button component

react/Button/Readme.md, react/ButtonAction/Readme.md, stylus/components/button.styl
https://ptbrowne.github.io/cozy-ui/react/
@gregorylegarec in #443 needs to have easy access to button themes.
In this refactoring, I tried to make more visible the fact that button variants all share the same code and are based on color themes. This should make it easier to implement button texts.
=> Refactor buttons

stylus/components/button.styl
=> fix: buttonAction line height

react/Menu/index.jsx
Wrappers should pass props down.
Fix #340
=> ✨ feat: pass props down in MenuItem

react/IntentModal/IntentModal.jsx, react/IntentModal/test/__snapshots__/intentModal.spec.js.snap
Add the current `mobileFullscreen` modal option to the IntentModal behaviour.
=> Add mobileFullscreen on IntentModal

react/Icon/index.jsx
=> Adds `size` prop for <Icon /> component

assets/icons/ui/icon-calendar.svg, react/__snapshots__/examples.spec.jsx.snap, src/icons.jsx
Add a calendar icon : ![image](https://user-images.githubusercontent.com/1606068/39587965-0ecc48e4-4efb-11e8-8703-809b2c48e1b6.png)
=> feat: add calendar icon

react/Chip/Readme.md, react/Chip/index.jsx, react/Chip/styles.styl, react/examples.spec.jsx, react/testFromStyleguidist.js, stylus/components/chip.styl
https://ptbrowne.github.io/cozy-ui/react/#!/Chip/7
fix #475
=> ✨ feat: add chip button

react/IntentHeader/index.jsx, react/IntentHeader/styles.styl, react/IntentModal/IntentModal.jsx, react/IntentModal/test/__snapshots__/intentModal.spec.js.snap, react/Modal/index.jsx
* Improve flex properties to avoid having a crushed header.
* Allow passing a className prop
=> <IntentHeader /> little improvements

stylus/components/forms.styl
Quickfix for a long term issue. Only Settings should be impacted.
=> fix: only links inside forms are concerned now

docs/styleguide.config.js, docs/styleguide.setup.js, react/helpers/migrateProps.jsx
Use setup files to setup global variable to force showing deprecation warnings.
Fix #458.
ping @gregorylegarec
=> ✨ feat: show deprecation warnings in the styleguide in production

stylus/cozy-ui/build.styl, stylus/settings/palette.styl
=> Expose all palette colors as css variables

docs/how-to-extract.md
There was no clear method on how to extract CSS from cozy-ui.
=> 📚 doc: add doc on how to extract some CSS from cozy-ui

.travis.yml, package.json, yarn.lock
This setups semantic-release.
What we get on each PR that get merged : 
* A new release of cozy-ui published on npm
* A new release of cozy-ui created on Github (with changelog in it)
* `CHANGELOG.md` is updated (with this format : https://github.com/drazik/my-awesome-module/blob/master/CHANGELOG.md)
What we need to do : 
* Respect the [conventional commit messages format](https://conventionalcommits.org/) (we are working on #519 to lint the commit messages and throw an error if a message is not valid). It means that emojis at the beginning of commit messages are no longer valid :disappointed: 
* Discuss if we really want to release a new version on each merged PR or not
=> chore: setup semantic-release

package.json, react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/SelectBox/styles.styl, react/__snapshots__/examples.spec.jsx.snap
cursor: disabled and grey color for disabled option
=> feat: add disabled option style

react/Icon/index.jsx
=> feat: bad icon does not throw an error

docs/styleguide.config.js, react/PopupOpener/Readme.md, react/PopupOpener/index.jsx
A component/wrapper which will open a link in a popup according to props provided.
https://cpatchane.github.io/cozy-ui/react/#popupopener
=> Add popup opener

react/IntentModal/styles.styl
Fixes issue #545 by giving more weight to the CSS selector.
Bug related to #335
=> fix: IntentModal Cross position

stylus/components/table.styl
=> fix: table's last row was without bottom border

react/Modal/Readme.md, react/Modal/index.jsx, react/Modal/styles.styl, stylus/components/modals.styl
Make things less specific with the possibility to pass the header content as props.
I had to use `*` in the stylus code to force the max-height on content :/
See https://cpatchane.github.io/cozy-ui/react/#!/Modal/23
=> Improve modal with illustrated header

stylus/components/accordion.styl
Add little padding to accordion title for more space between items.
=> Minor accordion padding fix

stylus/cozy-ui/build.styl, stylus/settings/palette.json
=> feat: add basic colors for overwriting

react/Alerter/styles.styl, react/Modal/index.jsx, stylus/components/alerts.styl
=> fix: Alerts have increased z-index when a Modal is displayed

assets/icons/ui/icon-help.svg, react/__snapshots__/examples.spec.jsx.snap, src/icons.jsx
Also available in the [documentation](https://cpatchane.github.io/cozy-ui/react/#icon)
=> Add help ui icon

react/Accordion/Readme.md, react/Text/Readme.md, react/Text/index.jsx, react/__snapshots__/examples.spec.jsx.snap, react/index.js
Refs: #589
Preview: https://gooz.github.io/cozy-ui/react/#text
=> chore: 📚 Update Text documentation

react/Button/Readme.md, react/Button/index.jsx, react/Button/styles.styl, react/__snapshots__/examples.spec.jsx.snap, stylus/components/button.styl
Preview: https://gooz.github.io/cozy-ui/react/#button
Fixes: #554
=> feat: ✨ Add Round icon button

.prettierrc.json, package.json, yarn.lock
It's already on ['eslint-config-cozy-app'][eslint-config-cozy-app]
[eslint-config-cozy-app]: https://github.com/cozy/cozy-libs/tree/master/packages/eslint-config-cozy-app
=> chore: Remove unnecessary dependency 🔥

react/AppIcon/test/AppIcon.spec.js
Following https://github.com/cozy/cozy-ui/pull/596#discussion_r211162387
=> Better asynchronous test for AppIcon

react/Modal/Readme.md, react/Modal/index.jsx
=> fix: Made Modal accessible

react/SelectionBar/index.jsx, stylus/components/selectionbar.styl
=> fix: Made selectionBar accessible

react/IntentModal/IntentModal.jsx, react/IntentModal/IntentModal.md, react/IntentModal/test/__snapshots__/intentModal.spec.js.snap, react/Modal/Readme.md, react/Modal/index.jsx
=> chore(Modal): 🎨 Renaming props for clarity

react/AppIcon/Readme.md, react/AppIcon/index.jsx, react/AppIcon/test/__snapshots__/AppIcon.spec.js.snap
Several updates:
* `className` prop : useful for styling
* `console.error`: useful for debugging
* Better doc: useful for learning
=> AppIcon improvements

package.json, react/Modal/index.jsx, yarn.lock
Added the dependency [Body Scroll Lock](https://github.com/willmcpo/body-scroll-lock) to prevent background scrolling when Modal is displayed and scrollable. 
Essential especially on iOS but useful on other mobile OS and desktop.
For now, it's only used with Modal but could be extended to other components if needed.
=> feat: ✨ Add Body Scroll Lock for Modals

docs/styleguide.config.js, docs/webpack.config.js, package.json, react/Alerter/index.jsx, react/I18n/index.jsx, react/IntentHeader/index.jsx, react/IntentModal/test/intentModal.spec.js, react/Modal/index.jsx, react/Portal/index.jsx, react/__snapshots__/examples.spec.jsx.snap, test/jestsetup.js, yarn.lock
Some cleaning work still need to be done, but:
=> feat: Remove preact and use React instead

docs/styleguide.config.js, react/ContextHeader/Readme.md, react/ContextHeader/index.jsx, react/ContextHeader/styles.styl, react/index.js
Adds a new component like the header here : https://marvelapp.com/2d65897/screen/39342136
Building the docs is currently broken so I'll update them as soon as they're back working!
=> feat: Added ContextHeader element

react/Modal/index.jsx
=> Fix typo labelledBy/labelledby

react/Modal/index.jsx
Necessary since last versions of cozy-ui
=> Add label prop to modal close button

package.json, react/I18n/index.jsx, react/Modal/index.jsx, react/Portal/index.jsx, yarn.lock
* Use portal from React only if `USE_PREACT` environment variable found
* Handle UNSAFE_ React API
=> Preact retrocompatibility

react/I18n/index.jsx, react/Modal/index.jsx
=> Pass correct props to api hack

react/Modal/index.jsx, react/index.js
I'm using a `ModalFooter` with buttons inside of it, but I want to be able to disable one of them, and generally have better control over them — but I also want the usual alignment.
=> feat(ModalFooter): Option for button alignment

react/ActionMenu/index.jsx, react/Overlay/index.jsx
Tweaks to make the action menu work with React.
=> Action menu react

react/ActionMenu/Readme.md, react/ActionMenu/index.jsx, react/ActionMenu/styles.styl, stylus/components/action-menu.styl
Add ActionMenuItem to standardize the way we display items in an ActionMenu. See https://mattermost.cozycloud.cc/test-team/pl/55kkh9isjbrf5xmq5taysor97a
=> feat: ActionMenuItem

docs/webpack.config.js, react/Chip/index.jsx, react/Empty/Readme.md, react/Layout/Layout.md
- Fix warnings in Empty/Layout
- Fix Alerter (need to pass process.env.USE_REACT to cozy-ui)
- Fix Chip which used props from render
=> Fix styleguidist

react/AppIcon/test/__snapshots__/AppIcon.spec.js.snap, react/IntentModal/test/__snapshots__/intentModal.spec.js.snap, react/__snapshots__/examples.spec.jsx.snap
Ce qu'il s'est passé est assez simple : 
- Une PR a modifié les classNames des styles 
- D'autres PR ont modifié des éléments dans les snapshots 
=> Les 2 étaient vertes, mais l'ensemble des deux non 
=> On devrait peut-être run les tests dans master ? C'est déjà fait ?
=> fix: Snapshots

react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/__snapshots__/examples.spec.jsx.snap
Regarding #679 , [react-select has an `innerRef` prop that needs to be passed down for some components](https://react-select.com/components#inner-ref).
=> fix(Select): Added innerRef prop

package.json
I could be wrong but I think we don't need either test and mocks file in our transpiled version.
=> Ignore test files on transpilation

package.json, yarn.lock
This was breaking the react-select installation.
It was missing from installing with yarn.
=> fix(dep): Use react-dom as dev dep

stylus/components/wizard.styl, stylus/cozy-ui/build.styl, stylus/utilities/spaces.styl
- some spacing adjustements for the stack part
- Adding spacing "auto" for utilities
=> fix: Mobile layout changes + adjustments

stylus/components/table.styl
=> fix: 🐛 Wrong color for table divider

stylus/components/forms.styl, stylus/components/wizard.styl, stylus/cozy-ui/build.styl
Some changes to fit the new design
=> fix: New way to display custom domain

react/Alerter/index.jsx, react/AppIcon/index.jsx, react/Avatar/index.jsx, react/Badge/index.jsx, react/Button/index.jsx, react/Empty/index.jsx, react/IntentHeader/index.jsx, react/IntentWrapper/index.jsx, react/Layout/Layout.jsx, react/Media/Media.jsx, react/Menu/index.jsx, react/Modal/index.jsx, react/Popover/Popover.jsx, react/SelectBox/SelectBox.jsx, react/Sidebar/index.jsx, react/Spinner/index.jsx, react/Tabs/index.jsx, react/Text/index.jsx
~~When I would like update `MainTitle` with my className it's override by default style.~~
~~I propose to put className always at the end~~
It's a refactoring to use cx everywhere and className on the end...
=> refactor around className

stylus/components/wizard.styl, stylus/cozy-ui/build.styl
It turns out we don't need this chunk so I removed it.
=> chore: Remove useless wizard style

stylus/components/forms.styl, stylus/components/wizard.styl, stylus/cozy-ui/build.styl
A few design feedback on the wizard views
=> fix: Wizard design

stylus/settings/palette.json, stylus/settings/palette.styl
On Banks we have a fuchsia color for this icon https://github.com/cozy/cozy-banks/blob/master/src/assets/icons/categories/icon-cat-activities.svg
=> feat: Add fuchsia color

react/MuiCozyTheme/theme.js, react/utils/color.js
On Banks we would like find color value from css variable https://github.com/cozy/cozy-banks/pull/661
=> refactor: Export getCssVariableValue

assets/icons/ui/info.svg, react/Icon/Readme.md, react/__snapshots__/examples.spec.jsx.snap, scripts/make-icon-sprite.sh
=> feat: Add info icon

react/Field/Readme.md, react/Field/index.jsx
=> Add fullwidth prop to Field

react/SelectBox/SelectBox.jsx, react/__snapshots__/examples.spec.jsx.snap
SelectBox arrow's hadn't the right size & color.
🎁 Bonus: fixed the change of direction when `menuIsOpen = true`
👀 Preview: https://gooz.github.io/cozy-ui/react/#selectbox
=> fix: 🐛 SelectBox arrow size & look

stylus/components/button.styl
After a discussion with @Claiw : 
- change hover color for txt & svg
=> fix(Subtle button): Fix hover color

react/Infos/styles.styl
=> fix(Infos): Force SVG color to slateGrey

react/Field/Readme.md, react/Field/index.jsx, react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/SelectBox/styles.styl, react/__snapshots__/examples.spec.jsx.snap
* Make it usable as Field by handling the type `dropdown`.
* Handle fullwidth and size  props to be compatible with Field props
=> Improve SelectBox

react/Field/Readme.md, react/Field/index.jsx, react/Field/styles.styl, react/__snapshots__/examples.spec.jsx.snap
Add InputPassword witch purpose a button to show/hide the string in the input.
The button could be disabled with the props "askShowHide" to "false".
=> feat(InputPassword): Add InputPassword component

react/Button/index.jsx, react/ContextHeader/index.jsx, react/Empty/index.jsx, react/Icon/index.jsx, react/Infos/index.jsx
The icon prop type should match the type of Icon component's icon prop
=> Fix Empty component icon proptype

react/Field/index.jsx, react/Field/styles.styl
=> Forward size and fullwidth to InputPassword

assets/icons/ui/pen.svg, react/Icon/Readme.md, react/__snapshots__/examples.spec.jsx.snap, scripts/make-icon-sprite.sh
Add pen icon (e.g. for Edit buttons)
=> feat(Icon): Add pen icon

react/MuiCozyTheme/Buttons/theme.js, react/MuiCozyTheme/theme.js
To simplify the modification of the theme and have a better vision of all the changes.
[See discussion](https://mattermost.cozycloud.cc/test-team/pl/abc3e58yupni7rzyug773hq9zw)
=> refactor: Move MuiButton style

react/Field/index.jsx, react/Input/Readme.md, react/Input/index.jsx, react/Textarea/Readme.md, react/Textarea/index.jsx, react/__snapshots__/examples.spec.jsx.snap, stylus/components/forms.styl
Base on @claiw 's mockup for harvest apps.
=> Input: Handle disabled attribute

react/Field/Readme.md, react/Field/index.jsx, react/Field/styles.styl, react/__snapshots__/examples.spec.jsx.snap
Add the possibility to have an text ( or button in the future ) item on the right of the label.
=> feat(Field): Extra field , actually just side label

assets/icons/ui/cross-small.svg, assets/icons/ui/plus-small.svg, react/Icon/Readme.md, react/__snapshots__/examples.spec.jsx.snap, scripts/make-icon-sprite.sh
=> feat(Icons): Add smal cross and small plus

react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/__snapshots__/examples.spec.jsx.snap
- Do not wrap select. A ref to the control is accessible via `ref.select.controlRef`
- Try not to do DOM operations while rendering.
View on : https://ptbrowne.github.io/cozy-ui/react/#!/SelectBox/5
=> [select-box] Do not wrap

stylus/generic/typography.styl
=> fix: Update title-h4 on mobile

stylus/components/wizard.styl, stylus/cozy-ui/build.styl
Added a centered layout class on mobile for the Waiting page essentially.
=> feat(wizard): Add centered layout class

stylus/objects/layouts.styl
Je ne comprends pas pourquoi on a du style de la cozy-bar dans cozy-ui...
=> feat: Remove cozy-bar style

react/Checkbox/Readme.md, react/Checkbox/index.jsx, react/Radio/Readme.md, react/Radio/index.jsx, react/__snapshots__/examples.spec.jsx.snap, stylus/components/forms.styl
Added props & style for disabled Checkbox & Radio.
Preview: [Checkbox](https://gooz.github.io/cozy-ui/react/#checkbox) & [Radio](https://gooz.github.io/cozy-ui/react/#radio)
=> feat: Add disabled checkbox & radio style

react/MuiCozyTheme/theme.js, stylus/settings/palette.json, stylus/settings/palette.styl
Add 3 CSS variables:
```
--primaryColor
--primaryColorLight
--primaryContrastTextColor
```
[Styleguide](https://kosssi.github.io/cozy-ui/styleguide/section-settings.html) - [styleguidist](https://kosssi.github.io/cozy-ui/react/#muicozytheme)
=> feat: Add primary variables

react/ActionMenu/Readme.md, react/ActionMenu/index.jsx, react/ActionMenu/styles.styl, react/__snapshots__/examples.spec.jsx.snap, stylus/components/action-menu.styl
fixes: #666
It accepts any children.
[Preview](https://gooz.github.io/cozy-ui/react/#actionmenu)
=> feat(ActionMenu): ✨ Add ActionMenuHeader component

stylus/components/wizard.styl, stylus/cozy-ui/build.styl
Wizard previous button was misplaced due to a previous fix
=> fix(wizard): Previous button position

stylus/components/wizard.styl
Select in dual field was too big. It caused a visual unbalance
=> fix(wizard): Dualfield select height

react/Field/index.jsx, react/Input/index.jsx
* Allow `date` value for `type` prop in `Input` component
* Fix typo in `propTypes` attribute in `Field` component
=> Minor improvements

react/Alerter/Readme.md
Current Documentation is broken for the Alert, here is the fix.
[Preview](https://gooz.github.io/cozy-ui/react/#alerter)
=> fix: Alert Styleguidist examples

react/Menu/Readme.md, react/Menu/index.jsx, react/Menu/styles.styl, react/__snapshots__/examples.spec.jsx.snap
Icons in menu item are now top aligned.
Fixed #654
[Preview](https://gooz.github.io/cozy-ui/react/#menu)
=> fix(Menu): Top aligned Menu Icon

react/ActionMenu/index.jsx
Should fix https://github.com/cozy/cozy-ui/issues/618
=> fix(ActionMenu): Add a check before adding / removing an event listener

stylus/cozy-ui/build.styl, stylus/utilities/list.styl
Add utility class to remove bullet point from lists (`<ul>` & `<ol>`)
=> feat: Add nolist utility class for lists

stylus/cozy-ui/build.styl, stylus/utilities/bgcolor.styl
Added `background-color` utility classes just like the utily classes for text color but this time for background.
Refs #867 
Also fixed the missing text color classes in the doc.
=> feat: Add bgcolor utily classes

stylus/generic/typography.styl, stylus/utilities/text.styl
Added `u-link` class to simply add the default link style.
Added `u-breakword` class to add `word-break: word-wrap;` to an element
Refactored font size & text alignment utility classes so it can be responsive now.
=> feat: Add link and break word utilities + refacto

react/Input/index.jsx
Tel is a valid type for an input. It fixes some proptypes warning.
=> fix(Input): Tel is a valid type

stylus/cozy-ui/build.styl, stylus/generic/animations.styl, stylus/utilities/effects.styl
Deploying of styleguidist in progress...
```
```
=> feat: Add u-shake to shake a login error

CODEOWNERS
Adding myself as a code owner \o/
=> chore: New codeowner 🎉

react/Spinner/Readme.md, react/Spinner/index.jsx, react/Spinner/styles.styl, react/__snapshots__/examples.spec.jsx.snap
should fix https://github.com/cozy/cozy-ui/issues/878 
https://crash--.github.io/cozy-ui/react/#spinner
=> feat: Spinner now use Icon

react/helpers/withBreakpoints.jsx
Allow to use proptypes without repeating all of breakpoints
ones everywhere
=> fix(breakpoints): Expose breakpointsPropTypes

react/Modal/Readme.md, react/Modal/index.jsx, react/Modal/styles.styl, stylus/components/modals.styl
An new size with 24rem as width
Deployed on https://cpatchane.github.io/cozy-ui/react/#modal
=> Add xsmall modal size

stylus/cozy-ui/build.styl, stylus/utilities/position.styl
Add values: `absolute`, `static`, `sticky`, `fixed` and `relative`
=> Add position utilities

package.json
Fixes https://github.com/CPatchane/create-cozy-app/issues/1198 — the global css files we import from cozy-ui are definitely not side effect free.
=> fix: Mark css files as having side effects

stylus/cozy-ui/build.styl, stylus/utilities/text.styl
=> fix(utilities): Add font-style utilities

react/AppLinker/index.jsx, react/AppLinker/index.spec.jsx, react/AppLinker/native.config.js, react/AppLinker/native.js, react/AppLinker/native.spec.js
Added support for Universal link for iOS
=> feat: Universal link

react/Spinner/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Spinner now uses our blue (dodgerblue via primaryColor) for default color and not random one.
=> fix: Update Spinner default color

react/Infos/Readme.md, react/Infos/index.jsx, react/Infos/styles.styl, react/__snapshots__/examples.spec.jsx.snap
See https://cpatchane.github.io/cozy-ui/react/#infos
=> feat(Infos): :nail_care: Improve Infos component with an action button

stylus/cozy-ui/build.styl, stylus/utilities/boxsizing.styl
Added a utility class to set the `box-sizing` property to `border-box`
=> feat: Add box-sizing utils

react/PushClientButton/index.jsx
Fix icon path so the component can work in a transpiled way or a non-transpiled way.
=> fix(PushClientButton): Update asset path

react/I18n/withLocales.jsx, react/Viewer/Readme.md, react/Viewer/docs/DemoProvider.jsx, react/Viewer/index.jsx, react/Viewer/index.spec.jsx, react/Viewer/locales/en.json, react/Viewer/locales/fr.json
The viewer now comes with built-in locales.
=> feat: Export viewer with locales

babel.config.js, package.json, react/I18n/withLocales.jsx, react/Viewer/index.jsx, yarn.lock
Once transpiled, the locales for the viewer were lost, because they don't get transpiled.
With this PR they will be inlined.
=> fix: Transpile locales

react/BarButton/index.jsx, react/BarButton/styles.styl, react/__snapshots__/examples.spec.jsx.snap
* ClassName typo
* missing stylus import
=> BarButton: Fixes

react/Viewer/Readme.md
Added a doc section about using the pdf viewer on a public page, and moved the webpack doc accordingly.
=> chore: Document viewer usage with webpack

react/I18n/index.jsx, react/I18n/withLocales.jsx, react/I18n/withLocales.spec.jsx
Adding test to withLocales HOC. Tests are not passing yet.
@y-lohse @gregorylegarec Can you take a look ? Is it a mistake from my end ?
=> test: Testing withLocales

react/Viewer/NoViewer/DownloadButton.jsx, react/Viewer/NoViewer/NoViewer.jsx, react/Viewer/TextViewer.jsx, react/Viewer/index.jsx, react/proptypes.js
Share the same PropType for file props.
=> refactor: Use single proptype for file

react/AppIcon/index.jsx, react/AppSections/locales/en.json, react/AppSections/locales/fr.json
- `app` is required for AppIcon
- Add missing locale strings for AppSections
=> feat: Fixes

stylus/components/forms.styl
Fixes #999
Radio button rendering is now consistent on every browsers.
=> fix: Radio button rendering

react/Checkbox/index.jsx, react/Checkbox/styles.styl, react/__snapshots__/examples.spec.jsx.snap
`<Checkbox />` component now uses `<Icon />` to display its icon, allowing to customize the color/icon/size icon for a checkbox.
Preview: https://gooz.github.io/cozy-ui/react/#checkbox
Related PR #983
=> feat: Checkbox component uses Icon

stylus/settings/breakpoints.styl
This reverts commit 69446c765aab42fc61dd58005434ed156b8719de.
See #1003
=> Revert "feat: Add Standard breakpoints for utility classes"

react/AppSections/Sections.jsx, react/AppSections/components/AppsSection.jsx, react/AppSections/components/SmallAppItem.jsx
Provides a way to customize the Icon in Sections.
We need to fetch icons in a custom way on mobile, the only way I saw was this :/
I'd like a better solution as I am not too fan of drilling the `IconComponent`.
=> Section icon custom

babel.config.js
Spec files should not be distributed and transpiled.
=> fix: Do not transpile spec files

assets/icons/ui/file-outline.svg, react/Icon/Readme.md, react/__snapshots__/examples.spec.jsx.snap, scripts/make-icon-sprite.sh
This icon will be used in banks. I think it has its place in the cozy-ui icon set.
See https://drazik.github.io/cozy-ui/react/#icon
=> feat: Add file-outline icon

stylus/components/wizard.styl, stylus/cozy-ui/build.styl
Added a little banner for updated ToS.
=> feat(wizard): Add updated banner

react/Field/index.jsx
Useful for validation purposes.
=> feat: Add onBlur to Input

react/Card/Readme.md, react/Card/index.jsx, react/Card/styles.styl, react/__snapshots__/examples.spec.jsx.snap
This makes possible to render a Card as an anchor, or anything else.
See https://drazik.github.io/cozy-ui/react/#card
=> feat(Card): Add tag prop

react/Field/index.jsx
Input can have "number" as type.
Field too now :)
=> feat: Field can have number as type

package.json, stylus/cozy-ui/build.styl, stylus/settings/breakpoints.styl
Update documentation so responsive suffixes for utility classes are officially explained and not only buried in the code.
=> chore: Update documentation about responsive utils

.travis.yml, package.json
I may have forgot to tell Travis to build the utility css file for the NPM package… :|
=> fix: Add a travis job to build utility CSS

docs/styleguide.config.js, react/AppIcon/Readme.md, react/AppIcon/index.jsx
=> fix: Reload icon when fetchIcon changes

react/AppIcon/Readme.md, react/AppIcon/index.jsx, react/AppIcon/test/AppIcon.spec.js, react/AppIcon/test/__snapshots__/AppIcon.spec.js.snap
Needed to provided an icon to fallback different from the cube
=> Handle fallback icon in AppIcon

package.json, react/AppLinker/Readme.md, react/AppLinker/index.jsx, react/AppLinker/index.spec.jsx
Remove reference to `__TARGET__`
=> fix: Do not use __TARGET__ on a lib

docs/styleguide.config.js, react/Figure/Figure.jsx, react/Figure/Figure.md, react/Figure/Figure.spec.jsx, react/Figure/Figure.styl, react/Figure/FigureBlock.jsx, react/Figure/FigureBlock.md, react/Figure/FigureBlock.styl, react/Figure/__snapshots__/Figure.spec.jsx.snap, react/Figure/index.js
Bring the Figure/FigureBlock components from Banks.
=> Figure component

react/Checkbox/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Icon was renamed.
See  https://ptbrowne.github.io/cozy-ui/react/#!/Checkbox
=> fix: Use the correct icon for checkbox

stylus/cozy-ui/build.styl, stylus/utilities/border.styl
We can now use : `.u-bdw-0` to have `border-width: 0`
=> feat(Border): Add utilities border-width

react/Field/index.jsx
Fix https://github.com/cozy/cozy-ui/pull/1128#discussion_r316106199 feedback :)
=> refactor(Field): Remove showVisibilityButton props

.github/auto-merge.yml
PRs with label automerge and with at least 1 approval will be automerged by probot-automerge.
=> feat: Configure automerge

renovate.json
The existing configuration was essentially the same.
=> chore: Switch to cozy-libs renovate config

docs/styleguide.config.js, react/MuiCozyTheme/RaisedList/README.md, react/MuiCozyTheme/RaisedList/index.js, react/MuiCozyTheme/theme.js
This component is based on the MUI List component. It has been added primarily for the password manager's needs, but it's a component that can be used on various places, like in administrative procedures.
See https://drazik.github.io/cozy-ui/react/#!/RaisedList
This is technically not a MUI component, but I put it under the `MuiCozyTheme` directory because it's based on the MUI's `List` component, so the user needs to have MUI as a dep to use it, just like any other MUI component.
=> Add RaisedList react component

package.json
Made a mistake and put argos-cli into normal deps.
=> Move argos cli to dev dep

react/PercentageLine/Readme.md
Otherwise, Argos sees difference every time
=> feat: Set percentage in example to fixed value

react/AppLinker/index.jsx, react/AppLinker/native.js
- Refactored generateUniversalLink to extract generateWebLink
=> feat: Export generateWebLink function

helpers/index.js, helpers/withOffline.jsx, package.json
Add a new folder `helpers` to put some of our ... `helpers` we can share across our app. 
Since we don't have decided yet nor having the tooling yet to put those helpers elsewhere, let's put it here and move it later once we know exactly what to do? (hope next week ?)
=> feat: Add withOffline helpers

react/HistoryRow/styles.styl
- remove comment
- change var name
=> refactor: Change the var name and remove comments

docs/styleguide.config.js, package.json, react/ViewStack/Readme.md, react/ViewStack/example.jsx, react/ViewStack/index.jsx, react/ViewStack/index.spec.jsx, react/index.js, yarn.lock
Adds ViewStack that helps building UI with slides that can control an
animated stack of slides.
View here: https://ptbrowne.github.io/cozy-ui/react/#!/ViewStack
=> feat: Implement ViewStack

docs/styleguide.config.js, react/DateMonthPicker/Readme.md, react/DateMonthPicker/index.jsx, react/DateMonthPicker/index.spec.jsx, react/DateMonthPicker/styles.styl
Show a date month picker.
⚠️ This is a very crude picker. We wanted to use [Material UI Datepicker](https://material-ui-pickers.dev/demo/datepicker), but this is only compatible with date-fns2 or moment. I propose that when we migrate, we will change this component to use Material UI date pickers.
=> feat: DateMonthPicker

react/DateMonthPicker/Readme.md, react/DateMonthPicker/index.jsx, react/DateMonthPicker/styles.styl
- iconOnly prop for Buttons with only an icon. Add label for a11y purposes
- Add comment
=> Date month picker tweaks

.travis.yml
On the "merge" job, Travis is on "master". This is why we have to check
if we are not on a PR before pushing the styleguidist.
https://travis-ci.org/cozy/cozy-ui/jobs/618197944#L1150
=> fix: Do not push styleguidist from PRs

react/Field/Readme.md, react/Field/index.jsx, react/Field/styles.styl, react/Labs/CollectionField/Readme.md, react/Labs/CollectionField/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Field now has an inline variant. A little refactor make it available to CollectionField too.
See https://drazik.github.io/cozy-ui/react/#!/Field/3
=> Add inline variant to Field

.travis.yml
Use a token that we can read from password-store
=> chore: Update GH_TOKEN from cozy-bot

react/ContactPicker/Readme.md, react/ContactPicker/index.jsx, react/ContactsListModal/index.jsx, react/ContactsListModal/styles.styl, react/Field/styles.styl, react/Labs/CollectionField/index.jsx
Several things related to contact picker after the integration in Banks in this PR:
* Properly align CollectionField label
* Correctly align « add » button in CollectionField when values are empty
* Fix ContactsListModal styling (see dedicated commit message for more context)
* Add a placeholder for the list modal input in ContactPicker
See https://drazik.github.io/cozy-ui/react/
=> Fixes on contact picker

react/ContactPicker/Readme.md, react/ContactPicker/index.jsx, react/ContactsListModal/AddContactButton.jsx, react/ContactsListModal/EmptyMessage.jsx, react/ContactsListModal/EmptyMessage.styl, react/ContactsListModal/Readme.md, react/ContactsListModal/index.jsx, react/ContactsListModal/styles.styl
Two things related to ContactsListModal in this PR:
* When no contact exists, we rendered an empty list. Now we can pass a message.
* A « add contact » button that redirects to contacts app when clicked has been added
See https://drazik.github.io/cozy-ui/react/#!/ContactsListModal and https://drazik.github.io/cozy-ui/react/#!/ContactPicker
=> Add empty message and add contact button to ContactsListModal

react/Icon/Readme.md, react/Icon/index.jsx
Let use `<Icon icon={Svg} />` where `Svg` is a React component
wrapping an `<svg>` tag.
=> feat: Use React component as icon

react/ContactsList/Contacts/ContactIdentity.jsx, react/ContactsList/__snapshots__/ContactRow.spec.js.snap, react/ContactsList/styles.styl, react/__snapshots__/examples.spec.jsx.snap
Avatar shrinked to 0px when the name was long. It doesn't shrink anymmore.
=> fix(ContactsList): Show avatar even if name is long

react/ContactPicker/index.spec.jsx, react/ContactsList/Contacts/ContactName.jsx, react/ContactsList/ContactsList.jsx, react/ContactsList/data.json, react/ContactsList/helpers.js, react/ContactsList/helpers.spec.js, react/ContactsList/index.js, react/__snapshots__/examples.spec.jsx.snap
When we don't have the name details but only the fullname, we show it. And
we take it into account when keying them on the name.
See https://drazik.github.io/cozy-ui/react/#!/ContactsList
=> Handle contacts fullname in ContactsList

react/InfosCarrousel/Readme.md, react/InfosCarrousel/index.jsx, react/__snapshots__/examples.spec.jsx.snap
See 
https://github.com/cozy/cozy-ui/pull/1321#issuecomment-567830548
for more information.
=> Fix unpredictable tests

react/AppLinker/index.jsx, react/ContactsList/ContactRow.spec.js, react/Field/index.jsx, react/I18n/format.spec.jsx, react/InputGroup/Readme.md, react/Spinner/Readme.md, react/Viewer/PdfJsViewer.spec.jsx, react/__snapshots__/examples.spec.jsx.snap, stylus/utilities/debug.styl, test/jestsetup.js
- Removed expected warnings
- Ignore non problematic warnings
See [issue](https://github.com/cozy/cozy-ui/issues/1318) for more information
=> Less warnings

react/Infos/index.jsx, react/Infos/styles.styl, react/InfosCarrousel/styles.styl, react/__snapshots__/examples.spec.jsx.snap
This PR makes some small UI tweaks for the Infos component, as seen with @joel-costa .
My preview branch is busy with #1347 but I think we can do without it here, it's just changing some spacing values.
=> fix: Adjust Infos UI

.travis.yml, scripts/screenshots.js
Take screenshots in mobile viewport additionally to the desktop viewport.
=> Screenshots in mobile viewport

react/Media/Readme.md, react/__snapshots__/examples.spec.jsx.snap
Very slow to load, slows down screenshots since browsers waits for the
page to load
=> feat: Do not use lorem ipsum

react/hooks/usePeriodicRender.js, react/hooks/usePeriodicRender.spec.js
Allows to rerender the calling component by a given interval
=> feat: Adds useInterval

react/Modal/Readme.md
Simple add to the style guide of what could be a generic confirmation modal
=> docs: Example of confirmation modal

.github/pull_request_template.md
Add checklist not to forget ARIA attributs.
=> docs: Add aria and styleguidist steps

react/Avatar/index.jsx, stylus/settings/palette.styl
The color name is fuchsia, not fushsia.
=> fix: Typo in variable name

docs/styleguide.config.js, react/LoadMore/Readme.md, react/LoadMore/index.jsx
This PR adds a new LoadMore component. [See the demo for more infos](https://yannick-lohse.fr/cozy-ui/react/#!/LoadMore)
=> feat: Load more component

docs/styleguide.config.js, react/UploadQueue/Readme.md, react/UploadQueue/index.jsx, react/UploadQueue/locales/en.json, react/UploadQueue/locales/es.json, react/UploadQueue/locales/fr.json, react/UploadQueue/styles.styl, scripts/screenshots.js
- Extracted component from Drive
- Locales are also extracted and can be tree-shaken
Attributes are added for extra flexibility:
- `popover` can be set to false to display the UploadQueue in the normal
flow (useful for styleguide)
- `app` is added to customize the name of the app in the header
Visible on https://ptbrowne.github.io/cozy-ui/react/#!/UploadQueue
=> feat: Upload Queue

react/UploadQueue/Readme.md, react/UploadQueue/styles.styl
Due to a bug, the background was transparent.
=> Fix background color UploadQueue on mobile

react/QuotaAlert/index.jsx
The small refactor should help having the good displayName
for the component
=> feat: Uses useClient in QuotaAlert

scripts/screenshots.js
Attempt to fix #1413. It seems to work better locally with this, but hard to say since I can't reproduce the bug on demand.
=> chore: Await puppeteer setViewport

react/__snapshots__/examples.spec.jsx.snap
The snapshots are broken on master — see https://travis-ci.org/github/cozy/cozy-ui/builds/673781602. They were ok on #1429 so not sure what happened there.
=> fix: Update snapshots

react/Hero/Readme.md, react/Hero/styles.styl, react/__snapshots__/examples.spec.jsx.snap
Following recent use of Hero in passwords-web.
- Add horizontal margin between sections
- Force CTA zone to have a max-width
=> feat: Hero improvements

docs/styleguide.config.js, react/Breadcrumbs/Readme.md, react/Breadcrumbs/index.jsx, react/Breadcrumbs/styles.styl, stylus/settings/typography.styl
Breadcrumbs from Banks.
I suppose they are different in Drive, maybe we'll have a variant and then
try to reconciliate the two ?
Visible here : https://ptbrowne.github.io/cozy-ui/react/#/Breadcrumbs
=> Breadcrumbs

react/Layout/Layout.jsx, react/Layout/Layout.md, react/Nav/index.jsx, react/Nav/styles.styl, stylus/components/nav.styl
Added secondary nav items.
Extracted styles from store, for usage in Banks
Took this oppportunity to make our example a bit more interactive and closer to reality.
https://ptbrowne.github.io/cozy-ui/react/#/Layout
=> feat: Secondary nav items

react/UploadQueue/Readme.md, react/UploadQueue/index.jsx
- Handle generic failed error instead of showing "pending"
- Show different errors in styleguide
=> feat: Handle errors in UploadQueue

react/NestedSelect/NestedSelect.jsx, react/NestedSelect/NestedSelect.md
- Add item.key (for deduplicating items with the same title)
- Add item.description (used as CompositeRow's secondaryText)
https://ptbrowne.github.io/cozy-ui/react/#/NestedSelect
=> Nested select improvements

react/index.js
- UploadQueue
- ActionMenuItem and ActionMenuHeader
=> Export components from index

stylus/components/nav.styl
- Better colors
- Fixed top margin of nav secondary element
=> Tweaks to Nav

react/NestedSelect/testing.js
Add a means to get options rendered in the NestedSelect.
=> feat: Add testing utility for NestedSelect

react/ActionMenu/Readme.md, react/Tabs/Readme.md, react/__snapshots__/examples.spec.jsx.snap, stylus/components/tabs.styl
On mobile, Tabs grow to fill the available space.
=> feat: Tabs grow to fill the space on mobile

stylus/components/button.styl
It needs to react to a change of theme.
=> feat: Use custom css prop for active color

react/Figure/Figure.styl
=> feat: Semantic custom props for Figure

react/Sidebar/Readme.md, stylus/components/nav.styl, stylus/settings/palette.styl
Custom properties are used to be able to theme nav text.
navTextColor
navTextActiveColor
navTextHoverColor
=> feat: Ability to theme nav text color

docs/styleguide.config.js, react/HistoryRow/index.jsx, react/PushClientButton/index.jsx, react/Wizard/Readme.md, react/Wizard/index.jsx, react/Wizard/styles.styl
Also fixed some bad imports that I do not understand why this had
not been detected before in the CI :/
EDIT: Ah it seems it has been detected, I don't know why I haven't seen it :/ https://travis-ci.org/github/cozy/cozy-ui/builds/709074283#L1112
=> Add Wizard from cozy-authentication

react/NestedSelect/NestedSelect.jsx, react/NestedSelect/NestedSelect.md
- Correct prop types
- Ellipsis by default on the caption (the app does not have to care about that)
See the result in Argos ;) https://www.argos-ci.com/cozy/cozy-ui/builds/584
=> Small improvements on NestedSelect

react/Alerter/Readme.md, stylus/components/alerts.styl
- validColor instead of emerald
- errorColor instead of pomegranate
=> feat: Use validColor instead of emerald for alerts

react/Labs/ExperimentalDialog/Readme.md, react/MuiCozyTheme/Dialog/DialogContent.jsx, react/MuiCozyTheme/Dialog/DialogContentText.jsx, react/MuiCozyTheme/Divider/index.jsx
I'll probably have more changes to ExperimentalModal coming up soon, but here's a first batch : exporting more documents and improving the docs!
=> Dialog changes

react/AppSections/components/AppTile.jsx, react/AppSections/components/AppTile.styl, react/AppSections/components/AppsSection.spec.jsx, react/AppSections/components/__snapshots__/AppsSection.spec.jsx.snap, react/Tile/styles.styl
Follow up of the refactor of AppTile.
Thanks to Quentin for the suggestion in https://github.com/cozy/cozy-ui/pull/1520
=> Refactor to reuse things

stylus/cozy-ui/build.styl, stylus/utilities/text.styl
- Styleguide now have font-weight utilities (normal and bold)
=> feat: Add font-weight to styleguide

react/ActionMenu/index.jsx, react/__snapshots__/examples.spec.jsx.snap, react/examples.spec.jsx, test/testFromStyleguidist.js
Updates the proptypes of action menu and fixes #1524
.
=> fix: ActionMenu proptypes

stylus/cozy-ui/build.styl, stylus/utilities/typography.styl
This is needed in harvest for
https://github.com/cozy/cozy-libs/pull/1066
=> feat: Add u-lowercase class

react/NavigationList/Readme.md, react/NavigationList/index.jsx, react/NavigationList/styles.styl, react/Text/index.jsx, stylus/settings/typography.styl, stylus/utilities/typography.styl
- Use SubTitle on Desktop to remove the impression that it can be
clicked
- Extract the SubTitle from the card
Visible on https://ptbrowne.github.io/cozy-ui/react/#!/NavigationList
=> feat: Tweaks to NavigationList

react/Infos/styles.styl, stylus/settings/palette.styl
It replaces hardcoded colors with semantic ones.
Fixes #1543
=> Semantic color for infos

react/ActionMenu/index.spec.jsx, react/Badge/index.jsx, react/ContactsList/ContactsList.jsx, react/ContactsListModal/AddContactButton.jsx, react/ContactsListModal/DemoProvider.jsx, react/Viewer/TextViewer.spec.jsx, react/__snapshots__/examples.spec.jsx.snap, test/jestsetup.js
Removal of warnings in tests.
The trigger for this PR was the PropTypes.oneOf warnings that broke tests in Banks (the tests in banks are configured to break on console.warn).
=> Removal of warnings in tests.

react/IntentIframe/Readme.md
=> docs: Add link to intents documentation

react/Card/styles.styl, react/DateMonthPicker/styles.styl, stylus/components/card.styl, stylus/cozy-ui/build.styl, stylus/settings/shadows.styl, stylus/utilities/card.styl, stylus/utilities/elevation.styl
- u-card
- Doc for u-stack in CSS styleguide
- u-elevation-1
Fixes https://github.com/cozy/cozy-ui/pull/1555
See https://ptbrowne.github.io/cozy-ui/styleguide/index.html, sections Utilities > Card, Spacings, Elevation
=> Add utility classes

react/Toggle/index.jsx
=> fix: Right path to import Switch

react/Button/Readme.md, react/__snapshots__/examples.spec.jsx.snap, stylus/components/button.styl
Make button full width work with Stack component. Fixes #1561.
=> Button full width does not reset margins

react/Media/Media.jsx
The align--middle class does not exist as it is the default behavior.
=> fix: Do not use align--middle since it does not exist

package.json
=> Add yarn watch

docs/styleguide.config.js, react/AppSections/locales/en.json, react/AppSections/locales/fr.json, react/AppTile/Readme.md, react/AppTile/__snapshots__/AppTile.spec.jsx.snap, react/AppTile/index.jsx, react/AppTile/locales/en.json, react/AppTile/locales/fr.json, react/Tile/styles.styl
- Exported with withLocales (fix #1569)
- Shown in styleguide
- Tile can be shown in a non flex container
=> AppTile improvements

react/Alerter/Readme.md
Current Alerter doc is not working for some exemples
=> docs: Fix Alerter Readme

package.json, react/MuiCozyTheme/theme.js, react/MuiTabs.js, react/Tabs/Readme.md, react/__snapshots__/examples.spec.jsx.snap
Fixes https://github.com/cozy/cozy-ui/issues/1563 and https://github.com/cozy/cozy-ui/issues/1196
Styleguide: https://ptbrowne.github.io/cozy-ui/react/#!/Tab
=> feat: Add theme for MuiTabs and add example

react/Labs/CollectionField/index.jsx
element is for the instance of a component, elementType is
for the class/functional component.
=> fix: Use correct proptype for CollectionField::component

docs/README.md, package.json, react/AppTile/__snapshots__/AppTile.spec.jsx.snap, react/I18n/index.jsx, react/Portal/index.jsx, react/Viewer/ViewerExposer.js, yarn.lock
=> feat: Remove preact

react/ListItemText/Readme.md, react/ListItemText/index.jsx, react/ListItemText/styles.styl, react/MuiCozyTheme/List/Readme.md, react/MuiCozyTheme/ListItemIcon/index.js, react/MuiCozyTheme/theme.js, react/NavigationList/Readme.md, react/__snapshots__/examples.spec.jsx.snap
- Use Typography components for list items
- Conform to design specs
Fix https://github.com/cozy/cozy-ui/issues/1600#issuecomment-707185707
=> feat: Tweak NavList

react/IntentOpener/IntentExample.jsx
Resulting by having wrong screenshots on argos. Let's fix that :)
=> fix: Lorempixel is down lets use another service

react/Avatar/Readme.md, react/Avatar/index.jsx, react/Avatar/styles.styl, react/ContactsList/__snapshots__/ContactRow.spec.js.snap, react/__snapshots__/examples.spec.jsx.snap
- Disabled avatar are greyed
See example here https://jf-cozy.github.io/cozy-ui/react/#!/Avatar
There is a little tiny difference between Chrome and Firefox in the grey color of image avatar
=> feat: Avatar can be disabled

react/CozyDialogs/ConfirmDialog.jsx, react/CozyDialogs/IllustrationDialog.jsx
=> fix: Misspelled propTypes

react/Avatar/Readme.md, react/Avatar/index.jsx, react/Avatar/styles.styl, react/Circle/Readme.md, react/Circle/index.jsx, react/Circle/styles.styl, react/ContactsList/__snapshots__/ContactRow.spec.js.snap, react/__snapshots__/examples.spec.jsx.snap, stylus/components/avatar.styl, stylus/components/circle.styl
We would like to add a 24px size for the Avatars => we can now use specific size for avatars.
There was also a need to correct some overlapping behavior.
Circle is improved as well
Avatar : https://jf-cozy.github.io/cozy-ui/react/#!/Avatar
Circle : https://jf-cozy.github.io/cozy-ui/react/#!/Circle
=> Improve Circle and Avatar to use specific size

react/QuotaAlert/Readme.md, react/QuotaAlert/index.jsx
Use a CozyDialog instead of Modal
=> feat: Use CozyDialog in QuotaAlert

.travis.yml, package.json, scripts/screenshots.js
Add screenshots for the KSS styleguide.
Utilities are not screenshotted as their screenshots are huge.
=> feat: Screenshot KSS styleguide

react/Banner/index.jsx, react/CozyDialogs/Dialog.jsx, react/CozyDialogs/FixedActionsDialog.jsx, react/CozyDialogs/FixedDialog.jsx, react/CozyDialogs/useCozyDialog.js, react/Dialog/Readme.md, react/Empty/Readme.md, react/Empty/index.jsx, react/MuiCozyTheme/Divider/Readme.md, react/MuiCozyTheme/Divider/index.jsx, react/MuiCozyTheme/List/Readme.md, react/MuiCozyTheme/List/index.js, react/MuiCozyTheme/RaisedList/README.md, react/MuiCozyTheme/theme.js, react/NavigationList/Readme.md, react/Tabs/Readme.md, react/__snapshots__/examples.spec.jsx.snap
- Text: text secondary color is grey
- Empty: Use Typography components
- Divider and List/ListItem: allow to use the inset border pattern
The last change is a breaking change, I can split the PR if
necessary. I have added components that have the old behavior that
we had inscribed in our theme to facilitate the migration. I think
it is not too difficult to do the search/replace but I could add
a codemod if necessary.
https://ptbrowne.github.io/cozy-ui/react/#!/List
=> Improvements

react/AppTile/index.jsx
add showStatus (with true as default value) in component props
=> fix: Can or not show status in AppTile

react/CozyTheme/Readme.md, react/CozyTheme/styles.styl, react/UploadQueue/styles.styl, stylus/settings/palette.styl, stylus/utilities/text.styl
Commits should be self explanatory, u-link will correctly work
in inverted theme now (important for vault unlock dialog).
=> Better support for u-links in inverted theme

react/Viewer/InformationPanel.jsx, react/Viewer/Navigation.jsx, react/Viewer/Readme.md, react/Viewer/Toolbar.jsx, react/Viewer/ViewerControls.jsx, react/Viewer/ViewerWrapper.jsx, react/Viewer/controls.styl, react/Viewer/index.jsx, react/Viewer/index.spec.jsx
On souhaite améliorer le Viewer actuel, et intégrer un panneau d'information sur le côté afin de lister des infos concernant le fichier ouvert, et ajouter des actions. On l'appelle le Viewer Augmenté.
Ceci est la première itération : 
- modification du Viewer actuel pour coller au style du Viewer augmenté
- ajout de la possibilité d'activer le mode "augmenté" du viewer (ajout du panneau d'info sur le côté)
Le contenu du panneau ne fait volontairement pas partie de cette PR.
**approved by @joel-costa** 
=> First iteration of new Viewer

docs/README.md
Add paragraph on how to code a new component
=> docs: Add guidelines for component development;

react/ActionMenu/Readme.md, react/BottomDrawer/Readme.md, react/Card/Readme.md, react/CompositeRow/Readme.md, react/CompositeRow/index.jsx, react/ContactsListModal/EmptyMessage.jsx, react/DropdownButton/Readme.md, react/Figure/FigureBlock.md, react/InfosCarrousel/Readme.md, react/InfosCarrousel/index.spec.jsx, react/InputGroup/Readme.md, react/ListItemText/Readme.md, react/MuiCozyTheme/Switch/Readme.md, react/ProgressionBanner/Readme.md, react/__snapshots__/examples.spec.jsx.snap, stylus/components/card.styl
Better theme support, and remove our deprecated Text components from our internal components.
=> Replace text by typography components

react/MuiCozyTheme/theme.js, react/Tooltip/Readme.md, react/Tooltip/index.jsx
to better match with the design.
Add screenshot test too.
https://jf-cozy.github.io/cozy-ui/react/#!/Tooltip
=> feat: Add arrow on Tooltip and change style

react/Alerter/Alert.jsx, react/Alerter/alerter.spec.js, react/Alerter/index.jsx, react/CozyTheme/styles.styl, react/Infos/styles.styl, react/UploadQueue/styles.styl, stylus/components/alerts.styl, stylus/cozy-ui/build.styl, stylus/settings/palette.json, stylus/settings/palette.styl
Ability to override AlertInfo background colors.
We add a level of indirection so that we can override only the background color
of a type of Alert.
=> Alert info color override

react/CozyDialogs/DialogBackButton.jsx, react/CozyDialogs/Readme.md, react/Dialog/index.jsx, react/__snapshots__/examples.spec.jsx.snap
PR necessary in order to correct the fact that with the addition of the theme via CozyTheme, it adds a tag in the children of Dialog, thus modifying the internal structure expected by Mui, thus changing the behavior of Mui Dialog.
This was particularly the case with FixedDialogs, which were no longer fixed.
https://jf-cozy.github.io/cozy-ui/react/#!/CozyDialogs
=> Fix Dialogs and CozyDialogs theme

react/Viewer/Toolbar.jsx, react/Viewer/index.jsx
will be merged since it's just very minors fixes
=> fix: Viewer defaultProps and Toolbar title position

react/Viewer/index.jsx
will be merged automatically since it's a very small fix *cough*
=> fix: Viewer panelInfoProps defaultProps

react/Stack/Readme.md
and use radio to switch examples
fix https://github.com/cozy/cozy-ui/issues/1712
https://jf-cozy.github.io/cozy-ui/react/#!/Stack
=> docs: Change Stack doc to show default spacing

react/Viewer/Readme.md, react/Viewer/Toolbar.jsx, react/Viewer/controls.styl, react/Viewer/styles.styl
Suite aux retours de @joel-costa et @poupotte, la toolbar ne doit pas couvrir le contenu. Quelques correctifs de style également (voir noms des commits)
=> Viewer full page behavior : toolbar no longer cover the content

react/ContactPicker/index.jsx
=> fix: Destructure prop to avoid passing it to children

react/Field/Readme.md, react/MuiCozyTheme/Buttons/Readme.md, react/MuiCozyTheme/theme.js, react/UploadQueue/styles.styl, react/__snapshots__/examples.spec.jsx.snap
- Add interactive way to set size
- Add icon to default and primary button
- Tweak theme for size variants
=> feat: Better example for mui buttons

react/Viewer/Readme.md
=> docs: Fix Viewer doc

react/IntentDialogOpener/IntentDialogOpener.jsx, react/IntentIframe/IntentIframe.jsx
Dans notre cas, on souhaite dans Banks ouvrir le file viewer de Drive, qui a un fond charcoalGrey. On souhaite donc dans Banks pouvoir spécifier à IntentDialogOpener d'utiliser un spinner blanc sur un fond charcoalGrey
=> feat: IntentIframe can receive props to be tweaked

CHANGELOG.md, package.json, react/Viewer/ImageLoader.jsx, react/Viewer/ImageViewer.jsx, react/Viewer/NoNetworkViewer.jsx, react/Viewer/NoViewer/FileIcon.jsx, react/Viewer/PdfMobileViewer.jsx, react/Viewer/PdfMobileViewer.spec.jsx, react/Viewer/Readme.md, react/Viewer/ViewerControls.jsx, react/Viewer/ViewerWrapper.jsx, react/Viewer/__snapshots__/ShortcutViewer.spec.jsx.snap, react/Viewer/__snapshots__/TextViewer.spec.jsx.snap, react/Viewer/__snapshots__/index.spec.jsx.snap, react/Viewer/docs/DemoProvider.jsx, react/Viewer/index.jsx, react/Viewer/locales/en.json, react/Viewer/locales/fr.json, react/Viewer/styles.styl, stylus/components/alerts.styl, yarn.lock
Sur mobile, lors de la visualisation d'un fichier pdf, on souhaite maintenant avoir l'aperçu de la premiere page du pdf comme image plutôt que le pdf lui-même. Une interaction sur cette image provoque un téléchargement du fichier (browser) ou l'ouverture dans une app externe (app native)
exemple : https://jf-cozy.github.io/cozy-ui/react/#!/Viewer
=> Add PdfMobileViewer on Viewer

react/Viewer/ImageLoader.jsx, react/Viewer/PdfMobileViewer.spec.jsx
we don't want any console log in tests
=> Remove console log from Viewer tests

react/UploadQueue/styles.styl, react/Viewer/Readme.md, react/Viewer/controls.styl, stylus/settings/z-index.styl
BREAKING CHANGE: The footer is now only a simple bottom container
The style have to be set in the application
Le besoin ici est de pouvoir ajouter ce qu'on veut dans le footer, notamment un bottomsheet. Par conséquent on ne veut pas qu'il y a du style inutile comme le border par exemple.
=> Viewer no longer enforce footer style

react/Viewer/Toolbar.jsx, react/Viewer/controls.styl
=> fix: Viewer toolbar back button position

react/MuiCozyTheme/theme.jsx, react/NestedSelect/NestedSelect.jsx
- List item have the correct hover/selected color in inverted theme
- NestedSelect navigation right icon correctly reacts to inverted theme
=> Inverted theme improvements

react/Viewer/Footer.jsx, react/Viewer/Toolbar.jsx, react/Viewer/ViewerControls.jsx, react/Viewer/ViewerSpinner.jsx, react/Viewer/controls.styl, react/Viewer/styles.styl
On souhaite avoir un comportement sur tablette identique à celui sur mobile, et non à celui sur desktop.
Cela veut dire : 
- un fond blanc et non gris foncé
- une toolbar blanche avec du texte gris et pas de bouton download
- pas de panel à droite
- un footer si nécessaire
=> feat: Viewer on tablet is now like on mobile

stylus/cozy-ui/build.styl
=> fix: Typo in CSS styleguide

react/AppSections/Sections.jsx, react/AppSections/Sections.styl
Spacing was a bit small, saw it in the store.
=> fix: Spacing in AppSections

assets/icons/illus/file-type-slide.svg, react/Icons/FileTypeSlide.jsx, react/__snapshots__/examples.spec.jsx.snap
=> feat: Replace Slide icon by vertical one

react/IntentIframe/IntentIframe.jsx, react/Viewer/Footer.jsx, react/Viewer/Toolbar.jsx, react/Viewer/ViewerByFile.jsx, react/Viewer/ViewerSpinner.jsx
to prevent breakpoint bug in intents, see https://github.com/cozy/cozy-ui/issues/1807
=> refactor: Viewer - use withBreakpoints instead of useBreakpoints

react/CozyDialogs/ConfirmDialog.jsx, react/CozyDialogs/Dialog.jsx, react/CozyDialogs/FixedActionsDialog.jsx, react/CozyDialogs/FixedDialog.jsx, react/CozyDialogs/IllustrationDialog.jsx, react/CozyDialogs/Readme.md, react/MuiCozyTheme/theme.jsx
- fix Title width on desktop and mobile
- adjust Title width according to close button
- remove back button if no close fn
=> fix: CozyDialogs Title width and close button

react/MuiCozyTheme/ListItemIcon/index.js, react/MuiCozyTheme/theme.jsx, react/__snapshots__/examples.spec.jsx.snap
This way ListItemIcon is only re-exported and we have access to
its type definition in apps
=> feat: Put styles as part of theme

react/CozyTheme/styles.styl, react/MuiCozyTheme/Divider/Readme.md, react/MuiCozyTheme/theme.jsx, stylus/settings/palette.styl
fix https://github.com/cozy/cozy-ui/issues/1811
fix https://github.com/cozy/cozy-ui/issues/1812
see examples here : 
https://jf-cozy.github.io/cozy-ui/react/#!/Divider
https://jf-cozy.github.io/cozy-ui/react/#!/CozyDialogs
https://jf-cozy.github.io/cozy-ui/styleguide/section-settings.html#kssref-settings-theme-components
=> fix: Divider styles

react/Checkbox/Readme.md, react/Checkbox/index.jsx, react/MuiCozyTheme/theme.jsx, react/Viewer/Readme.md, react/__snapshots__/examples.spec.jsx.snap
BREAKING CHANGE: Checkbox no longer accept `name` prop
before : https://docs.cozy.io/cozy-ui/react/#!/Checkbox
after : https://jf-cozy.github.io/cozy-ui/react/#!/Checkbox
MUI theme doc : https://next.material-ui.com/customization/default-theme/#main-content
Pour vérifier les interrogations concernant le viewer : 
before : https://docs.cozy.io/cozy-ui/react/#!/Viewer
after : https://jf-cozy.github.io/cozy-ui/react/#!/Viewer
=> feat: Replace our custom Checkbox by MUI checkbox API

react/SelectionBar/index.jsx
See commit message
Corrections/améliorations mineures donc mergé dès que CI verte (nécessaire sur Banks)
=> SelectionBar fixes for key, label and tests

react/IconStack/Readme.md, react/IconStack/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Ayant besoin de surcharger le style du wrapper de l'icône au premier plan, je vous propose une amélioration du composant IconStack, par l'ajout d'une prop foregroundClassName.
Par la même, j'en ai profité pour clarifier un peu plus le nom des autres props :)
=> feat: Improve IconStack

docs/dev.md
Old procedure was not up to date.
=> docs: Update procedure for local screenshots generation

react/Banner/Readme.md
In order to have documentation relevant to the use case
=> docs: Banner example show real Drive usecase now

stylus/cozy-ui/build.styl
Les classes utilitaires se base sur ces couleurs : https://github.com/cozy/cozy-ui/blob/master/stylus/utilities/colors.styl
=> Update styleguide colored text documentation

react/Modal/Readme.md
fix https://github.com/cozy/cozy-ui/issues/1870
=> docs: Fix Modal documentation

docs/how-to-transpile.md, examples/parcel-app/App.js, examples/webpack-app/App.js, examples/webpack-app/index.js, react/Icon/Sprite.jsx, react/index.js
This PR is the continuation of this one #1908 
In several places there were bad Sprite imports.
Which might give us messages like :
```console
WARNING in ./node_modules/cozy-ui/transpiled/react/index.js 10:0-63
"export 'Sprite' (reexported as 'IconSprite') was not found in './Icon'
```
=> fix: Change import about Sprite

react/MuiCozyTheme/theme.jsx
see https://v4.mui.com/fr/customization/default-theme/
=> fix: Action prop in mui palette

react/MuiCozyTheme/makeOverrides.js
sera mergé dès que CI verte, nécessaire pour débloquer une beta Maif
=> fix: Border color of Accordion

react/ContactsList/helpers.spec.js, react/Viewer/AudioViewer.spec.jsx, react/Viewer/PdfMobileViewer.spec.jsx, react/Viewer/ShortcutViewer.spec.jsx, react/Viewer/VideoViewer.spec.jsx
wait is deprecated and adds a few warnings when testing
=> test: Use waitFor instead of wait

react/ContactsList/helpers.spec.js, react/Viewer/AudioViewer.spec.jsx, react/Viewer/PdfMobileViewer.spec.jsx, react/Viewer/ShortcutViewer.spec.jsx, react/Viewer/VideoViewer.spec.jsx
⚠️ this is a supposition, CI is broken since the last merge into master, so let's wait until the CI confirm the fix
___
This reverts commit ba948b4778efa0c3cfa35258fa0eb48873661e2a.
Usage of WaitFor instead of Wait breaks the CI
=> fix: Revert "Merge pull request #1956 from cozy/test/waitFor"

react/Icons/LogoutLarge.jsx, react/SquareAppIcon/index.jsx, react/SquareAppIcon/styles.styl, react/__snapshots__/examples.spec.jsx.snap
to get a better display in different sizes
=> fix: Add viewBox to LogoutLarge icon

react/ActionMenu/Readme.md, react/__snapshots__/examples.spec.jsx.snap
to simplify documentation
see https://jf-cozy.github.io/cozy-ui/react/#!/ActionMenu
=> docs: Use variants for ActionMenu

react/BarTitle/Readme.md, react/BarTitle/index.jsx
to show title with an ellipsis
=> https://jf-cozy.github.io/cozy-ui/react/#!/BarTitle
=> feat: Add `noWrap` prop on BarTitle

react/Viewer/Footer/BottomSheetContent.jsx, react/Viewer/Footer/FooterContent.jsx, react/Viewer/index.jsx
Added prop for show/hide the cozy sharing button on mobile Viewer.
=> feat: Disable sharing button on Viewer

package.json, react/Viewer/Footer/BottomSheetContent.jsx, react/Viewer/Panel/Certifications.jsx, react/Viewer/Panel/PanelContent.jsx, react/Viewer/Panel/Qualification.jsx, react/Viewer/Panel/QualificationListItemText.jsx, react/Viewer/Panel/getPanelBlocks.jsx, react/Viewer/Readme.md, react/Viewer/docs/DemoProvider.jsx, react/Viewer/helpers.js, react/Viewer/helpers.spec.js, react/Viewer/index.jsx, react/Viewer/locales/en.json, react/Viewer/locales/fr.json, react/Viewer/queries.js, yarn.lock
This panel allows to display the following qualification informations:
- Name of the file
- Qualification
If qualified via the "My papers" application,
it to display additional information
(depending on the information provided):
- Date obtained / expiration date
- Name of the owner
Demo: https://merkur39.github.io/cozy-ui/react/#!/Viewer/1 (file N°4)
=> feat: Added Qualification panel block

react/FilePicker/docs/DemoProvider.jsx
Demo here : https://merkur39.github.io/cozy-ui/react/#!/FilePicker/1
=> fix: Show breadcrumb on FilePicker documentation

package.json, react/MuiCozyTheme/makeOverrides.js, react/MuiCozyTheme/makeTheme.js, react/__snapshots__/examples.spec.jsx.snap, yarn.lock
afin de supprimer les warnings du fait qu'une app peut avoir la version 4.12.3 et cozy-ui la version 4.11
=> Upgrade mui to 4.12.3

react/Avatar/Readme.md, react/Avatar/index.jsx, react/Avatar/styles.styl, react/__snapshots__/examples.spec.jsx.snap
We will need to handle a new style type named `ghost`.
Used very soon on the CoachCO2 application.
Demo: https://merkur39.github.io/cozy-ui/react/#!/Avatar
=> feat(Avatar): Add ghost property

react/MuiCozyTheme/makePalette.js
Inverted theme use previously the same values as Normal theme
=> fix: Inverted palette opacity values

react/BottomSheet/BottomSheet.jsx, react/BottomSheet/README.md
=> chore(BottomSheet): Fix typo in documentation

react/Banner/index.jsx, react/Banner/index.spec.jsx
This triggers a lot of warnings in our application
cozy-sharing Banner is waiting for that change
I forgot that part
=> fix(Grid): Use justifyContent props inside Grid component

.github/auto-merge.yml
during : https://github.com/cozy/cozy-ui/pull/1696 , I noticed 
:
=> chore(automerge): Fix auto-merge job what unallowed used merge commits

react/AppIcon/index.jsx, react/AppLinker/index.jsx, react/Icons/Cube.jsx
When opening an application from the home screen, we want to send with cozy-intent the position and dimensions of the icon that was clicked on
=> feat: Implement openApp animation from cozy-ui

react/ActionMenu/__snapshots__/index.spec.jsx.snap, react/ActionMenu/index.spec.jsx, react/__snapshots__/examples.spec.jsx.snap, react/examples.spec.jsx
because of the delay, it was necessary to constantly update the
examples.spec snapshots. Hope this fix the problem
=> test: Move ActionMenu snapshot in component tests

react/ContactPicker/index.spec.jsx, react/ContactsList/ContactRow.jsx, react/ContactsList/ContactRow.spec.js, react/ContactsList/Contacts/ContactCozy.jsx, react/ContactsList/Contacts/ContactEmail.jsx, react/ContactsList/Contacts/ContactIdentity.jsx, react/ContactsList/Contacts/ContactName.jsx, react/ContactsList/Contacts/ContactPhone.jsx, react/ContactsList/ContactsList.jsx, react/ContactsList/__snapshots__/ContactRow.spec.js.snap, react/ContactsList/styles.styl, react/__snapshots__/examples.spec.jsx.snap, stylus/components/table.styl
Les composants dans l'app Contacts ont évolué de leur côté, et n'étaient pas ceux de cozy-ui. On remet donc cozy-ui iso avec l'app Contacts.
Côté app on utilise maintenant les composants de cette PR (cf https://github.com/cozy/cozy-contacts/pull/868) pour s'assurer qu'il n'y a pas de regression.
=> fix: ContactsList display always the right data

react/Filename/Readme.md, react/Filename/index.jsx
Added the prop `variant` to have more flexibility on the text.
Ref: #2018
=> feat: Add variant prop to Filename component

package.json
=> chore: Remove prepush commands

.bundlemonrc, .travis.yml, package.json, yarn.lock
during #2094, we would like to measure impact in bundle of setting Material UI as dependencies, that's why I set Bundlemon to make the job
=> chore(bundlemon): Add bundlemon reporter

react/CozyDialogs/Readme.md
=> Cleaner doc for CozyDialogs

docs/README.md, docs/dev.md
=> Add some missing points in the main documentation

react/Viewer/Footer/DownloadButton.jsx, react/Viewer/Footer/ForwardButton.jsx
Demo (via Viewer component): https://merkur39.github.io/cozy-ui/react/#!/Viewer
=> feat: Update the Viewer buttons to use the new cozy-ui Buttons

react/MuiCozyTheme/makeTheme.js
Demo: https://merkur39.github.io/cozy-ui/react/#!/List
=> feat(ListItem): Active ripple effect

react/MuiCozyTheme/makeOverrides.js
demo : https://jf-cozy.github.io/cozy-ui/react/#!/CozyDialogs (check "actionsLayoutColumn checkbox)
=> fix(CozyDialogs): Remove margin on action buttons for column layout

package.json, react/UploadQueue/index.jsx, yarn.lock
pas de changement dans la doc (qui est mockée)
=> UploadQueue : The progress bar changes correctly every second

react/DropdownText/Readme.md, react/DropdownText/index.jsx, react/__snapshots__/examples.spec.jsx.snap
- innerTextProps : props passed to the text
- innerIconContainerProps : props passed to the icon container
- innerIconProps : props passed to the icon
demo : https://jf-cozy.github.io/cozy-ui/react/#!/DropdownText
=> feat(DropdownText): Add possibility to ellipsis text and pass more props

react/IconStack/Readme.md, react/IconStack/index.jsx, react/__snapshots__/examples.spec.jsx.snap
to offset the inner icon
demo : https://jf-cozy.github.io/cozy-ui/react/#!/IconStack
fix https://github.com/cozy/cozy-ui/issues/1663
=> feat(IconStack): Add offset prop

react/MuiCozyTheme/makeOverrides.js
demo : https://jf-cozy.github.io/cozy-ui/react/#!/List
=> fix(ListSubheader): Only 1rem of text indent on mobile

react/Chips/Readme.md, react/Chips/index.jsx, react/__snapshots__/examples.spec.jsx.snap
=> Chips: ref forwarding + style fix

package.json
fix #1865
This PR will only be merged once we are sure it won't increase bundle size.
Needed to merged https://github.com/cozy/cozy-libs/pull/1530
=> feat(deps): Material UI is dependency of CozyUI

react/MuiCozyTheme/makeOverrides.js
=> refactor(Buttons): Move borderRadius on root element

.travis.yml
see fec1006f4620a261f67494c789f87fe0dc36ba6c
=> chore: Remove temporary script in travis

react/Nav/index.jsx, react/Sidebar/Readme.md
to generate styled NavLink for react-routeur v6
=> feat: Add genNavLinkForV6() in Nav component

package.json, react/BottomSheet/BottomSheet.jsx, react/BottomSheet/README.md, yarn.lock
see commit messages
testé dans la doc de cozy-ui + Banks
testé également sur iphone 8 iOS 15.5
fix https://github.com/cozy/cozy-ui/issues/2233
demo : https://jf-cozy.github.io/cozy-ui/react/#!/BottomSheet et https://jf-cozy.github.io/cozy-ui/react/#!/CozyDialogs
=> Multiple fix for BottomSheet

react/Viewer/Panel/Qualification.jsx, react/Viewer/Readme.md, react/Viewer/styles.styl
demo : https://polaritoon.github.io/cozy-ui/react/#!/Viewer
=> Prevent filename overflowing in the viewer

assets/icons/ui/swap.svg, react/Icon/Readme.md, react/Icons/Swap.jsx, react/__snapshots__/examples.spec.jsx.snap
Used in cozy-settings in the mobile app.
=> feat: Add Swap icon

react/Viewer/Panel/ActionMenuDesktop.jsx, react/Viewer/Panel/ActionMenuMobile.jsx, react/Viewer/Panel/ActionMenuProvider.jsx, react/Viewer/Panel/ActionMenuWrapper.jsx, react/Viewer/Panel/Qualification.jsx, react/Viewer/Panel/QualificationListItemContact.jsx, react/Viewer/Panel/QualificationListItemOther.jsx, react/Viewer/Panel/styles.styl, react/Viewer/Readme.md, react/Viewer/ViewerContainer.jsx, react/Viewer/docs/DemoProvider.jsx, react/Viewer/helpers.js, react/Viewer/helpers.spec.js, react/Viewer/locales/en.json, react/Viewer/locales/fr.json
Ajout de l'option "Modifier" sur tous les attributs listés à l'exception des suivants :
- Date de création
- Qualification
- Titulaire (futur développement)
Cette option ne sera pas présente sur les applications Drive & Photos pour le moment.
Démo : https://merkur39.github.io/cozy-ui/react/#!/Viewer
=> Add edit option to Viewer informations

react/ActionMenu/ActionMenuHeader.jsx, react/ActionMenu/ActionMenuItem.jsx, react/ActionMenu/ActionMenuRadio.jsx, react/ActionMenu/ActionMenuWrapper.jsx, react/ActionMenu/NotInlineWrapper.jsx, react/ActionMenu/index.jsx
to better update them later. No code change
=> refactor(ActionMenu): Extract code in some components

react/Viewer/Panel/Qualification.jsx, react/Viewer/Panel/QualificationListItemInformation.jsx, react/Viewer/Panel/QualificationListItemNumber.jsx, react/Viewer/helpers.js, react/Viewer/helpers.spec.js, react/Viewer/locales/en.json, react/Viewer/locales/fr.json
Les utilisateurs ont maintenant la possibilité de créer un Permis de conduire étranger.
Les informations de celui-ci diffèrent du Permis de conduire français.
=> Add metadata for stranger driver license

react/Input/__snapshots__/index.spec.jsx.snap, react/Input/index.jsx, react/__snapshots__/examples.spec.jsx.snap
fix https://github.com/cozy/cozy-ui/issues/2250
=> feat(Input): Disables spell checking

scripts/generate-svgr-icon.sh, scripts/svgr-template.js
=> chore: Use sed instead of gsed on linux

react/MuiCozyTheme/List/Readme.md, react/MuiCozyTheme/makeOverrides.js, react/NestedSelect/ItemRow.jsx, react/NestedSelect/NestedSelect.jsx, react/NestedSelect/NestedSelect.md
BREAKING CHANGE: Style, color and position of List elements have been readjusted. The result may not be appropriate for your use case, refer to the documentation to apply adjustments if necessary.
demo : https://jf-cozy.github.io/cozy-ui/react/#!/List
=> fix(List): Change default color and position of  List element

react/ActionMenu/ActionMenuWrapper.jsx, react/ActionMenu/Readme.md, react/ActionMenu/index.jsx, stylus/components/action-menu.styl
fix https://github.com/cozy/cozy-ui/issues/1848
=> feat(ActionMenu): Use BottomSheet instead of  BottomDrawer on mobile

react/ContactsList/ContactsList.jsx, react/MuiCozyTheme/List/Readme.md, react/MuiCozyTheme/makeOverrides.js, react/UploadQueue/index.jsx, react/__snapshots__/examples.spec.jsx.snap
L'utilisation de List et de ses sous-composants n'étaient pas bonne par rapport à le doc Mui. On corrige donc ici le style et surtout l'utilisation dans la documentation cozy-ui
demo:
- https://jf-cozy.github.io/cozy-ui/react/#!/List
=> Adjust List styles and usage

react/Table/Readme.md, react/Table/index.jsx
Let's forward ref for our Table's components. 
Fix https://github.com/cozy/cozy-ui/issues/1678 
http://crash--.github.io/cozy-ui/react/#/Table
=> feat: Table components now forward ref

react/Viewer/Panel/QualificationListItemInformation.jsx, react/Viewer/Panel/QualificationListItemInformation.spec.jsx, react/Viewer/helpers.js, react/Viewer/locales/en.json, react/Viewer/locales/fr.json
Ajout de la metadata `noticePeriod`, dans le Viewer, afin de pouvoir la voir et la modifier
=> feat(Viewer): Add notice period metadata

react/BottomSheet/README.md, react/Viewer/Readme.md, react/Viewer/ViewerContainer.jsx, react/Viewer/proptypes.js
https://jf-cozy.github.io/cozy-ui/react/#!/BottomSheet
=> Add some doc for BottomSheet and Viewer

react/BottomSheet/BottomSheetHeader.jsx, react/BottomSheet/BottomSheetItem.jsx, react/BottomSheet/BottomSheetTitle.jsx, react/BottomSheet/README.md, react/BottomSheet/index.jsx, react/index.js
Ajoute un BottomSheetTitle qui prend soit : 
- un label et affiche un Typography h6
- un label et une icon et affiche un ListItem h6
Demo : https://zatteo.github.io/cozy-ui/react/#!/BottomSheet
=> feat: Add BottomSheetTitle

react/AppSections/search.js
This way we can filter on qualification labels.
=> feat: Add Filter on qualificationLabels

react/Avatar/index.jsx, react/ContactsList/Contacts/ContactCozy.jsx, react/ContactsList/Contacts/ContactEmail.jsx, react/ContactsList/Contacts/ContactIdentity.jsx, react/ContactsList/Contacts/ContactName.jsx, react/ContactsList/Contacts/ContactPhone.jsx, react/ContactsList/__snapshots__/ContactRow.spec.js.snap, react/__snapshots__/examples.spec.jsx.snap
There wasn't any straightforward way to retrieve these elements.
This will help rewriting some of `cozy-contacts`' tests in order to upgrade to React 18.
=> Add some test ids for use by `cozy-contacts` tests

react/ActionMenu/index.spec.jsx, react/Alerter/alerter.spec.js, react/AppIcon/test/AppIcon.spec.js, react/AppLinker/index.deprecated.spec.jsx, react/AppLinker/index.spec.jsx, react/AppLinker/native.js, react/AppTile/AppTile.spec.jsx, react/Banner/index.spec.jsx, react/CipherIcon/index.spec.jsx, react/ContactsListModal/index.jsx, react/DateMonthPicker/index.spec.jsx, react/Field/index.spec.js, react/FileInput/index.spec.jsx, react/FilePicker/FilePickerHeader.jsx, react/I18n/withLocales.jsx, react/Input/index.spec.jsx, react/Modal/index.spec.jsx, react/PieChart/index.spec.jsx, react/Popup/index.spec.jsx, react/PushClientButton/index.spec.jsx, react/Radio/index.spec.jsx, react/SquareAppIcon/SquareAppIcon.spec.js, react/UploadQueue/index.spec.jsx, react/ViewStack/example.jsx, react/ViewStack/index.spec.jsx, react/Viewer/Viewer.jsx, react/Viewer/ViewerExposer.js, react/Viewer/components/ViewerControls.jsx, react/hooks/useConfirmExit/index.spec.js
Minor changes that should be uncontentious (the last commit is labelled "feat" in order to trigger a publication, because I mislabeled the last merged PR).
=> Use extensionless specifiers when importing JS files

react/Avatar/index.jsx, react/ContactsList/Contacts/ContactCozy.jsx, react/ContactsList/Contacts/ContactEmail.jsx, react/ContactsList/Contacts/ContactIdentity.jsx, react/ContactsList/Contacts/ContactName.jsx, react/ContactsList/Contacts/ContactPhone.jsx, react/ContactsList/__snapshots__/ContactRow.spec.js.snap, react/__snapshots__/examples.spec.jsx.snap
See #2353. Snapshots have been adapted to the `next` branch.
=> Port "Add some test ids for use by cozy-contacts tests" to `next`

.travis.yml, docs/styleguide.config.js, package.json, release.config.js
La méthode de fetch de l'ancienne doc n'est pas optimale, mais c'est une première itération par manque de temps. Il y a d'autres problématiques à vérifier (côté Argos et NPM)
=> Test ci branch next

react/Viewer/Panel/Qualification.jsx, react/Viewer/Panel/QualificationListItemInformation.jsx, react/Viewer/helpers.js, react/Viewer/locales/en.json, react/Viewer/locales/fr.json
Cette PR sert principalement à trigger le déploiement d'une nouvelle version suite à cette PR https://github.com/cozy/cozy-ui/pull/2378
Elle ajoute également un flag autour de chaque changements provocant une regression tant que le service de migration de Mespapiers n'est pas disponible
=> refactor: Use deep import

react/MuiCozyTheme/List/Readme.md, react/MuiCozyTheme/ListItem/ExpandedAttributes/index.jsx, react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/ActionMenuItemWrapper.jsx, react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/Actions/call.js, react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/Actions/emailTo.js, react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/Actions/hr.js, react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/Actions/modify.js, react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/Actions/smsTo.js, react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/Actions/viewInContacts.js, react/MuiCozyTheme/ListItem/ListItemBase/Renaming/RenameDialog.jsx, react/MuiCozyTheme/ListItem/ListItemBase/index.jsx, react/MuiCozyTheme/ListItem/ListItemContact/index.jsx, react/MuiCozyTheme/ListItem/ListItemContact/useActions.jsx, react/MuiCozyTheme/ListItem/ListItemFile/ExpirationAnnotation.jsx, react/MuiCozyTheme/ListItem/ListItemFile/PrimaryText.jsx, react/MuiCozyTheme/ListItem/hoc/withListItemLocales.jsx, react/MuiCozyTheme/ListItem/locales/en.json, react/MuiCozyTheme/ListItem/locales/fr.json
see https://jf-cozy.github.io/cozy-ui/react/#!/List - Contextualized item
je pense qu'on devrait sortir les actions et tout ce qui est relatif aux ActionsMenu et les regrouper avec ActionMenu. Ce sera l'objet d'une prochaine PR pour ne pas polluer/ralentir cette PR.
=> Add default actions on ListItemContact

react/Filename/index.jsx, react/MuiCozyTheme/ListItem/ExpandedAttributes/ExpandedAttribute.jsx, react/MuiCozyTheme/ListItem/ExpandedAttributes/helpers.js, react/MuiCozyTheme/ListItem/ExpandedAttributes/helpers.spec.js, react/MuiCozyTheme/ListItem/ListItemByDoc/index.jsx, react/MuiCozyTheme/ListItem/ListItemContact/index.jsx, react/MuiCozyTheme/ListItem/ListItemFile/index.jsx, react/MuiCozyTheme/ListItem/locales/en.json, react/MuiCozyTheme/ListItem/locales/fr.json
Certains attributs indexés dans la recherche n'étaient pas pris en compte, il y avait un bug avec les nombres interprétés comme étant des dates, et on expose une méthode pour faciliter l'intégration côté app
=> Enhanced logic of expanded attributes for listItem

react/MuiCozyTheme/TextField/index.js, react/MuiCozyTheme/TextField/index.jsx, test/jestsetup.js
Add an ID to make label and helperText accessible to screen readers
See https://v4.mui.com/api/text-field/#props for more details
=> feat: Override TextField for improve accessibility

docs/components/DemoProvider.jsx, docs/components/Wrapper.jsx
We can change the lang for each component.
https://crash--.github.io/cozy-ui/react/#!/Paywall
=> docs: Add lang chooser

react/Fab/Readme.md, react/MuiCozyTheme/makeOverrides.js
Override extended variant height
Démo: https://merkur39.github.io/cozy-ui/react/#!/Fab
=> feat: Update Fab component

react/Badge/Readme.md, react/CozyDialogs/Readme.md, react/Menu/Readme.md, react/MuiCozyTheme/TextField/Readme.md, react/MuiCozyTheme/makeOverrides.js
démo : https://jf-cozy.github.io/cozy-ui/react/#!/TextField
=> TextField: Update style and doc

docs/styleguide.config.js, react/ContactsList/ContactRow.jsx, react/ContactsList/ContactsList.jsx, react/ContactsList/Readme.md, react/ContactsList/__snapshots__/ContactRow.spec.js.snap, react/ContactsList/styles.styl, react/FilePicker/FilePickerBodyItem.jsx, react/MuiCozyTheme/List/Readme.md, react/MuiCozyTheme/ListItem/Readme.md, react/MuiCozyTheme/ListItem/index.js, react/MuiCozyTheme/ListItemIcon/index.js, react/MuiCozyTheme/ListSubheader/Readme.md, react/MuiCozyTheme/ListSubheader/index.js, react/MuiCozyTheme/makeOverrides.js, react/NestedSelect/ItemRow.jsx, react/__snapshots__/examples.spec.jsx.snap, react/utils/react.js
https://jf-cozy.github.io/cozy-ui/react/#!/List
https://jf-cozy.github.io/cozy-ui/react/#!/ListItem
https://jf-cozy.github.io/cozy-ui/react/#!/ListSubheader
=> feat(List) : Update List, ListItem, ListItemText, ListSubheader, ListItemIcon

react/ActionsMenu/ActionsItems.jsx, react/ActionsMenu/ActionsMenuItem.jsx, react/ActionsMenu/ActionsMenuWrapper.jsx, react/ActionsMenu/Readme.md, react/MenuItem/index.js, react/MuiCozyTheme/ListItem/Readme.md, react/MuiCozyTheme/ListItem/index.js, react/MuiCozyTheme/makeOverrides.js, react/utils/react.js
https://jf-cozy.github.io/cozy-ui/react/#!/ActionsMenu
=> Add some features on ActionsMenu

docs/README.md, docs/guidelines.md
Guidelines qui reprend ce qu'on a décidé il y a quelques semaines sur les différences entre primary et secondary.
=> docs: Create guidelines and add new component guidelines

react/Viewer/locales/en.json, react/Viewer/locales/fr.json
for the National health insurance card
=> feat(Viewer): Add missing translation

react/Paywall/Readme.md, react/Paywall/howto.md
Improvement from a discussion with @Merkur39
=> docs: Improve documentation for the creation of paywall variants

react/Paywall/Paywall.jsx, react/Paywall/QuotaPaywall.jsx, react/Paywall/Readme.md, react/Paywall/index.jsx, react/Paywall/locales/en.json, react/Paywall/locales/fr.json, react/deprecated/QuotaAlert/Readme.md, react/deprecated/QuotaAlert/index.jsx, react/deprecated/QuotaAlert/locales/en.json, react/deprecated/QuotaAlert/locales/fr.json
[Live demo](https://cballevre.github.io/cozy-ui/react/#!/Paywall)
=> feat: Update QuotaAlert design

package.json, react/ActionsMenu/Actions/helpers.js, react/ActionsMenu/Actions/helpers.spec.js, react/__snapshots__/examples.spec.jsx.snap, test/testFromStyleguidist.js, yarn.lock
they will be filtered
Cela permet dans l'app de faire un makeAction([ isSomething && actionOne, actionTwo ]) sans avoir a manipuler le tableau des actions (ce qui peut être pénible à maintenir si l'action en question n'est ni au début ni à la fin)
=> feat(ActionsMenu): MakeActions() can now receive nullish actions

react/Filename/Readme.md, react/Filename/index.jsx
to be able to replace end ellipsis by middle one
demo : https://jf-cozy.github.io/cozy-ui/react/#!/Filename
=> feat(Filename): Add midEllipsis prop

react/ContactsList/Contacts/ContactIdentity.jsx, react/ContactsList/__snapshots__/ContactRow.spec.js.snap, react/__snapshots__/examples.spec.jsx.snap
demo : https://jf-cozy.github.io/cozy-ui/react/#!/ContactsList
=> fix(ContactsList): Avatar is no longer above list subheader

react/AppSections/Sections.jsx, react/AppSections/components/AppsSection.jsx
It is now possible to condition the click on the AppTile via the prop:
```
const componentsProps = {
appsSection: {
disableClick: app => app.installed
}
}
<Section componentsProps={componentsProps} apps={apps} handleAppClick={handleAppClick} />
```
=> feat(Section): Add prop to manage click on AppTile

react/Viewer/Readme.md, react/Viewer/Viewer.jsx, react/Viewer/ViewerContainer.jsx, react/Viewer/components/Toolbar.jsx, react/Viewer/components/ToolbarFilePath.jsx, react/Viewer/components/ViewerByFile.jsx, react/Viewer/components/ViewerControls.jsx, react/Viewer/docs/DemoProvider.jsx, react/Viewer/helpers.js, react/Viewer/proptypes.js, react/Viewer/queries.js
[Live demo](https://cballevre.github.io/cozy-ui/react/#!/Extra/Viewer)
**Remaining works:**
- ~Make a functional example into documentation (mock query to get parent path)~
**Related PRs:**
- https://github.com/cozy/cozy-libs/pull/2272
=> feat(Viewer): Display file path into the toolbar

docs/components/DemoProvider.jsx, react/Buttons/Readme.md, react/ContactPicker/Readme.md, react/ContactPicker/index.spec.jsx, react/ContactsListModal/Readme.md, react/ContactsListModal/mockClient.jsx, react/CozyDialogs/Readme.md, react/CozyTheme/index.jsx, react/Dialog/DialogEffects.spec.tsx, react/Field/Readme.md, react/Labs/CollectionField/Readme.md, react/NestedSelect/NestedSelect.md, react/Paywall/Paywall.spec.jsx, react/SquareAppIcon/SquareAppIcon.spec.js, react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap, react/__snapshots__/examples.spec.jsx.snap, react/providers/DemoProvider.jsx
cela faisait partie d'une ancienne PR qui déplaçait les providers dans un dossier. J'ai isolé ce commit dans une PR à part.
Contrairement à d'habitude on ne throw pas d'erreur si on utilise useCozyTheme. Car dans Ui on utilise le hook dans 2 contextes différents, l'un avec le provider loadé (les fichiers react, la doc) et l'autre qui ne l'a pas (les tests). J'ai essayé de rajouter le provider dans les tests mais ça n'a pas fonctionné. J'ai donc opté pour cette approche.
Petite note concernant DemoProvider : il y en a bien 2 différents, l'un pour la doc readme, l'autre pour les tests
=> feat(CozyTheme): Add error log if useCozyTheme is used outside provider

react/NestedSelect/Modal.jsx
Vu avec @joel-costa, aura un impact sur `cozy-banks` et `coachco2`
=> Feat(nestedSelectModal): The dialog must be centered

react/Viewer/components/Toolbar.jsx
Demo: https://merkur39.github.io/cozy-ui/react/#!/Extra/Viewer
Before:
After:
=> feat(Viewer): On mobile, the title benefits well from the MidEllipsis

react/Dialog/Readme.md, react/NestedSelect/BottomSheet.jsx, react/NestedSelect/ItemRow.jsx, react/NestedSelect/NestedSelect.jsx, react/NestedSelect/NestedSelect.md, react/NestedSelect/NestedSelectResponsive.jsx, react/NestedSelect/index.jsx, react/SelectBox/Readme.md
demo : https://jf-cozy.github.io/cozy-ui/react/#!/NestedSelect
=> Add NestedSelectResponsive component

react/ActionsMenu/ActionsMenuItem.jsx, react/ActionsMenu/ActionsMenuMobileHeader.jsx, react/ActionsMenu/ActionsMenuWrapper.jsx, react/ActionsMenu/Readme.md, react/ListItemIcon/index.js, react/Menu/Readme.md, react/MuiCozyTheme/makeOverrides.js
demo: 
https://jf-cozy.github.io/cozy-ui/react/#!/ActionsMenu
https://jf-cozy.github.io/cozy-ui/react/#!/Menu
https://jf-cozy.github.io/cozy-ui/react/#!/ListItem
@joel-costa can you check please?
=> Some adjustement on Menu and ActionsMenu

react/Empty/Readme.md, react/Empty/index.jsx, react/__snapshots__/examples.spec.jsx.snap
fix https://github.com/cozy/cozy-ui/issues/1465
demo: https://jf-cozy.github.io/cozy-ui/react/#!/Empty
=> feat(Empty): Accept now <Icon />, <img> and <svg> as icon prop value

react/CozyDialogs/Readme.md, react/MuiCozyTheme/makeInvertedOverrides.js, react/MuiCozyTheme/makeOverrides.js, react/MuiCozyTheme/makePalette.js, react/providers/CozyTheme/Readme.md, stylus/components/nav.styl, stylus/elements/defaults.styl, stylus/objects/sidebar.styl, stylus/settings/palette.styl
Dans l'optique d'amener le theme dark à cozy-ui. Une première PR qui nettoie et corrige certains sujets autours des thèmes.
demo: https://jf-cozy.github.io/cozy-ui/react/
=> Several fixes after check with joel

react/NestedSelect/BottomSheet.jsx, react/NestedSelect/Modal.jsx, react/NestedSelect/NestedSelect.jsx, react/NestedSelect/NestedSelect.md
demo: see https://jf-cozy.github.io/cozy-ui/react/#!/NestedSelect with `withHeader` variant
=> NestedSelect: Add option headers

react/PointerAlert/Readme.md, react/PointerAlert/index.jsx
https://zatteo.github.io/cozy-ui/react/#!/PointerAlert
=> feat(PointerAlert): Make arrow position customisable

package.json, react/Viewer/Footer/ForwardButton.jsx, react/Viewer/Footer/ForwardButton.spec.jsx, yarn.lock
And add onClick prop So that apps can pass a custom function.
=> Feat: Upgrade cozy-client to 45.0.0

react/NestedSelect/NestedSelect.jsx, react/NestedSelect/NestedSelect.md
demo: https://jf-cozy.github.io/cozy-ui/react/#!/NestedSelect
=> NestedSelect: add better child header management

react/BottomSheet/BottomSheet.jsx, react/NestedSelect/BottomSheet.jsx, react/NestedSelect/NestedSelect.jsx, react/NestedSelect/NestedSelect.md
je mets un lien de démo pour la forme https://jf-cozy.github.io/cozy-ui/react/ mais le problème n'était pas visible sur desktop, seulement sur un device mobile. La doc permet juste de vérifier que rien n'est cassé.
=> fix(BottomSheet): Did not rerender correctly after a change to children

react/ContactsList/ContactsList.jsx, react/ContactsList/Readme.md, react/ContactsList/_mockContacts.json, react/ContactsList/helpers.js, react/ContactsList/helpers.spec.js, react/ContactsList/locales/en.json, react/ContactsList/locales/fr.json, react/ContactsList/locales/withContactsListLocales.jsx, react/__snapshots__/examples.spec.jsx.snap
Démo : https://merkur39.github.io/cozy-ui/react/#!/Extra/ContactsList
=> feat(ContactsList): Show myself always at the top of the list

react/Banner/Readme.md, react/MuiCozyTheme/makePalette.js, react/MuiCozyTheme/overrides/makeLightInvertedOverrides.js, react/MuiCozyTheme/overrides/makeLightNormalOverrides.js, react/ProgressionBanner/index.jsx, react/Tile/styles.styl, stylus/settings/themes/dark-inverted.styl, stylus/settings/themes/light-inverted.styl
demo: https://jf-cozy.github.io/cozy-ui/react/#/TextField
✅ validé par @joel-costa
=> Adjust some color, initially for TextField

package.json, react/Viewer/Panel/Qualification.jsx, react/Viewer/Panel/QualificationListItemContact.jsx, react/Viewer/Panel/QualificationListItemDate.jsx, react/Viewer/Panel/QualificationListItemInformation.jsx, react/Viewer/Panel/QualificationListItemInformation.spec.jsx, react/Viewer/Panel/QualificationListItemOther.jsx, react/Viewer/helpers.js, react/Viewer/helpers.spec.js, react/Viewer/hooks/useReferencedContactName.jsx, yarn.lock
Code has been mutualized on cozy-client. Learn more here https://github.com/cozy/cozy-client/pull/1452.
=> Use paper metadata formatting from cozy-client 

react/NestedSelect/Modal.jsx
=> Adjust NestedSelect Modal

react/Layout/Layout.md, react/Nav/index.jsx, react/Nav/locales/en.json, react/Nav/locales/fr.json, react/Nav/locales/withNavLocales.jsx, react/Nav/styles.styl, react/__snapshots__/examples.spec.jsx.snap, react/index.js, stylus/components/nav.styl
https://acezard.github.io/cozy-ui/react/#!/NavLimiter
=> feat: Add `<NavLimiter />` component (VO-529)

react/__snapshots__/examples.spec.jsx.snap, stylus/components/nav.styl
The previous PR to master did not detect a linting error that has gone to master.
This PR aims to fix master by removing the lint error
=> fix: update nav.styl after broken lint passed PR

react/ListItem/ExpandedAttributes/helpers.js, react/ListItem/ExpandedAttributes/helpers.spec.js, react/ListItem/ExpandedAttributes/index.jsx, react/ListItem/Readme.md, react/Viewer/Panel/Qualification.jsx, react/Viewer/Panel/QualificationListItemDate.jsx, react/Viewer/Panel/QualificationListItemInformation.jsx, react/Viewer/Panel/QualificationListItemInformation.spec.jsx, react/Viewer/Panel/QualificationListItemOther.jsx
demo: https://jf-cozy.github.io/cozy-ui/react/#/ListItem : permet de vérifier que les label/valeurs sont les bons
=> Modify ExpandedAttributes to use cozy-client locales

react/NestedSelect/ItemRow.jsx, react/NestedSelect/NestedSelect.jsx, react/NestedSelect/NestedSelect.md, react/NestedSelect/NestedSelect.spec.jsx, react/NestedSelect/helpers.js, react/NestedSelect/helpers.spec.js, react/types.js
Cette PR permet à NestedSelect dans le cas où un élément est déjà sélectionné de pouvoir s'ouvrir directement sur lui.
Démo : https://merkur39.github.io/cozy-ui/react/#!/Extra/NestedSelect
=> feat: Open NestedSelect to a specific element

react/MuiCozyTheme/overrides/makeLightNormalOverrides.js
to override center alignment of input type button
=> feat(TextField): Force left text alignment for input

react/SelectBox/SelectBox.jsx, react/SelectBox/styles.styl, react/__snapshots__/examples.spec.jsx.snap, stylus/components/forms.styl
https://jf-cozy.github.io/cozy-ui/react/#/Field
https://jf-cozy.github.io/cozy-ui/react/#/SelectBox
see argos too to better understand changes
=> feat: Adjust style for old component Field and SelectBox

react/IconStack/index.jsx
Après échange avec @joel-costa, le style de ce composant doit de base avoir le style changé dans cette PR.
(La surcharge est toujours possible si jamais)
=> feat(IconStack): Do not add "foregroundIcon" container when icon is not present

.travis.yml
since we have to check them manually, there are only needed on PRs
=> feat: Remove jobs for argos on branch master

react/BottomSheet/BottomSheet.jsx, react/BottomSheet/README.md, react/BottomSheet/helpers.js, react/Viewer/Footer/FooterContent.jsx, react/Viewer/Readme.md, react/hooks/useSetFlagshipUi/helpers.js
See commits messages
The changes were validated with @joel-costa 
Demo: 
- BottomSheet: https://merkur39.github.io/cozy-ui/react/#!/Extra/BottomSheet
- Viewer: https://merkur39.github.io/cozy-ui/react/#!/Extra/Viewer
=> feat(Viewer): Open BottomSheet at minimum height in public view

.travis.yml, package.json, react/BottomSheet/BottomSheetHeader.jsx, react/ListItem/locales/en.json, react/ListItem/locales/fr.json, react/Viewer/Footer/Sharing.jsx, yarn.lock
=> fix(Viewer): Add displayName static property to BottomSheetHeader

docs/dev.md, react/ActionsMenu/Readme.md, rsgscreenshots.json, scripts/screenshots/fetchAllComponents.js, scripts/screenshots/screenshotComponent.js
to avoid flaky test as possible
=> Adjust screenshots scripts and argos result

react/AppSections/locales/en.json, react/AppSections/locales/fr.json
This PR adds recently added categories to appSections to display correctly in the store
=> [SCR-683] feat: Add new categories to appSections locales

react/providers/Alert/index.jsx
to be able to choose when to auto hide the alert
=> feat(AlertProvider): Add `duration` prop

docs/styleguide.config.js, react/MobileStepper/Readme.md, react/MuiCozyTheme/overrides/makeLightNormalOverrides.js
The MobileStepper was already exported but I customized it to follow figma specification ([demo](https://cballevre.github.io/cozy-ui/react/#!/Core/MobileStepper))
=> [VO-710] feat(MobileStepper): Add cozy design to MUI export

.github/actions/build_argos_desktop_cache/action.yml, .github/actions/build_argos_kss_cache/action.yml, .github/actions/build_argos_mobile_cache/action.yml, .github/actions/build_cache/action.yml, .github/actions/build_cache_read/action.yml, .github/actions/setup_argos/action.yml, .github/actions/setup_modules/action.yml, .github/workflows/deploy.yml, .travis.yml, docs/dev.md, package.json, react/AppSections/generateI18nConfig.ts, react/ContactsListModal/ContactsListModal.jsx, react/Dialog/DialogEffects.spec.tsx
On remplace Travis par GA. On améliore le script GA au passage en utilisant du cache.
=> chore: Enhanced GA CI with cache

react/CozyDialogs/FixedDialog.jsx, react/Dialog/index.jsx
=> Fix Dialog and FixedDialog

jest.config.js, package.json, yarn.lock
This lib was used in the Viewer, but is no longer in cozy-ui.
=> feat: Remove unused react-pdf dep

react/QualificationIconStack/Readme.md, react/QualificationIconStack/index.jsx
Now works both for theme and qualification
=> feat(QualificationIconStack): Add `theme` props

react/MuiCozyTheme/overrides/twake/makeLightNormalOverrides.js, react/Switch/Readme.md, react/Switch/index.jsx
demo: https://jf-cozy.github.io/cozy-ui/react/#/Switch
=> feat(Switch): Adjust style component

docs/styleguide.config.js, react/Buttons/Readme.md, react/MuiCozyTheme/overrides/makeLightNormalOverrides.js, react/ToggleButton/Readme.md, react/ToggleButton/index.js, react/ToggleButtonGroup/Readme.md, stylus/cozy-ui/build.styl, stylus/utilities/border.styl
demo: https://jf-cozy.github.io/cozy-ui/react/#/ToggleButtonGroup / https://jf-cozy.github.io/cozy-ui/react/#/ToggleButton
=> Adjust ToggleButton style

react/Avatar/Readme.md, react/Avatar/helpers.js, react/Avatar/index.jsx, react/MuiCozyTheme/overrides/makeLightNormalOverrides.js, react/MuiCozyTheme/overrides/twake/makeLightNormalOverrides.js
demo : https://jf-cozy.github.io/cozy-ui/react/#/Avatar
=> fix(Avatar): Style wasn't correct

react/Layout/Layout.jsx, react/Sidebar/index.jsx, react/UploadQueue/FileUploadProgress.jsx, react/UploadQueue/Item.jsx, react/UploadQueue/Pending.jsx, react/UploadQueue/Readme.md, react/UploadQueue/RemainingTime.jsx, react/UploadQueue/helpers.js, react/UploadQueue/index.jsx, react/UploadQueue/styles.styl, react/UploadQueue/useStatusIcon.js, stylus/objects/layouts.styl, stylus/objects/sidebar.styl
demo: https://jf-cozy.github.io/cozy-ui/react/#/Layout / https://jf-cozy.github.io/cozy-ui/react/#/UploadQueue
=> Adjust style for Layout and UploadQueue

react/SearchBar/Readme.md, react/SearchBar/index.jsx
Goal : be able to implement this bar
Test : https://zatteo.github.io/cozy-ui/react/#/Core/SearchBar
=> feat(SearchBar): Allow to disable hover

react/CozyDialogs/PermissionDialog.jsx, react/CozyDialogs/useCozyDialog.js, react/MuiCozyTheme/overrides/makeLightNormalOverrides.js
demo: https://jf-cozy.github.io/cozy-ui/react/#/CozyDialogs
=> Remove PermissionDialog inverted theme

react/Contacts/GroupsSelect/styles.styl, react/ContactsList/ContactCell.jsx, react/ContactsList/Contacts/ContactIdentity.jsx, react/ContactsList/ContactsList.jsx, react/ContactsList/helpers.js, react/ContactsList/helpers.spec.js, react/ContactsList/locales/en.json, react/ContactsList/locales/fr.json
=> Fix styles and locales

react/ActionsMenu/Actions/locales/en.json, react/ActionsMenu/Actions/locales/fr.json, react/ActionsMenu/ActionsMenuButton.jsx, react/ContactsList/ContactCell.jsx, react/ContactsList/locales/en.json, react/ContactsList/locales/fr.json
we could pass DotsIcon as prop but for now it's not necessary.
As we will "re-create" this in few components in admin-panel, I think it's a good idea to just create it once here and use it everywhere.
=> feat(ActionsMenuButton): Add component
