codemods/new-icons.js

Button can use icon identifiers and thus should be correctly upgraded
to use the new names.
https://github.com/cozy/cozy-ui/issues/1227

feat: Handle Buttons when upgrading Icons

---

react/ViewStack/ModalStack.jsx
react/ViewStack/index.js

Using the same mechanism as the ViewStack (that should be renamed SlideStack
now ?) we can have a stack of views that uses Modals.
This could be useful for example to change the style of stacking based on
whether we are on desktop or mobile.
See how the switch from a sliding stack to a modalling (?) stack : https://github.com/cozy/cozy-banks/pull/1680/commits/3eedbf390f8adb5f4ddba2ad255c9e4e392e7f27

ModalStack

---

react/I18n/index.jsx
react/Portal/index.jsx

BREAKING CHANGE
I  changed the environment variable from USE_REACT=true to USE_PREACT so that apps using React have the least amount of job to do.

feat: Invert Preact/React flag so that React becomes the default

---

docs/webpack.config.js
package.json
react/Viewer/ViewerExposer.js

I missed a reference to USE_REACT in the ViewerExposer.
I switched the condition to use USE_PREACT env variable.
Also removed the USE_REACT=true that webpack injected during
for the styleguidist since USE_REACT=true is the default now.

fix: ViewerExposer uses USE_PREACT

---

react/Portal/index.jsx

Since before we relied on injected env var to remove the preact
branch in the conditional, webpack was smart enough not to resolve the
require('preact-portal'). Since we inverted the condition and the host app does not define USE_PREACT, `webpack` cannot ignore the conditional block and
the `require` has to be resolved.
For it not to fail at build time, it must be wrapped in a try/catch.
I should have been more careful with this.
Related: https://github.com/cozy/cozy-libs/pull/874

fix: Prevent webpack from erroring if preact-portal is not found

---

docs/styleguide.config.js
react/CompositeRow/index.jsx
react/CompositeRow/styles.styl
react/NestedSelect/Modal.jsx
react/NestedSelect/NestedSelect.jsx
react/NestedSelect/NestedSelect.md
react/NestedSelect/NestedSelect.spec.jsx
react/NestedSelect/Row.jsx
react/NestedSelect/index.jsx
react/NestedSelect/styles.styl
react/index.js
scripts/screenshots.js
stylus/settings/spaces.styl
stylus/utilities/spaces.styl

Originally a component from Banks to select the category of a transaction. Categories can be nested hence the need.
At the moment, there is no transition/animation (a part from the Radio button), I think NestedSelect could use ModalStack/ViewStack in the future (depending on desktop/mobile).
Visible on https://ptbrowne.github.io/cozy-ui/react/#/NestedSelect

feat: Add NestedSelect

---

docs/styleguide.config.js
package.json
react/ContactPicker/Readme.md
react/ContactPicker/index.jsx
react/ContactPicker/index.spec.jsx
react/ContactPicker/styles.styl
react/Field/Readme.md
react/Field/index.jsx
react/SelectBox/styles.styl
react/__snapshots__/examples.spec.jsx.snap
stylus/components/forms.styl
yarn.lock

:warning: Base branch should be changed to master after https://github.com/cozy/cozy-ui/pull/1273 has been merged.
Add a `ContactPicker` components that renders like a select, but opens a `ContactsListModal`. Also add the possibility to use it with a `Field` with `type="contact"`.
See https://drazik.github.io/cozy-ui/react/#!/ContactPicker and https://drazik.github.io/cozy-ui/react/#

Add ContactPicker component

---

stylus/objects/layouts.styl

Important to have native feel when scrolling in modals for example.

fix: Set overflow scrolling to touch for elastic content

---

react/ContactsListModal/AddContactButton.jsx

The subdomain type was not retrieved correctly due to a typo. The type was always "flat" because that's the default value in `generateWebLink`.

fix(ContactsListModal): Get contacts app url correctly

---

react/helpers/tracker.jsx
react/helpers/tracker.spec.js

Call shouldEnableTracking in getTracker so we can't track if it's not enabled. 
shouldEnableTracking is memoized in order to avoir dom query

fix: Don't trackEvent if no shouldEnableTracking

---

stylus/components/forms.styl

We missed this one in https://github.com/cozy/cozy-ui/pull/983. It is
used via a `@extend $form-select` in a stylus file in cozy-settings.
Thus after updating cozy-ui, it thrown an error.

fix(forms): Use dropdown icon instead of arrow

---

react/Stack/index.jsx

The tag prop enables us to change the tag used for the rendering of the Stack. It's useful to avoid rendering too many useless intermediary elements.
When some inline elements were children of a Stack, the margins were not
applied since vertical margins have no effect on inline elements. By adding
a flex display in column direction, we ensure that no matter which type of
element is rendered, it will have margins applied.
See https://drazik.github.io/cozy-ui/react/#!/Stack

Add tag prop on Stack and force column layout

---

react/AppSections/Sections.jsx
react/AppSections/components/AppsSection.jsx
react/AppSections/components/DropdownFilter.jsx
react/MuiCozyTheme/Dialog/DialogCloseButton.jsx
react/NestedSelect/Modal.jsx
react/NestedSelect/NestedSelect.jsx

Some files did use an absolute path for cozy-ui
loading from `cozy-ui/react/…`. This breaks
if we use the components from a transpiled path
(it will escape the transpiled to go into non transpiled)
----
In early versions of B2B overrides, we needed to have absolute path for the files we wanted to overide. Files modified in this PR were using absolute path for that motive.
Today, our babel configuration does rewrite all path in order to use absolute path pointing at the transpiled version of each file. We don't need to write absolute path ourself in cozy-ui anymore (and we shouldn't).

fix: Always use transpiled cozy-ui

---

package.json
yarn.lock

In #947 we upgraded semantic-release. Ever since, it seems that when semantic-release runs on master, we get the error `The local branch master is behind the remote one, therefore a new version won't be published.` — see [this for example](https://travis-ci.org/cozy/cozy-ui/builds/623746891#L1526).
Might be related to https://github.com/semantic-release/semantic-release/compare/v15.13.28...v15.13.29 — pending further tests, we can downgrade semantic-release to the previous version.

chore: Downgrade semantic release

---

react/Text/Readme.md
react/Text/index.jsx
react/Text/styles.styl
react/__snapshots__/examples.spec.jsx.snap

Adds an ErrorMessage text component, so that when we need a red error message, we can just use this, instead of a random element with a custom classname or the `u-error` utility classname.
See https://github.com/cozy/cozy-settings/pull/269#discussion_r357227693
See https://drazik.github.io/cozy-ui/react/#!/BaseText/15

feat: Add ErrorMessage text component

---

react/Infos/Readme.md
react/Infos/index.jsx
react/Infos/styles.styl
react/__snapshots__/examples.spec.jsx.snap
react/helpers/createDepreciationLogger.js
react/helpers/createDepreciationLogger.spec.js

This PR updates the Infos component to suit new needs and fix old bugs, in particular:
- The line width should be capped
- More flexibility with the titles (adding subtitles, controlling their colors, …)
- Possibility to have a closing cross
- Compatibility with a InfosCarrousel component, which will be in a separate PR
The prop have changed, but there is a layer of compatibility, so no breaking changes. You can see the old components (and the new ones) in the [demo](https://yannick-lohse.fr/cozy-ui/react/#!/Infos), but I will remove the old examples before I merge this PR. The only changes are visual, the paddings and margins have slightly changed, but that is desired.
Just to be explicit about it: before this PR, we would pass a `title` prop, and the Infos component would render a …

Update Infos component

---

docs/styleguide.config.js
react/Labs/PasswordInput/Readme.md
react/Labs/PasswordInput/helpers.js
react/Labs/PasswordInput/helpers.spec.js
react/Labs/PasswordInput/index.jsx
react/Labs/PasswordInput/styles.styl

This is a new form of input field. But it needs to stabilized and maybe merged with current Input/Field. Labs seems to be a good place for it at the moment.
Related to https://github.com/cozy/cozy-ui/issues/1304
See https://github.com/cozy/cozy-settings/pull/269#discussion_r357225768
See https://drazik.github.io/cozy-ui/react/#!/PasswordInput

feat: Add PasswordInput to Labs components

---

react/MuiCozyTheme/TextField/Readme.md
react/MuiCozyTheme/index.jsx
react/MuiCozyTheme/theme.js

The inverted theme is made to look fine on non-white backgrounds. For
now we only have the TextField look for this theme, but with this
commit, everything should be ready to implement the theme for other MUI
components.
The discussion leading to this new theme was on https://github.com/cozy/cozy-ui/pull/1316. I decided to open another PR instead of amend the whole content of the previous one to avoid losing the context.
See https://drazik.github.io/cozy-ui/react/#!/TextField

feat(MuiCozyTheme): Add inverted theme for TextField

---

react/Spinner/Readme.md
react/__snapshots__/examples.spec.jsx.snap

Lack of parenthesis around the returned locale object resulted in the phrases
inside the polyglot instance empty.

fix: Spinner snapshot with translated msg ws wrong

---

package.json
react/ContactsListModal/AddContactButton.jsx
react/ContactsListModal/DemoProvider.jsx
react/ContactsListModal/Readme.md
react/ContactsListModal/index.jsx
react/ContactsListModal/useRealtime.js
yarn.lock

This adds realtime to the contacts list. There are two features:
* If the contacts app is not installed, then in the ContactsListModal, the « add a contact » button links to the contacts' store install page. When the app has been installed, we update the button so it links to the contact page instead of the store
* When the user clicks on « add a contact », and creates or updates a contact in the contacts app, we update the contacts list, so when he comes back to the original app, he sees the new or updated contacts.
There is a thing that bothers me, it's that by adding cozy-realtime and using it in the ContactsListModal, which is exported by the main entry point (index.js), it will require apps to install cozy-realtime. We already have the problem with cozy-client sometimes. I don't know …

Contacts list realtime

---

react/Radio/index.jsx

When used as a pure UI component and not in a form,
name, value and label are not required.

Lenient prop types for Radio

---

.travis.yml
package.json
yarn.lock

`travis-deploy-once`is deprecated, as per #756, and we shouldn't need it anymore. I don't think this will fix our publishing problem, but might as well clean it up.
I also changed the format of the `repo`flag or publishing the docs as it was failing, see https://travis-ci.org/cozy/cozy-ui/builds/627274288#L1340

fix: Remove travis-deploy-once

---

react/Modal/index.jsx

Warning to put aria-label on Modal was issued even if aria-label
was provided.
Fix #1338

fix(Modal): Do not issue warning if aria-label is provided

---

react/Text/index.jsx
react/Text/index.spec.jsx

This is needed in cozy-notes for `<MainTitle />`

feat: Allow `ref` in text and titles

---

react/Text/index.jsx

Every text components is the same and the code was not very clear about that.
By refactoring we can see that only the extra className is different.
We can also see that our component names do not match the utility classes applied.
@y-lohse @joelcosta do we have a preferred nomenclature for the text components ?

refactor: Refactor creation of text components

---

react/hooks/useEventListener.js
react/hooks/useEventListener.spec.js

To attach an event to an element, we often use a ref
to this element. The ref begins with a null value
which breaks useEventListener.
This change allows to keep the call to the hook
whatever the argument are, and only attach an
event if we have something to work with.

feat: Allows undefined values in useEventListener

---

react/AppLinker/__snapshots__/index.spec.jsx.snap
react/AppLinker/index.jsx
react/AppLinker/index.spec.jsx

We encountered the issue on Notes. If you mount an `<AppLinker>` with an empty `href`, `generateUniversalLink` throws an error but we don't catch it and we finished by having a blank screen. 
This PR fix the behavior by catching the error and logging it with an console.error(). It's better to have a link that doesn't work instead of the all app.

Fix/app linker don't crash

---

react/hooks/useEventListener.spec.js

In react-hooks-testing-library, cleanup is done automatically if the
test framework (jest in our case) exposes an `afterEach` function. For
the only case in which we need to manually unmount, we use the `unmount`
function returned by `renderHook`.

test(useEventListener): Remove cleanups

---

react/Labs/PasswordInput/helpers.js
react/Labs/PasswordInput/helpers.spec.js

Due to how RegExp.test works with RegExp with the `g` flag, the
getStrength function returned a different result when called multiple
times with the same inputs.
See https://frama.link/d5dgGURD for more infos.
This problem appeared when we extracted the regexp from the function.
Before, they were recreated on each call, which was more expensive, but
not buggy. To fix the problem without putting the regexp in the function
again, we can just remove the `g` flags that are useless here.

fix(PasswordInput): The getStrength function was not pure

---

react/Field/index.jsx

By requiring the label prop to be a string, we get a warning when we do
```jsx
<Field label={<span>Some label</span>} />
```
We can have the need to pass a node for a lot of reasons, but the one we
have now is that we need to obfuscate the label in cozy-harvest-lib. The
according PR is coming, but in brief we need to put some fake visually
hidden content in the label so password manager extensions don't target
some inputs. It can also be useful for styling purpose, for example.

feat(Field): Label prop accepts a node

---

react/Infos/index.jsx

The InfosMigration component is an anonymous function wrapped in
InfosMigration. Thus it didn't have any name and it resulted in enzyme
rendering it with the name `Unknown` in tests.

fix(Infos): Add display name to migration component

---

codemods/utils.js

When only the default import is imported, there is no imported property
in the default specifier.

fix: Should not fail when import doesnt have imported attribute

---

stylus/components/modals.styl

The modal wrapper was using `overflow-y: scroll`. The problem is that
the `scroll` value makes scrollbar appear even if it's disabled. Using
the `auto` value fixes it.
Before 
After

fix(Modal): Use overflow auto

---

react/hooks/useConfirmExit.js
react/hooks/useConfirmExit.spec.js

This hook was needed for cozy-notes. It allows to hook the onBeforeUnloadevent to warn about unsaved changes.

feat: Adds useConfirmExit React hook

---

react/I18n/index.jsx

It is unnecessary since proptypes will be checked one level below, and
it can actually lead to false positives, for example when a component
set the t PropType : since the translate()-wrapped component does not
receive the t prop from above, it triggers a warning when there is no
real problem (since t is provided to the component below by translate()

feat(I18n): Do not copy proptypes from wrapped component

---

react/utils/color.js
react/utils/color.spec.js

fix: Make getCssVariableValue return mocked value in test environment

---

react/InfosCarrousel/index.jsx
react/InfosCarrousel/index.spec.jsx

Fixes a bug with InfosCarrousel: when we navigate to the last slide, and remove a child, the internal `index` points to a slide that no longer exists. We now force the index back one slide when that happens.
This component can still "break" if it ends up with no children at all, but I don't think that the component itself should guard against that..?

fix: InfosCarrousel handles removing children

---

package.json
react/Viewer/TextViewer.jsx
react/Viewer/TextViewer.spec.jsx
react/Viewer/__snapshots__/TextViewer.spec.jsx.snap
react/Viewer/index.spec.jsx
yarn.lock

Since a `cozy-note` has a new doctype, our Viewer doesn't see it has a Mardown file. This PR fix this issue
also upgraded cozy-client to use createMockClient()

feat: Use Markdown viewer for a cozy-note

---

stylus/tools/mixins.styl

The minified CSS is quite heavy, and a large part of the wright is due to media queries. I think we can do a lot better. The first optimization is to regroup media queries from the cssModulesUtils and nativeUtils mixins. Before this commit, cozy-ui.min.css took 129kb, and after, it tooks now 123kb.

feat: Optimize the output of the CSS

---

scripts/screenshots.js

Since https://github.com/cozy/cozy-ui/pull/1361/files we now have a perSection styleguidist. 
But our current argos script get the links from the displayed page and not from the side menu. This PR fixes that. 
In order to not screenshot both the section page and the component page, I filter the section but looking for a `?` in the URL. Then, I get the text (name) of the component in order to build the right url

chore: Let's screenshots all the components 

---

react/I18n/index.jsx

On the I18n component, we kept preact compatibility by implementing both
`UNSAFE_componentWillMount` and `componentWillMount` methods. But when
using with react, this leads to deprecated methods calls warnings in
console. To avoid this, we can export a component that only implements
`UNSAFE_componentWillMount` by default, and another one that implements
`componentWillMount` when `USE_PREACT` is defined.

fix(I18n): Remove deprecated method warning

---

react/MuiCozyTheme/Menus/index.js
scripts/screenshots.js

Before this PR we were taking screenshot for a component page. But this page could contain several examples and sometimes it doesn't work well since examples can override each other. For instance, if we had a page with several modals, only the latest will appear on the screenshot.
This PR fix this behavior by creating a screenshot for every example we have in the styleguidist

test: Take individual screenshots for the examples

---

react/Modal/index.jsx

Since `dismissAction` is not always defined, we may check it's defined before calling it explicitly when clicking outside the modal.
Related to https://github.com/cozy/cozy-keys-lib/pull/78#discussion_r375665232

fix(Modal): Check if dismissAction is defined before calling it

---

react/Overlay/index.jsx

Sometimes we use Overlay to just handle click
outside of an area (Menu for instance).
I was tired of seeing this warning in drive

fix: Children is not mandatory for Overlay

---

stylus/components/button.styl

I migrated to Chromium (82.0.4078.0) again and the button's content were not correctly centered. 
It seems that the default user agent stylesheet for button in Chromium is `align-items: flex-start;`. I don't know if this behavior has been changed recently? 
exemple:

fix: Default to align items center

---

react/Badge/index.jsx

I forgot to change the badge's proptypes... we now pass a node element to the content

fix: Badge proptypes

---

react/Viewer/PdfJsViewer.jsx
react/Viewer/PdfJsViewer.spec.jsx
react/Viewer/PdfToolbarButton.jsx
react/Viewer/__snapshots__/index.spec.jsx.snap
react/Viewer/locales/en.json
react/Viewer/locales/fr.json

We display a button icon only for the PDF viewer, but we have to provide a label to make it mare accessible. It also fixes a few warnings in the console ;)

fix: Viewer Warning and accessibility

---

react/MuiCozyTheme/theme.js
stylus/settings/z-index.styl

MUI's dialog comes with a 1300 zindex. We need to fix it back to 70 as our previous modal. 
To do that, I expose a few more CSS variables

fix: Zindex dialog

---

docs/styleguide.config.js
react/Tooltip/Readme.md
react/Tooltip/index.jsx

Direct import from MUI for a first use in cozy-notes.
We only add a cozy style but the API doesn't change.

feat: Import the tooltip component from MUI

---

react/ActionMenu/index.jsx

Before, the popover was portaled. It worked well
in a normal context, but not when we only have
a portal like a Modal.
The idea, is to display the popover in the
component calling it and put it in a fixed
position (we can't have an absolute one
since Modals for instance are fixed...).
We set the right zIndex to this popover to be well
displayed.
The drawback of this method, is that the Popover
doesn't follow the scroll anymore. But we already
have this behavior in our old Menu. I think we can
deal with it, the time we find a solution.
We need to use an inline style since the MUI override 
of popperjs is setting the position absolute as inline style 
(https://github.com/mui-org/material-ui/blob/v3.x/packages/material-ui/src/Popper/Popper.js#L176) 
Styleguidist …

fix: Popover position

---

.travis.yml
react/UploadQueue/Readme.md
rsgscreenshots.json
scripts/screenshots.js

`isTesting` is use to show the popover variant during screenshots.
Previously, in both 800x600 and 300x600 screenshots, the UploadQueue
screenshots would show the mobile version, now we configure a specific
resolution for this component, through a JSON config file.

Improve UploadQueue screenshots

---

rsgscreenshots.json
scripts/screenshots.js

Argos limits us to 500 screenshots so instead of screenshotting each
example, we screenshot each component page
One additional challenge introduced by screenshotting at component level, is that for some examples, we *need* to screenshot at example levels, for example with modals or action menus. To support this usecase, a configuration attribute `perExampleScreenshot` is introduced. When this is configured, screenshot are taken at example level.

Draft feat: Take less screenshots

---

react/ThresholdBar/index.jsx
react/UploadQueue/Readme.md
react/UploadQueue/index.jsx
react/UploadQueue/locales/en.json
react/UploadQueue/locales/fr.json
react/UploadQueue/styles.styl
stylus/settings/typography.styl
stylus/utilities/typography.styl

Add remaining time next to progress bars.
- Only shown on desktop
- This component is only used in Drive but it should possible to use in Photo
- Speed is not shown, I chose this not to clutter the interface too much
https://ptbrowne.github.io/cozy-ui/react/#/UploadQueue
cc @joel-costa

Add remaining time to individual uploads

---

docs/styleguide.config.js
react/ActionMenu/Readme.md
react/DropdownButton/Readme.md
react/DropdownButton/index.jsx
react/DropdownButton/styles.styl
react/__snapshots__/examples.spec.jsx.snap

This component is used with the `ActionMenu` component, but not only — it will also be used with drive's Breadcrumb component, and more.
- [DropdownButton demo](https://yannick-lohse.fr/cozy-ui/react/#!/DropdownButton)
- [Updated ActionLMenu example](https://yannick-lohse.fr/cozy-ui/react/#!/ActionMenu)

feat: Added DropdownButton component

---

react/ActionMenu/Readme.md
react/ActionMenu/index.jsx
react/__snapshots__/examples.spec.jsx.snap

`ActionMenu` on desktop relies on `Popper` from MUI, itself being a small wrapper around `Popper.js`. By default, Popper will portal-render itself at the root of the DOM. This caused ActionMenu to malfunction when used within a modal (see https://github.com/cozy/cozy-ui/commit/92cccc24fb732371c4c38bb8e687771a164f7468).
The previous fix was to disable portaling. This solved the z-index problem but caused overflowing problems, so `position: fixed` was used as well. The problem is that as soon as `disablePortal` is activated, Popper won't honor the `placement` attribute anymore. So that prop has been broken since 92cccc24fb732371c4c38bb8e687771a164f7468.
Since *not* using Portal isn't an option, we need to control where the Portal is rendered. We can dothis using the [`container` …

fix: ActionMenu placements

---

package.json
react/UploadQueue/Readme.md
react/UploadQueue/index.jsx
yarn.lock

Splitting the filename had a bug when there was no extension: it would return { filename: ".", extension: "" } if the filename had no extension, resulting in upload queue rows with only "." if the item was a directory or an extension less file.

Fix upload queue item for directories

---

react/ActionMenu/Readme.md
react/ActionMenu/index.jsx
react/Modal/index.jsx
react/PopperContainerContext.js
react/__snapshots__/examples.spec.jsx.snap

In a previous PR, containerElRef was introduced so that ActionMenus
could be rendered correctly in modals. The problem was that we don't
know a priori if a component is going to be rendered in a Modal, which
makes it impossible to pass the modal ref to the action menu.
Here a context automatically provides the ref through a PopperContainerContext.
containerElRef is kept for backward compatibility.
~~One caveat here: the ActionMenu must be rendered after the ref object has
been filled with React which means that the ActionMenu content must *not* be
rendered in the same render round as the Modal. This is why in the example
I had to separate the Modal content from the modal itself. Otherwise,
when opening the actionMenu, the Modal was re-rendered since the modalOpened
state and actionMenu …

fix: Remove need for containerElRef

---

react/ActionMenu/Readme.md
react/ActionMenu/index.jsx
react/__snapshots__/examples.spec.jsx.snap
stylus/components/action-menu.styl

This PR adds support for having more complex content than a string in ActionMenuItems. Technically it was already possible to add any component as a child of `ActionMenuItem`, but the alignment was out of place.
The new feature is illustrated with a label + description.
See the first example as a preview: https://yannick-lohse.fr/cozy-ui/react/#!/ActionMenu

feat: Support more complex action menu items

---

react/UploadQueue/Readme.md
react/UploadQueue/index.jsx
react/UploadQueue/styles.styl

- No ellipsis was showing in case of long filename
- Content was centered, this would result in misalignment when progress
width was shorter than filename
- Used Media to reduce the amount of code
- Texte de statut aligné à droite
On a une différence de padding sur le côté droit, du au fait que c est maintenant la ligne qui porte le padding, ca fait que le padding est uniforme à gauche et à droite. A mon avis, c'est mieux qu'avant, @joel-costa tu peux confirmer ? cf [avant](https://argos-ci-production.s3.eu-west-1.amazonaws.com/aa8da7fd28c86fc1c6baadf4f73bbeeb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVTMHH3OS5ZZGS3AJ%2F20200423%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20200423T100814Z&X-Amz-Expires=7200&X-Amz-Signature=e4581a09986917793b036e09b53da831a395857b88d30bb579b007f9 …

fix: Upload queue bugs

---

react/UploadQueue/styles.styl

I could not see this bug in the styleguidist since the "pending" in French has no space.

fix: No wrap status for upload queue

---

react/Stepper/testing.jsx

Add testing utility near the component, for use downstream in apps.
It was pretty difficult to test if a step was in warning (with react testing library). I propose in those cases to have testing utilities here in cozy-ui for easier usage in Apps. 
See https://github.com/cozy/cozy-passwords/pull/26 for context.

feat: Add testing utility for Stepper

---

react/ActionMenu/Readme.md
react/ActionMenu/__snapshots__/index.spec.jsx.snap
react/ActionMenu/index.jsx
react/ActionMenu/index.spec.jsx
react/Popper/testing.js
react/__snapshots__/examples.spec.jsx.snap

In Drive we have an ActionMenu but not all items are visible at all time — if one of the items should be hidden, it returns null instead, as is common in React. This was breaking `ActionMenu` because it was checking `null.type`.
I also added an example for the `right` prop of ActionMenuItem so that we have visual regression tests for it.

Support ActionMenu having null children

---

react/NestedSelect/NestedSelect.jsx
react/NestedSelect/NestedSelect.md

Add the ability to position the radio buttons of the nested select to the left instead of the right.
Added a `radioPosition` prop that defaults to `right`.
Edit: This option is screenshotted on mobile on Argos.
cc @joel-costa @fffflo

feat: Ability to have the radio buttons to the left

---

react/ActionMenu/index.jsx
react/ActionMenu/index.spec.jsx

At the moment, the ActionMenu stays open when an item is clicked. This is not the default behavior of most of our menus, where the menu is be closed as soon as an action is picked.
Eventually this should be the default behavior, but I couldn't find a way to make it the default without introducing a breaking change. So this PR adds an `autoclose` prop that can be set for new menus while the old ones are migrated, and after a period we can remove this prop entirely or switch its default value to `true`.
Menus that need updating, off the top of my head: in cozy-sharing, cozy-scanner, cozy-notes.

feat: Enable ActionMenu to automatically close itself

---

react/ActionMenu/index.jsx
stylus/components/action-menu.styl

- Support for className
- ActionMenu defaults its color to charcoalGrey, this is helpful if the actionMenu
is contained in a container setting a default color

ActionMenu improvements

---

react/ActionMenu/Readme.md
react/ActionMenu/index.jsx
react/ActionMenu/styles.styl
react/__snapshots__/examples.spec.jsx.snap
react/index.js
stylus/components/action-menu.styl

To be able to put a Radio inside an ActionMenuItem, we need a
specific style.
https://ptbrowne.github.io/cozy-ui/react/#!/ActionMenu

feat: Add ActionMenuRadio

---

docs/ThemeChooser.jsx
docs/components/SectionsRenderer.jsx
docs/styleguide.config.js
react/Breadcrumbs/Readme.md
react/Breadcrumbs/index.jsx
react/Breadcrumbs/styles.styl
react/CozyTheme/Readme.md
react/CozyTheme/index.jsx
react/CozyTheme/styles.styl
react/Figure/Figure.jsx
react/Figure/Figure.styl
react/Figure/FigureBlock.md
react/Figure/FigureBlock.styl
react/Figure/__snapshots__/Figure.spec.jsx.snap
stylus/components/button.styl
stylus/components/forms.styl
stylus/settings/palette.styl

- Use CSS variables for text color
- Breadcrumbs and Figure use those variables
- ThemeChooser component for easy switch between themes in styleguide
(per component for now, would love to have it globally in the sidebar)
Preview: https://ptbrowne.github.io/cozy-ui/react/#!/Breadcrumbs
Edit: added the preview

Improve theme support for Breadcrumb / Figure

---

react/ActionMenu/index.jsx
react/BottomDrawer/styles.styl
stylus/components/action-menu.styl

ActionMenu inside a BottomDrawer in latest designs is rounder and has no margin from the
screen.

feat: Rounder style for action menu in bottom drawer

---

docs/styleguide.config.js

Sort components alphabetically inside sections.
For the future, I think we should start to think of how to reorganize our
components. I think our sections have grown a bit since the beginning
and that some sections like "Basics" have components that could
be moved in other sections like "Content".
I think this can be done in a separate issue, what do you think ?

refactor: Reorganize alphabetically

---

codemods/use-breakpoints-hook/index.js
codemods/use-i18n-hook/index.js

A codemod must return the source, not the root object

fix: Use toSource() on codemod

---

package.json
react/Modal/Readme.md
yarn.lock

We use focus trap in the cozy store. In the process of trying to
understand a crash, I developed an example and thought it could
be useful to keep it here. It could serve as a base to further
integrate focus trap so that it is automatically used by the
Modal buttons or content. What do you think ?
Info: The crash in question was in cozy-store where focus-trap
could not find any focusable element since the modal was loading
and a spinner was displayed. I have not found why it would not
crash bfore the update to cozy-ui 34 but I have seen that the
close button was focused by focus-trap-react before the update
to cozy-ui 34. After the update the close button was not
focused. Maybe the change to portal the content by default
was the triggerer for the error.
Edit: add link to example …

Example with focus trap

---

react/Figure/Figure.styl
react/Labs/PasswordInput/styles.styl
react/Text/Readme.md
react/__snapshots__/examples.spec.jsx.snap
stylus/components/nav.styl
stylus/settings/palette.styl
stylus/utilities/text.styl
stylus/utilities/typography.styl

- feat: Status colors go through semantic indirection
The semantic indirection is helpful when building a theme since we
can override the semantic variable, whereas it makes not much
sense to override a color variable
- Use semantic variable for text classes
- Use primary color for nav (to show that a page is active)

CSS variables improvements

---

stylus/components/button.styl
stylus/settings/palette.styl

Use CSS custom properties to customize button's border radius
and text transform.

feat: Make button textTransform and borderRadius overridable

---

react/CozyTheme/styles.styl
stylus/components/tabs.styl
stylus/settings/palette.styl

By default, inverted color is the primary color but sometimes the
primary color cannot be used as a background. In those cases, we
want to be able to override the inverted color.

Ability to override inverted color

---

react/AppIcon/Preloader.js
react/AppLinker/index.jsx
react/AppSections/components/SmallAppItem.jsx
react/HistoryRow/index.jsx
react/NestedSelect/Row.jsx
react/PushClientButton/index.jsx
react/UploadQueue/index.jsx
react/Viewer/ShortcutViewer.jsx

An import was still using cozy-ui/react directly. We must use relative paths when importing other componetns. Those relative paths are expanded into `cozy-ui/transpiled/react` paths at transpile time.

Use relative paths everywhere

---

CODEOWNERS
react/Wizard/Readme.md
react/Wizard/index.jsx

Display errors in red in italic. Can be used with a custom Component with the `tag` prop, which can be used for example to use ReactMarkdown.

feat: Add missing WizardErrors that was lost during migration

---

stylus/components/nav.styl

If the nav link is active, we do not want a change of color
on hover.
Took this opportunity to remove deprecated `.active` class
that was not used in the Nav implementation.

No change of color of nav text on hover if it is active

---

stylus/components/nav.styl

A last :hover would make the text the normal color even
if the link was active.
Can be viewed here : https://ptbrowne.github.io/cozy-ui/react/#!/Sidebar
`--navTextActiveColor: red` can be set on body to check this behavior.
When the link is active, it should be red even with the mobile mode activated in the devtools, and with the pointer hovering the link.

Fix nav color text on mobile if hovered

---

package.json
react/LoadMore/index.jsx
yarn.lock

Since LoadMore use Intersection Observer (and IO doesn't work on Safari), it seems to make sense that LoadMore requires the polyfill itself.

fix: Import Intersection-observer polyfill

---

.travis.yml

chore: Update travis node version

---

package.json
react/ActionMenu/Readme.md
react/ActionMenu/index.jsx
react/Modal/index.jsx
react/PopperContainerContext.js
react/__snapshots__/examples.spec.jsx.snap
yarn.lock

Our ActionMenu on desktop uses Popper to position itself. This Popper instance is exported by material-ui (v3) and is the v1 of Popper. We've had a few problems with our more advanced use cases, eg. menus inside modals. We fought it hard, even introducing a PopperContext to help with positioning. 
But even after all that: 
And the Popper exported by MUI is restricted, we can't use fixed positioning with it for example. So I tried to use Popper v2 instead, and:
Everything seems to Just Work™, without even using fixed positions, without messing with containerElements etc.
So yeah, I suggest we use the newer version of Popper for the menu as it seems simply better in every regard, and as far as I can tell there is no breaking change.

fix: Use newer version of popper in action menu

---

package.json
react/IntentIframe/IntentIframe.jsx
react/IntentModal/test/__snapshots__/intentModal.spec.js.snap
yarn.lock

The IntentIframe now uses cozy-interapp and does not need
cozy-client-js to work.

feat: Use cozy-interapp to provide intents

---

docs/styleguide.config.js
react/MuiCozyTheme/Divider/Readme.md
react/MuiCozyTheme/Divider/index.jsx

The Divider was not present in the doc.
I've reworkd the code as I realized I had not wrapped the example in a MuiCozyTheme. When wrapping the Divider in a MuiCozyTheme, it has a special behavior that works well for Dialogs (where the padding of the modal must be cancelled), but not so well in "normal situations". To deal with the problem, I created a CardDivider that cancels the bad behavior of the normal Divider.
I've created the issue in #1534. The idea behind CardDivider is that when we solve the problem with the normal Divider, it will be simple to convert CardDivider to Divider and Divider to DialogDivider.

docs: Add doc on Divider

---

react/ListItemText/index.jsx
react/MuiCozyTheme/List/Readme.md
stylus/utilities/text.styl

It is useful to be able to add u-error on list item components.
In the usecase section, I tweaked the example to have a usecase
that is nearer to the real usecase of the navigation menu.

feat: Ability to add classNames to primaryText and secondaryText

---

react/ListItemText/index.jsx

PropTypes.string is often too restrictive. Here for example, we
wanted to show an icon next to the text, hence we used a fragment
containing <Icon /> and the text string as secondaryText prop.

feat: {primary,secondary}Text can be React nodes

---

stylus/cozy-ui/build.styl
stylus/settings/palette.json
stylus/settings/palette.styl
stylus/utilities/bgcolor.styl
stylus/utilities/text.styl

Using semantic utility classes that use semantic
CSS variables enables us to build themes.

feat: Add utility classes for semantic backgrounds

---

react/Badge/index.jsx
react/__snapshots__/examples.spec.jsx.snap

When using `InfosBadge` or `Ghostbadge`, we got a warning `Material-UI: the key `badge` provided to the classes property is not implemented in Component.`. This is because even though `badge` is a valid class name for [MUI Badge](https://v3.material-ui.com/api/badge/), it wasn't declared in the cozy-ui export.
I also fixed a problem where custom classes where not spread in the right place.

fix: Prevent badge warnings from MUI

---

codemods/transform-dialog-imports.js
package.json
yarn.lock

Since Dialog components are now directly exported from react/Dialog/index.js, we use `transformImports` from `@cozy/codemods` to automatically
migrate Dialog imports through jscodeshift (see https://github.com/cozy/cozy-ui/pull/1551#pullrequestreview-487460641).
Related @cozy/codemods PR : https://github.com/cozy/cozy-libs/pull/1095
```patch
- import DialogContentText from 'cozy-ui/transpiled/react/MuiCozyTheme/Dialog/DialogContentText'
+ import DialogContentText from 'cozy-ui/transpiled/react/Dialog'
```

feat: Add jscodeshift transform to migrate dialog imports

---

react/Infos/styles.styl

Typo making the background "white" on Infos--danger

fix: Use correct variable for error background

---

stylus/settings/shadows.styl

The elevation utility should have a small translucent border.

feat: Add border for elevation utility

---

react/MuiCozyTheme/ListItemIcon/index.js
react/NavigationList/Readme.md

Our ListItemIcon must have a fixed width of 32px with horizontal padding
of 16px.
- Fixes https://github.com/cozy/cozy-ui/issues/1541
- See result at https://ptbrowne.github.io/cozy-ui/react/#!/NavigationList

fix: ListItemIcon size is fixed

---

codemods/transform-typography.js
docs/styleguide.config.js
react/MuiCozyTheme/theme.js
react/Text/Readme.md
react/Typography/Readme.md
react/Typography/index.jsx

To better follow the design specs, and to remove discrepancies
between cozy-ui and material-ui, I added the theme for our
text specs into the MUI theme.
🔧 We can now use Typography components in our apps, instead of the Text components.
An example in the styleguide is there to show how to migrate
and a codemod is also there to facilitate the transition.
https://ptbrowne.github.io/cozy-ui/react/#!/Typography
⚠️ Styles for `Typography variant=h1,h2` are not similar to `u-title-h1`, `u-title-h2` since u-title-h1 is now `Typography variant=h3`. A second pass to take care of utility classes would be necessary, maybe adding first u-typo-h1 and others, and then removing u-title classes ?

Typography components

---

stylus/settings/fontstack.styl
stylus/settings/palette.styl
stylus/settings/z-index.styl

Custom stylesheet lost the ability to override button colors after
the introduction of CSS properties relying on others (for example
regularButtonPrimaryColor relying on primaryColor).
For the button color to be correctly overriden, the stack must be
able to override the --primaryColor, so that it is correctly
picked up when using regularButtonPrimaryColor.
html targets the same element as :root but its specificity is lower.
This allows us to use html to define our CSS custom properties inside
cozy-ui, and use :root in the custom CSS injected by the stack for
context that have a theme. This way, the :root selector can override
CSS custom properties, without relying on CSS order.

fix: Allow custom stylesheet to override global custom properties

---

.travis.yml

Fast finish is used during matrix jobs and we do not use the matrix
feature from Travis here.

chore: Remove unused fast_finish from travis

---

react/SelectBox/SelectBox.jsx

Used in contact to pass data-testid on Icon
```
```

Add possibility to pass props to SelectBox options icon

---

react/ContactPicker/index.jsx
react/Labs/CollectionField/Readme.md
react/Labs/CollectionField/index.jsx
react/__snapshots__/examples.spec.jsx.snap

Following @joel-costa's remarks during validation phase, the
CollectionField now supports the use of an imperative callback called when
a component is added. This is useful for example for the contact picker that should be
shown directly just after clicking "Add".
See the CollectionField/Readme.md for more information (see the onAddField prop).
[new behavior](https://ptbrowne.github.io/cozy-ui/react/#!/CollectionField) to compare with [current behavior](https://docs.cozy.io/cozy-ui/react/#!/CollectionField)

Better behavior for CollectionField

---

react/MuiTabs.js
react/MuiTabs.jsx
react/Tabs/Readme.md

We want tabs to be in fullWidth variant on mobile. To achieve
this we must export a component wrapping the material-ui tabs.

feat: Tabs switch to fullWidth variant on small viewports

---

react/SelectBox/ControlDefault.jsx
react/SelectBox/SelectBox.jsx
react/SelectBox/index.jsx

We have now a default react-select control that works on mobile in the case we want to use an onClick function on the control, specially to manage the isMenuOpen prop.
Fix https://github.com/cozy/cozy-ui/issues/1593
```
```

fix: Default Control works now on mobile

---

stylus/settings/palette.json
stylus/settings/palette.styl

I needed a semantic color to indicate a "danger zone" like destroying a document. This is currently the same as an error since its value is `pomegranate` but now its semantically correct ;)

feat: Add u-danger color

---

docs/README.md

Developing a component from the styleguidist was not mentioned in the README.

docs: Add mention of developing inside the styleguidist

---

react/MuiCozyTheme/theme.js

We had a small discrepancy between our tabs font-size and the one that
we should use (the fontsize from subtitle1).
https://ptbrowne.github.io/cozy-ui/react/#!/Tab

Change tabs font size to match subtitle1

---

codemods/transform-list-item-attributes.js

primaryText and secondaryText were deprecated, a codemod is here
to help with the migration

feat: Add codemod to migrate ListItemText props

---

react/MuiCozyTheme/theme.js

- useful to manage ellipsis
- 90% is not arbitrary, it's @joel-costa 's specs

feat: Set dialogTitle width to 90%

---

docs/README.md

Added an explicit note that can help understand why updating snapshots of unit tests can be problematic with IC.

docs: Add comment about transpile before update snapshots

---

react/CozyDialogs/ConfirmDialog.jsx
react/CozyDialogs/Dialog.jsx
react/CozyDialogs/FixedActionsDialog.jsx
react/CozyDialogs/FixedDialog.jsx
react/CozyDialogs/IllustrationDialog.jsx
react/CozyDialogs/dialogPropTypes.js

This way we have no discrepancy between MUI Dialog and our Dialog, we
have less props to learn. And it follows the principle of least astonishment.

feat: Use open prop like MUI Dialog

---

react/SelectBox/Readme.md
react/__snapshots__/examples.spec.jsx.snap
rsgscreenshots.json

In a few cases, a SelectBox can be displayed in a Dialog. By default, in that case, the content of the SelectBox will be inside the ModalContent. Using `fixed` resolves this issue. I'm not setting it by default since the Select is now fixed, it doesn't follow the scroll 
see: https://crash--.github.io/cozy-ui/react/#/Forms?id=selectbox

docs: Add Example for ActionMenu in a Dialog

---

react/Viewer/withFileUrl.jsx

We need to reset the timeout when reseting. Without, the call in the didUpdate is not done since timeout is setted.
It's a quick fix, I'm working on a refacto on this HOC to convert it to hooks. But I need to rewrite the tests, so let's go for this fix first, and later the refacto 👍

fix: Clear Timeout when reseting

---

stylus/components/selectionbar.styl

In https://github.com/cozy/cozy-ui/commit/9c543922553fe8d193ba6c38e3f0521f26c88e9e#r43258678 we wondered why the selector was on role=application. It was to be more precise than the style on the button and on the hover button of Cozy-UI (we have by default blue hover on a subtle button). Let's use a slightly more precise selector by manually specifying the hover to make sure we use the right color.
With this fix, the hover on the SelectionBar item is now white and not blue

fix: Use a precise selector for SelectionBar button hover

---

react/ActionMenu/Readme.md
react/ActionMenu/index.jsx

Previously it was impossible to close the Menu by clicking again on the item that opened it. Now, during onClose we can see if we are not clicking on the anchorRef to let it manage all by itself what to do.
Same implementation than MUI:
https://v3.material-ui.com/demos/menus/#menus
https://crash--.github.io/cozy-ui/react/#!/ActionMenu/1
(I can't have createRef working on functional component, have to convert it in class https://github.com/styleguidist/react-styleguidist/issues/1150)

feat: Can close an ActionMenu by clicking again on the anchorElRef

---

react/Avatar/Readme.md
react/Avatar/index.jsx
react/__snapshots__/examples.spec.jsx.snap

Avatar can accept `<Icon>` directly from icon props. Like that, we can import the IconComponent directly without importing the Sprite. 
with: https://github.com/cozy/cozy-libs/pull/1149

feat: Avatar accepts IconComponent

---

react/Avatar/styles.styl
stylus/components/circle.styl

Fix back css classes and extendables on Circle and Avatars. This was an unwanted BC

fix: Circle and Avatars comes with stylus again

---

package.json
release.config.js
yarn.lock

The npm plugin had been forgotten, leading to non publication of the
release on npm.
Added the semantic-release/changelog plugin which could write the release
notes to the CHANGELOG.md file. I tried to run locally (dry run) but could
not see any change, I think it may be because of the dry run.

Add npm publication with semantic-release

---

react/ListItemText/Readme.md
react/MuiCozyTheme/List/Readme.md
react/MuiCozyTheme/theme.js
react/Radio/Readme.md
react/Radio/index.jsx
react/Typography/Readme.md
react/__snapshots__/examples.spec.jsx.snap
stylus/components/forms.styl

- Alignment of checkbox and radio is easier to control
- Add secondary text color
BREAKING CHANGE: A bottom margin has been removed from Radio/Checkbox, it could have visual impacts but generally the alignment should be better now. See Argos screenshots to see the removed bottom margin.
If an app needs the margin-bottom behavior, it is easy to re-add u-mb-half to the Radio or Checkbox.
https://ptbrowne.github.io/cozy-ui/react/#!/Radio

Improvements

---

react/MuiCozyTheme/theme.js

The theme had scienceBlue instead of using the CSS variable.

feat: Use primaryColorDark CSS variable in MUI theme

---

react/MuiCozyTheme/theme.js
stylus/settings/palette.styl

- We do not use the secondary color much but it can be useful for
custom themes.
- Tweak MUI button styles so that they follow our chart. We now
can use MUIButtons directly
I checked with @joel-costa and we're aligned.
Styleguide : https://ptbrowne.github.io/cozy-ui/react/#!/Buttons

feat: Better support for secondary color

---

react/CozyDialogs/Readme.md
react/CozyDialogs/useCozyDialog.js

- A warning was displayed if open={false} and opened was not passed since
we would take the value of opened when open was falsy
- Fix key warning in example

Dialog improvements

---

react/Dialog/index.jsx

This is a fix to block scroll on Dialog with screen < 1024. This is based on the work done in #1597 to block scroll on Overlay on iOS. 
The comment in the Dialog should be enough. I took the one done by @ptbrowne on its previous attempt (https://github.com/cozy/cozy-ui/pull/1666) and the issue we fixed with ActionMenu / Overlay (#1597)  
https://crash--.github.io/cozy-ui/react/#!/CozyDialogs

feat: BlockScroll on mobile screen

---

stylus/settings/palette.styl

The theme was relying on missing css custom prop
secondaryContrastTextColor

fix: Missing variable in palette would cause blank page

---

react/Viewer/withFileUrl.jsx

Fix lot of `undefined` in the stack's prod log file. For the user it doesn't change anything except if they use a browser not supporting the download attribute hack (https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/FileCollection.js#L481-L488)

fix: Pass the filename to download()

---

react/CozyDialogs/ConfirmDialog.jsx
react/CozyDialogs/Dialog.jsx
react/CozyDialogs/FixedActionsDialog.jsx
react/CozyDialogs/FixedDialog.jsx
react/CozyDialogs/IllustrationDialog.jsx
react/CozyDialogs/useCozyDialog.js
react/Dialog/Readme.md
react/MuiCozyTheme/theme.js

DialogActions should respect the safe-area except for ConfirmDialog
The Dialogs are in fullscreen in mobile so it is not embarrassing to add the safe-area in all cases.
ConfirmDialog is not supposed to display a lot of content. Moreover ConfirmDialog is not fullscreen like other Dialogs, so  no need to add safe-area paddingBottom.
**Before**
**After**

fix: Safe-Area  for FixedDialog

---

react/Viewer/InformationPanel.jsx
react/Viewer/Readme.md
react/Viewer/index.jsx
react/Viewer/styles.styl

Ajout d'exemples d'utilisation des blocs dans le panneau d'info du Viewer. Pour l'instant pas de souhait d'avoir un composant haut niveau dans UI, l'approche étant que ce soit l'app qui puisse ajouter les blocs dans le panneau d'info comme elle le souhaite.
Petit changement également pour screenshoter le viewer et non la doc.

Viewer : Add blocks in info panel

---

stylus/components/accordion.styl
stylus/components/action-menu.styl
stylus/components/button.styl
stylus/components/chip.styl
stylus/components/forms.styl
stylus/components/modals.styl
stylus/components/popover.styl
stylus/components/table.styl
stylus/components/tabs.styl
stylus/components/wizard.styl
stylus/cozy-ui/build.styl
stylus/objects/sidebar.styl

Not to forget, I did a quick search and replace to have a more semantic
variable name instead of var(--silver) everywhere.
I used `var(--dividerColor)`. It follows the same logic as material UI that uses theme.palette.divider for the border color of the Paper variant='outlined'.
Wondering what @joel-costa thinks about that.

Border color as a variable

---

react/CozyDialogs/dialogPropTypes.js

Sometimes we do not want to have the onClose proptype.
In those cases, the DialogCloseButton is not displayed (the check
was already in place).

Remove required onClose required propType on CozyDialogs

---

react/Viewer/NoNetworkViewer.jsx
react/Viewer/NoViewer/DownloadButton.jsx
react/Viewer/PdfJsViewer.jsx
react/Viewer/ShortcutViewer.jsx
react/Viewer/ShortcutViewer.spec.jsx
react/Viewer/Toolbar.jsx
react/Viewer/__snapshots__/index.spec.jsx.snap
react/Viewer/index.jsx
react/Viewer/withViewerLocales.jsx

Ceci est nécessaire lors de l'utilisation du Panel afin d'utiliser le provider de langue de l'app et non celui de UI

fix: Viewer now uses UI locales only for specific component

---

react/helpers/appDataset.js
react/helpers/appDataset.spec.js
react/helpers/tracker.jsx
react/helpers/tracker.spec.js

The stack introduced the data-cozy attribute a while ago. All the
future data coming from the stack to the cozy should come from
there.
Here the tracking setup code is refactored to use helpers that can
read either from data-cozy attribute or data-cozy-<attrName> attribute.

feat: Read tracking setting from data-cozy or data-cozy-tracking

---

react/Viewer/Toolbar.jsx
react/Viewer/ViewerControls.jsx
react/Viewer/ViewerWrapper.jsx
react/Viewer/controls.styl
react/Viewer/index.jsx
react/Viewer/styles.styl

- Il n'est plus possible de choisir si le Viewer est foncé ou clair.
- Le viewer sur desktop est maintenant toujours gris foncé
- Le viewer sur mobile est maintenant toujours blanc
Le bouton "back" n'apparaît pas dans les screenshot d'argos mais est bien présent suite au build... je valide donc la CI

Viewer: global style for mobile

---

react/Viewer/docs/DemoProvider.jsx

L’exemple dans la doc du Viewer avec une image et un fichier texte ne fonctionne pas (car `client` est `null`)

fix: Viewer doc example for ImageLoader

---

react/CozyDialogs/DialogBackButton.jsx
react/CozyDialogs/Readme.md
react/MuiCozyTheme/theme.js

fix bug introduced with https://github.com/cozy/cozy-ui/commit/4bc03f4106ded21b425b92da09e1c30ab23f960d because of display flex

fix: CozyDialog Title should have ellipsis with long text

---

react/Viewer/Readme.md
react/Viewer/Toolbar.jsx
react/Viewer/ViewerControls.jsx
react/Viewer/index.jsx

Ce qui fait qu'on a bien maintenant les changements au redimensionnement de la fenêtre, sans avoir besoin d'actualiser la page.
Pour info on voit que Argos se base également sur les breakpoints et non le type de device

fix: Viewer isMobile based on breakpoint, not device

---

stylus/components/wizard.styl

Wizard uses color names variables instead of semantic variables.
This makes theming impossible.

feat: Use semantic colors for wizard

---

.travis.yml
release.config.js

- revert de https://github.com/cozy/cozy-ui/commit/ab2622f1f99fa478b0487e5566ed770946da8f51 qui pose problème dans travis
```
error: The destination you provided is not a full refname (i.e.,\nstarting with "refs/"). We tried to guess what you meant by:\n\n- Looking for a ref that matches \'undefined\' on the remote side.\n- Checking if the <src> being pushed (\'HEAD\')\n  is a ref in "refs/{heads,tags}/". If so we add a corresponding\n  refs/{heads,tags}/ prefix on the remote side.\n\nNeither worked, so we gave up. You must fully qualify the ref.\nhint: The <src> part of the refspec is a commit object.\nhint: Did you mean to create a new branch by pushing to\nhint: \'HEAD:refs/heads/undefined\'?\nerror: failed to push some refs to \'https://github.com/cozy/cozy-ui.git\'
```
suite à la …

fix: Revert travis and deploy modification

---

docs/README.md

The licence indicated in `docs/README.md` is not the same as the one in `LICENCE`.
That part was probably forgotten in [this commit](https://github.com/mkrtchian/cozy-ui/commit/e3bb473b974f7cf134f2ccc976a5a979386b1faf).
---
```
```

docs: udpate licence in the README.md

---

react/AppTile/Readme.md
react/AppTile/index.jsx

The showStatus prop of AppTile can now be an array listing
the statuses that should be shown. This way an app can
choose to show only "maintenance" and "update" statuses and
not show the "installed" status.

feat: Ability to choose which status will be shown

---

react/Viewer/ImageViewer.jsx
react/Viewer/PdfJsViewer.jsx
react/Viewer/TextViewer.jsx
react/Viewer/TextViewer.spec.jsx
react/Viewer/ViewerSpinner.jsx
react/Viewer/withFileUrl.jsx

Sur mobile, le Viewer est sur fond blanc (contrairement à un fond gris sur Desktop). Les spinners doivent donc être de la couleur primaire, et non blanc, pour être visibles.

fix: Viewer spinners should not be white in mobile

---

.travis.yml

Travis met plus de 10 minutes et crash avant la fin avec le message suivant : 
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

chore: fix for travis with build longer than 10 minutes

---

stylus/cozy-ui/build.styl
stylus/utilities/filter.styl

Le cas d'usage est ici https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/src/components/KonnectorBlock.jsx#L27 afin de remplacer le withStyle. (on a déjà la classe utilitaire opacity)
Ce remplacement ne peut être fait que comme ça ou via un stylus. Comme on évite de faire du stylus et que j'ai pensé que cette classe utilitaire pourrait resservir dans d'autres contextes, j'ai choisi cette façon de faire.
La nécessité de remplacer le withStyle est due au fait qu'on a un conflit de classe css `jss` générée dans Banks lors de l'utilisation du Viewer (de cozy-ui) via un intent Drive. Après quelques recherches je pense que c'est dû à un différence de version de MUI utilisé (Banks et Harvest sont en v3, Drive en v4), et ayant une feature qui commence à dater qu'on aimerait …

feat: Add filter grayscale utility class to styleguide

---

react/Viewer/Toolbar.jsx
react/Viewer/ViewerControls.jsx
react/Viewer/index.jsx

Since this is an invalid role.
BREAKING CHANGE: there is no role anymore on Viewer toolbar
Ref is useful to get the height value of this element

feat: Replace "role" of Viewer toolbar by "ref"

---

react/BarContextProvider/index.jsx

Afin d'éviter l'erreur `Error: Cannot use useBreakpoints without BreakpointsProvider. The component must have a BreakpointsProvider above it` dans un ActionMenu présent dans la cozy-bar importée dans une app via 
```
const { BarRight } = cozy.bar
<BarRight>
<BarContextProvider>
<ActionMenu>
</ActionMenu>
</BarContextProvider>
</BarRight>
```

feat: Add bp provider in BarContextProvider

---

react/Viewer/ImageLoader.jsx
react/Viewer/PdfMobileViewer.jsx
react/Viewer/PdfMobileViewer.spec.jsx

- On se basait avant sur `file.links` pour afficher la page d'erreur. Or sur mobile il n'y a pas cette propriété du fait qu'on ne passe pas par la stack. On tombait donc toujours en erreur.
- On ne différencie pas le type d'erreur, si c'est une erreur réseau ou si c'est une erreur de links, les deux affichent la même page d'erreur. Cela pourrait faire l'objet d'une amélioration future : https://github.com/cozy/cozy-ui/issues/1779

fix: PdfMobileViewer shows thumbnail on mobile and correct error

---

react/Viewer/Toolbar.jsx

Since we removed the role https://github.com/cozy/cozy-ui/commit/32f1139, some tests may
not be relevant anymore if they were based on this attribute

fix: Add data-testid on Viewer Toolbar

---

package.json
react/SelectBox/Readme.md
react/SelectBox/SelectBox.jsx
react/__snapshots__/examples.spec.jsx.snap
yarn.lock

Hopefully, this will remove duplicate dependencies (like an old version of react-transition) from our builds.
BREAKING CHANGE: react-select is upgraded from v2 to v4. It should not
impact you but you should be extra careful around the areas that use a
select.
Values are now normalized:
https://github.com/JedWatson/react-select/pull/4339 The onChange callback
receives values that are more coherent now (array if multi select, value is
always an array (can be empty), if a single select, value can be
object/null.
V4 changelog:
https://github.com/JedWatson/react-select/blob/master/packages/react-select/     CHANGELOG.md#400
V3 changelog:
https://github.com/JedWatson/react-select/blob/master/packages/react-select/     CHANGELOG.md#300

feat: Upgrade react-select

---

react/CozyDialogs/styles.styl

On iPhone (at least) we had a bug with few kinds
of Dialog:
- ConfirmDialog small
We can't close them by clicking on the top right cross.
In fact, this is when we have conflicts with few dom elements
(when dialogContentInner withFluidActions).
The DialogCloseButton is "behing" others.
I don't know why it's work on Safari Dekstop but not on Safari Mobile...
Go to https://docs.cozy.io/cozy-ui/react/#!/CozyDialogs with an iOS device. 
Select Small then "Open confirm dialog" and try to close it from the right top cross. 
Go to https://crash--.github.io/cozy-ui/react/#!/CozyDialogs and do the same. It should works.

fix(Dialogs): Fix closing issue with the cross on iOS

---

react/UploadQueue/Readme.md
react/UploadQueue/index.jsx
react/UploadQueue/styles.styl

Harmonisation du style entre la phase d'`upload` et la phase `done`. Ajout de l'état `done` dans les screenshots.
Besoin de ce correctif pour Drive.
Exemple UI : https://jf-cozy.github.io/cozy-ui/react/#!/UploadQueue
Screenshot Drive : 
**Avant :**
**Après :**

fix: UploadQueue header style

---

react/CozyDialogs/Readme.md
react/MuiCozyTheme/theme.jsx

Previously, the z-index was too low and alerts would appear beneath
the MUI Dialog overlay.
See https://ptbrowne.github.io/cozy-ui/react/#/Content?id=cozydialogs

feat: Show alerts on top of mui dialogs

---

react/IntentDialogOpener/IntentDialogOpener.jsx

The problem was that a click on chip inside a row with an onClick
handler would trigger both the row and chip onClick handlers. Here,
I preventDefault() on the ev as a way of saying "this event is
already taken care of", and the click handler of the row checks
ev.defaultPrevented and does not do anything if it is set to true.
I thought of using stopPropagation() but this solution seems less
brutal.

fix: Prevent default when opening intent dialog

---

react/NestedSelect/NestedSelect.jsx
react/NestedSelect/NestedSelect.md
react/NestedSelect/NestedSelect.spec.jsx

feat: Add search input
- Add possibility to search something 
You have to implement onSearch function to define what you want to search
In Cozy Banks, we need to search subcategories in a NestedSelect.
Styleguidist: https://flohhhh.github.io/cozy-ui/react/#!/NestedSelect
Example for Cozy Banks :
Others:
- docs: Add example for search
- refactor: Clean styles

Add search options

---

react/AppSections/components/AppsSection.jsx
react/Tile/index.jsx
react/Tile/styles.styl

Since a previous refactor title is not well displayed specialy
on mobile and when having a long title to display
We simply apply the previous className in order to fix
the issue
https://crash--.github.io/cozy-ui/react/#!/AppSections

fix: TileTitle

---

react/AppSections/Readme.md
react/AppSections/Sections.jsx
react/AppSections/__snapshots__/index.spec.jsx.snap
react/AppSections/_mockApps.js
react/AppSections/components/AppsSection.jsx
react/AppTile/AppTile.spec.jsx
react/AppTile/index.jsx
react/AppTile/styles.styl

Add maintenance display in props
This display is similar to what we have already in cozy home, when a konnector is in maintenance.
By default: maintenanceDisplay is `false` (allow to keep current behavior)
[https://flohhhh.github.io/cozy-ui/react/#/Special?id=appsections](https://flohhhh.github.io/cozy-ui/react/#/Special?id=appsections)

Add maintenance display app sections

---

react/Empty/index.jsx

We have some pages where we do not have any icon. We could
bypass the icon by writing `icon=''` but this is even simpler
to not require the icon in the first place.

feat: Icon is not required for Empty component

---

react/helpers/appDataset.js
react/helpers/appDataset.spec.js

a "false" value previously returned true, as was the case for "tracking" before the stack patch https://github.com/cozy/cozy-stack/pull/3050

fix: ReadCozyDataFromDOM can now deal with "boolean string"

---

stylus/components/selectionbar.styl

fix: Remove wide space between count and text in mobile SelectionBar

---

react/SelectionBar/index.jsx
stylus/components/selectionbar.styl

Le but principal est de corriger l'effet de selected/hover sur chrome : 
Voir https://jf-cozy.github.io/cozy-ui/react/#!/SelectionBar et le retour Argos pour les différences

fix: SelectionBar use Mui Button and IconButton

---

react/SelectionBar/index.jsx

Pour être cabable de contrôler le disabled des actions. Nécessaire par exemple quand on veut rendre enable un bouton alors qu'aucun élément n'est sélectionné. Ce qui avant n'était pas possible, car dans ce cas on forçait le disabled.
Exemples : 
```
selectAll: {
action: () => fillSelection(),
displayCondition: selected => selected.length !== items.length,
icon: SelectAllIcon,
disabled: () => false
}
```
```
selectAll: {
action: () => fillSelection(),
displayCondition: selected => selected.length !== items.length,
icon: SelectAllIcon,
disabled: selected => selected.length > 1
}
```

feat: Add disabled prop on SelectionBar actions

---

package.json
scripts/screenshots.js
yarn.lock

Previous version used to randomly hang while creating screenshots
This issues shows that some old versions are subjective to random
freezes https://github.com/puppeteer/puppeteer/issues/4011
So upgrading to latest version should fix our issue
This fixes https://github.com/cozy/cozy-ui/issues/1842

fix: Upgrade puppeteer

---

package.json

Having exact required version may introduce resolution conflicts when
installed in a project using NPM 7 (which has automatic peer dependency
resolution)

fix: Set cozy-client minimum version in peer dependencies

---

react/CozyDialogs/ConfirmDialog.jsx
react/CozyDialogs/Dialog.jsx
react/CozyDialogs/FixedActionsDialog.jsx
react/CozyDialogs/FixedDialog.jsx
react/CozyDialogs/IllustrationDialog.jsx
react/CozyDialogs/Readme.md

When a dialog doesn't have any action we shouldn't render the
`DialogActions` component, so it won't take any unused space in the
rendered DOM
Fixes #1861
Changes are visible here by switching off `With actions` option : https://ldoppea.github.io/cozy-ui/react/#!/CozyDialogs

feat: Do not render `DialogActions` when `actions` prop is undefined

---

docs/README.md

After a clean checkout, it is not possible to build docs without calling `yarn build:css:all` first.

docs: Add CSS build instruction in `README.md`

---

react/FilePathLink/index.jsx
react/FilePathLink/styles.styl

Minor refactor: Use Material UI props on Link component instead of custom stylesheet

feat: Decouple FilePathLink from stylesheet

---

stylus/objects/layouts.styl

This class is used when the UI is split in two panes, usually when the app has a sidebar and a main content
When using `height:auto`, this prevents the main content to be scrollable if it is smaller than the navbar. Also the navbar is not scrollable at all as its height won't adapt to the browser size
Another effect is that the main content is not scrollable to the end of document when the navbar overflows the document as it virtually push the document's limits outside of the browser view
This behavior is visible only in `cozy-store` as it is the only app that have a navbar tall enough to overflow the browser's body
Other apps are not impacted as their navbar is very small
By removing `height:auto`, then the navbar height adapt to its container size (vs its own size). This allow the main …

fix: Remove `height:auto` from `app-2panes-sticky` class

---

react/AppSections/_mockApps.js
react/AppTile/index.jsx
react/AppTile/styles.styl
react/Tile/index.jsx
react/Tile/styles.styl

This PR add UI improvement on Tiles as they are displayed in `cozy-store`:
- Highlight app tiles that have available update (`update` text is now displayed in primaryColor)
- Highlight app tiles that are installed (tile background is now grey)
- Allow app tiles's names to be displayed on two line when no `status` (installed or update) is set
Changes can be observed here:
https://ldoppea.github.io/cozy-ui/react/#!/AppTile
https://ldoppea.github.io/cozy-ui/react/#!/AppSections

Feat/app tile UI

---

react/AppTile/helpers.js
react/AppTile/index.jsx
react/AppTile/styles.styl
react/Tile/index.jsx
react/Tile/styles.styl

This PR is a rewrite of the previous one : https://github.com/cozy/cozy-ui/pull/1884
Previous PR did not break anything but some of its edits were not effective in production. This is because CSS is not generated in the same order between `yarn build:doc` and `yarn build:css`. So what was visible in the cozy-ui documentation  would not be visible when used in an app.
New PR move the style from `AppTile` to `Tile` and use more specific CSS rules in order to be less dependant from the CSS order resulting from build.

Feat/move app tile UI to tile

---

react/MuiCozyTheme/theme.jsx

In testing environment, MUI transitions were disabled for normal theme
but not for inverted one
Related commit: 5dc817a50e4ebb4d612ebc3d0d002de3664a9ce6
This may fix https://github.com/cozy/cozy-ui/issues/1880

fix: Desactivate MUI transition for inverted theme if is testing

---

react/MuiCozyTheme/Divider/Readme.md
react/MuiCozyTheme/Divider/TextDivider/index.jsx
react/MuiCozyTheme/Divider/TextDivider/styles.styl
react/MuiCozyTheme/Divider/index.jsx

Add a simple divider component to split content sections 
https://acezard.github.io/cozy-ui/react
Used in cozy-home

feat: Add a section divider component

---

docs/components/SectionsRenderer.jsx
react/Icon/Readme.md
react/Icon/index.jsx

We delete this export in order to optimize the size of the Icon component.
As soon as we imported this Icon component we
embed Sprite which is not necessarily used.
This can increase the size of the
application that uses Cozy UI.
BREAKING CHANGE:
Now Sprite is no longer exported by Icon.
However, you can import it directly with
`import Sprite from 'cozy-ui/transpiled/react/Icon/Sprite'`
instead of
`import { Sprite } from 'cozy-ui/transpiled/react/Icon'`

fix: Remove export Sprite from Icon (index.jsx)

---

package.json
scripts/removeEmptyCss.js
scripts/removeEmptyCss.spec.js
yarn.lock

see https://github.com/cozy/cozy-ui/issues/1380
We have sometimes empty generated block. So I made a script to remove them. We don't gain a lot... 🤷‍♂️ 
Previously: 
```
-rw-r--r--   1 quentinvalmori  staff  126282 13 sep 18:38 cozy-ui.min.css
-rw-r--r--   1 quentinvalmori  staff   74637 13 sep 18:38 cozy-ui.utils.min.css
```
After: 
```
-rw-r--r--   1 quentinvalmori  staff  125228 13 sep 18:41 cozy-ui.min.css
-rw-r--r--   1 quentinvalmori  staff   74611 13 sep 18:41 cozy-ui.utils.min.css
```

fix: Add scripts to remove empty blocks

---

.travis.yml

Since cozy/cozy-ui#1917 removed stack tests, the batchCount should be
decremented by 1

fix: Set correct argos batchCount

---

react/SquareAppIcon/Readme.md
react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/SquareAppIcon/index.jsx

To keep the expected `white-space: break-spaces` css value and then
keep the name of SquareAppIcon possible in two lines.

fix: Use u-spacellipsis instead of u-ellipsis for SquareAppIcon name

---

react/Field/Readme.md
react/Field/index.jsx
react/__snapshots__/examples.spec.jsx.snap

On mobile devices, `autoCapitalize` allows to control on-screen
keyboard's behavior regarding words capitalization inside text inputs
Demo: https://ldoppea.github.io/cozy-ui/react/#!/Field
⚠️ only testable on mobile devices. Not compatible with current Firefox version (92) and behavior will depends on your on-screen Keyboard app

feat: Add `autoCapitalize` prop in Fields

---

react/SquareAppIcon/index.jsx

This property is based on AppIcon's type property
It is needed to force the type of konnector icons, or else AppIcon will
try to get their icon from the stack first with the wrong app type
This leads to lots of 404 errors in the home application.
Only after that, AppIcon tries to get the icon from the registry and
succeeds.

feat: Add type prop to SquareAppIcon

---

react/SquareAppIcon/index.jsx
react/SquareAppIcon/styles.styl

This css rule leads to a blurry display on webkit browsers when use
transform: scale on the icon
With use the default behavior instead, which was already used on on
firefox which does not support backdrop-filter yet.

feat: Do not use backdrop-filter on SquareAppIcon anymore

---

react/Icons/LogoutLarge.jsx
react/SquareAppIcon/Readme.md
react/SquareAppIcon/SquareAppIcon.spec.js
react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/SquareAppIcon/index.jsx
react/SquareAppIcon/styles.styl
react/__snapshots__/examples.spec.jsx.snap

To allow a custom icon or even a grid of icon to be displayed
This prop will be used to display category candidates (with a grid of icons) and the exit button with a custom icon on the home application.
- [ X] [Deployed the styleguidist](https://refined-github-html-preview.kidonng.workers.dev/doubleface/cozy-ui/raw/gh-pages/react/index.html#!/SquareAppIcon)

feat: Add IconContent prop to SquareAppIcon

---

react/ContactsList/helpers.spec.js
react/Viewer/AudioViewer.spec.jsx
react/Viewer/PdfMobileViewer.spec.jsx
react/Viewer/ShortcutViewer.spec.jsx
react/Viewer/VideoViewer.spec.jsx

⚠️ we should check that CI passes correctly multiple times (stability), 
_________
This re-add commit ba948b4778efa0c3cfa35258fa0eb48873661e2a that shouldn't have been reverted
cf https://github.com/cozy/cozy-ui/pull/1962
Original PR : https://github.com/cozy/cozy-ui/pull/1956

test: Use waitFor instead of wait

---

react/Radio/Readme.md
react/Radio/index.jsx
react/Radio/index.spec.jsx
react/__snapshots__/examples.spec.jsx.snap

When embedded in a RadioGroup, Radio should be able to handle
RadioGroup's `onChange` and `name` props
Fixes cozy/cozy-ui#1901
Demo visible here : https://ldoppea.github.io/cozy-ui/react/#!/Radio

fix: Allow `Radio` to be part of a `RadioGroup`

---

react/SquareAppIcon/Readme.md
react/SquareAppIcon/index.jsx

To configure to behavior of AppIcon, in SquareAppIcon, we need access to
all AppIcon properties. SquareAppIcon does not have access to the
context of the app enough to make choices regarding :
Ex :
- priority : stack or registry, to avoid too many 404 requests
in the app
Now SquareAppIcon takes it's own properties and forwards the remaining
ones directly to AppIcon
This way, when the AppIcon changes, we do not need to change
SquareAppIcon.

feat: Add appIconProps to SquareAppIcon

---

react/Viewer/docs/DemoProvider.jsx

Fix of the documentation following this commit 621fe47

fix: Replace jest function in documentation

---

stylus/components/button.styl

We have an order problem during the build concerning some css classes.
Classes are imported before others, which causes style errors.
In our case, some properties had to be overridden to keep the expected behavior in the app.
That being said, the Alerter component seems old and not in accordance with the specifications.

fix: Correct colors about Alerter buttons

---

docs/README.md

- Don't use absolute path. It doesn't work on fork's 
- Move React components on top of CSS styleguide since this is mainly the only link we want to go
- deprecated vanilla usage (see https://github.com/cozy/cozy-ui/issues/1991#issuecomment-990706555)

docs: Update readme.md

---

react/Viewer/Footer/BottomSheetContent.jsx
react/Viewer/Footer/FooterContent.jsx
react/Viewer/Panel/Qualification.jsx

Moved the contact async fetch in the Qualification Panel to the FooterContent parent, this prevents `mui-bottom-sheet` from miscalculating one of its style variables.
Demo: https://merkur39.github.io/cozy-ui/react/#!/Viewer/1

fix: BottomSheet no longer opens fully

---

react/AppLinker/index.jsx

In some cases, the Applinker would throw when we just want a warning

fix: Handle context flow without undefined return

---

react/CozyDialogs/ConfirmDialog.jsx
react/CozyDialogs/Dialog.jsx
react/CozyDialogs/FixedActionsDialog.jsx
react/CozyDialogs/FixedDialog.jsx
react/CozyDialogs/IllustrationDialog.jsx
react/CozyDialogs/Readme.md
react/CozyDialogs/e2e.js
react/CozyDialogs/testing.js
react/NestedSelect/Modal.jsx
react/UploadQueue/index.jsx

BREAKING CHANGE: If you were using `data-test-id` prop to test `NestedSelect` or `UploadQueue` components, you should now use `data-testid`. Besides if something fail on `CozyDialog` components, take a look at our helpers in `react/CozyDialogs` to know how to test these components.

feat: Replace data-test-id by data-testid

---

react/CozyDialogs/useCozyDialog.js

to be able to catch dialogTitle ref, in order to compute its height for exemple. Could be useful to determine the maximum height of a bottomSheet inside the dialog

feat: Add `titleRef` on CozyDialogs

---

package.json

Version 1.16.0 is required for cozy-intent and other contexts when requiring information about the presence of a
in-webview render. DevDependencies were up-to-date but peerDependencies were not updated at the time

fix: Bump cozy-device-helper

---

react/AppLinker/index.jsx

We had unwanted rerenders on HomeView in AA application. It was pretty hard to pinpoint the source of the bug because I was looking in the wrong direction, eg React Native. The issue was caused by a simple e.preventDefault() missing in AppLinker. Indeed, without this, each time we sent a message we also refreshed the page (default behavior of `#` href).

fix: PreventDefault on cozy-intent event

---

react/BottomSheet/BottomSheet.jsx

dans certain cas (Viewer de cozy-ui) c'est le name qui est renseigné, dans d'autre cas (CCO2 par exemple) c'est le displayName

fix: Auto ref on BottomSheet Header now use displayName too

---

react/BarContextProvider/index.jsx
react/BarContextProvider/index.spec.jsx

Simply wrap BarContext children with WebviewIntentProvider. This will not break apps not rendered in a webview, as per the test ensures.

feat: Add WebviewProvider in BarProvider

---

react/FilePicker/FilePickerBodyItem.jsx
react/FilePicker/FilePickerBodyItem.spec.jsx
react/FilePicker/docs/DemoProvider.jsx

We should use the `updated_at` and `size` attributes existing in the root of the file, because the `attributes` attribute does not necessarily exist.

fix: Error when attributes doesn't exist

---

react/MuiCozyTheme/makeOverrides.js

Ca fonctionnait dans la doc car il y avait bien la class `Mui-checked` mais dans l'app cette classe est préfixé avec un hash

fix: Radios and Checkbox css to use correct primary/secondary colors

---

react/BottomSheet/BottomSheet.jsx
react/BottomSheet/README.md

To set the height of the middle snap point
Ca permet de forcer une hauteur spécifique pour le point d'ancrage du milieu.
En settant une valeur, il n'y a plus l'effet d'animation car le premier render n'est plus fait avec une hauteur null. Et comme il n'y a plus d'animation, les screenshot argos seront toujours les mêmes.
fix https://github.com/cozy/cozy-ui/issues/2023
=> https://jf-cozy.github.io/cozy-ui/react/#!/BottomSheet

feat: BottomSheet settings accept `mediumHeight` new prop

---

react/FilePicker/FilePickerBodyItem.jsx
react/FilePicker/FilePickerBodyItem.spec.jsx
react/NestedSelect/NestedSelect.jsx

Pour éviter les warning de dépréciation en console, et faire partir en erreur les tests sur les apps qui ont une politique de test stricte (faire échouer le test à cause des warning)

feat: Use new Radio button for FilePicker and NestedSelect

---

docs/README.md

Le lien relatif ne fonctionne pas sur la page github, ou la doc cozy.io/en

docs: Fix external links

---

docs/README.md
react/I18n/format.jsx
react/I18n/format.spec.jsx
react/UploadQueue/Readme.md
react/UploadQueue/index.jsx
react/UploadQueue/index.spec.jsx
react/UploadQueue/locales/en.json
react/UploadQueue/locales/es.json
react/UploadQueue/locales/fr.json

`initFormat` used to specify the language for the `format` method of date-fns.
however `formatDistanceToNow` needs also to specify the lang to correctly translate.
That's why the `initFormat` method has been split in order to init the locale first inside a singleton, and then provide to any format of date-fns a locale.

fix(UploadQueue): UploadQueue manage internationalized progress message

---

react/UploadQueue/index.jsx
react/UploadQueue/styles.styl

Remaining time changes regularly
that used to impact size of progress bar
https://trollepierre.github.io/cozy-ui/react/#!/UploadQueue

fix(upload): Make progress bar size fixed

---

react/Banner/index.jsx
react/Banner/index.spec.jsx

This triggers a lot of warnings in our application
cozy-sharing Banner is waiting for that change
It's just a renamed props
https://mui.com/components/grid/

fix(Grid): Use justifyContent props inside Grid component

---

react/FileImageLoader/index.jsx

Since https://github.com/cozy/cozy-stack/pull/3315 we can
now request a "tiny" thumbnail aka 96x96 px.
Will be useful for list's item

feat: Add tiny size for FileImageLoader

---

react/Buttons/Readme.md
react/Buttons/index.jsx

In order to reference the MUI button from an application, we need the passed reference to be propagated

fix: Propagate the ref on the MUIButton

---

package.json

There should be a mismatch in the way eslint resolve depencencies
In order to keep a high developer experience
let's add eslint-plugin-prettier in devDependencies

chore(eslint): Add eslint-plugin-prettier as devDependencies

---

package.json
react/FilePicker/FilePickerBody.jsx
react/FilePicker/FilePickerBodyItem.jsx
react/FilePicker/FilePickerBodyItem.spec.jsx
react/FilePicker/Readme.md
react/FilePicker/docs/DemoProvider.jsx
react/FilePicker/index.jsx
react/helpers/acceptedTypes.js
react/helpers/acceptedTypes.spec.js
yarn.lock

Added the possibility to accept files with their extensions or their mime type.
related: #2026
Today, the FilePicker is only used on the MyPapers application.
On this application we need to be able to authorize only certain types of files.
For the size of the bundle (in App):
Before:
`cozy-ui@62.2.0`: 123.08 ko
After (without FilePicker): 
`cozy-ui@62.6.0`: 123.17 ko
After (with FilePicker):
`cozy-ui@62.6.0`: 126.54 ko
Démo: https://merkur39.github.io/cozy-ui/react/#!/FilePicker/1

feat: Improve FilePicker component

---

react/ContactsListModal/AddContactButton.jsx

Let's remove this warning. AppLinker now uses `app` props instead of `slug`

test: Use app object instead of slug

---

package.json

Following our guideline, inside any Cozy library,
we expect peerDependency to be either react, react-dom
or other Cozy-library.
As piwik-react-router is not following this case, it should
come as a dependency of Cozy-UI
__
Few projects use regression testing of Cozy-UI: 
https://github.com/cozy/cozy-ui/blob/master/docs/README.md#ui-regression-testing= 
That is why we can be using [peerDependenciesMeta]
(https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta) 
that will consider this dependency as optional.

fix(deps):  Define puppeteer as optional peer dependencies + piwik-react-router as dependencies

---

.github/dependabot.yml

in order to fix not found label error in https://github.com/cozy/cozy-ui/pull/2083

chore(dependabot): Update label because of Cozy-UI label specificity

---

package.json

BREAKING CHANGE: cozy-ui needs this updated version
The Flagship App API changed in cozy-device-helper.
Some components will break if the parent app does not have
cozy-device-helper at ^1.18.0

fix: Upgrade cozy-device-helper in peerDeps

---

react/Viewer/Footer/ForwardButton.jsx

The function used `getSharingLink` to share a link when in mobile web version expects an array of file IDs and not an object

fix(Viewer): Forward button on web mobile

---

react/NavigationList/Readme.md

on n'utilise plus les couleurs en dur comme `u-coolGrey`, le composant devrait être basé sur des couleurs relatives au thème. Inutile donc de le forcer dans la doc, cela donne un aperçu erroné du comportement réel.

docs: Remove forced coolGrey color in NavigationList

---

react/DateMonthPicker/styles.styl
react/DropdownButton/styles.styl
react/Icon/Readme.md
react/Infos/index.jsx
react/InfosCarrousel/styles.styl
react/Menu/styles.styl
react/NavigationList/Readme.md
react/__snapshots__/examples.spec.jsx.snap
stylus/components/action-menu.styl
stylus/settings/themes/inverted.styl

`--iconColor` est utilisé pour remplir la couleur du svg d'une icône https://github.com/cozy/cozy-ui/blob/master/react/Icon/styles.styl#L4 or cette couleur devrait être un héritage de la couleur définie dans le composant, et non une valeur en dur comme c'était le cas jusqu'à aujourd'hui.
On corrige au passage les erreurs de couleur qu'on avait à droite à gauche, en grande majorité pour le theme inversé, oh yeah 🎉

fix: `--iconColor` value for inverted theme

---

react/Viewer/index.jsx

to be able to `import { toolbarPropsPropType } from
'cozy-ui/transpiled/react/Viewer'`
Vu avec @paultranvan sur Drive, ça posait souci sur les tests qui font des imports non profonds du style `{ xxx } from cozy-ui/transpiled/react`

fix: Export toolbarPropsPropType correctly

---

package.json
react/BottomSheet/BottomSheet.jsx
react/Dialog/index.jsx
yarn.lock

BREAKING CHANGE: This will use a more robust CDH API.
In order to support the update, it is needed to upgrade CDH to >=2.0.0

fix: Upgrade cozy-device-helper API

---

react/IconButton/index.jsx

By wrapping the component when exporting it, propTypes can't work anymore and we get this kind of warning in console:
```
Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?
```
We need to use the forwardRef as implemented on this PR or as here: https://bit.ly/3ykcWZx
More info: https://github.com/facebook/react/issues/16653

fix(IconButton): Implementation of forwardRef

---

react/CircleButton/index.jsx
react/MuiCozyTheme/makeOverrides.js

Permet de corriger le fait que l'effet hover s'affiche au clic sur le bouton, alors que ça ne devrait pas
Utilisation de la même approche que Mui : 
https://github.com/mui/material-ui/blob/v4.x/packages/material-ui/src/Button/Button.js#L117
Pour reproduire le souci sur la doc qu'on a en prod : passer en vue mobile, cliquer sur le bouton : on constate que l'effet hover reste actif.
demo : https://jf-cozy.github.io/cozy-ui/react/#!/CircleButton
https://jf-cozy.github.io/cozy-ui/react/#!/Buttons

Fix hover on mobile for CircleButton and Buttons

---

react/Viewer/styles.styl

This is dued to viewer-toolbar padding-top set to flagship-top-height
Adding only top-height was not enough, the best optimization found, is x2
Before:
After:

fix(viewer): Amiral displays PDF without enough margin-top

---

react/helpers/tracker.jsx
react/helpers/tracker.spec.js

Can read appName with both cozy-data={} and
cozy-data-appname to support all our apps.
We do not want to use the userID, and we
and to  remove the tracked domain
or hostname from all page URLs.
(fix a small part of https://github.com/cozy/cozy-ui/pull/1888/files)

fix: Matomo tracking

---

react/CozyDialogs/ConfirmDialog.jsx
react/CozyDialogs/Dialog.jsx
react/CozyDialogs/IllustrationDialog.jsx
react/MuiCozyTheme/makeOverrides.js

fix https://github.com/cozy/cozy-ui/issues/1868
pas de modif sur desktop.
Sur mobile, pas de modif non plus pour les dialogs avec un long content, cela ne concerne donc que les dialog avec un short content. J'ai également vérifié, lorsqu'il n'y a pas d'action button, qu'on ait bien les mêmes marges bottom qu'avant.

fix: Action buttons at the bottom of Dialog/IllustrationDialog on mobile

---

react/Viewer/Panel/getPanelBlocks.spec.jsx

we removed it in Drive because no longer required, so moved it in cozy-ui
See https://github.com/cozy/cozy-drive/pull/2607

test: Add getPanelBlocks from Drive

---

react/Viewer/Footer.jsx
react/Viewer/Footer/DownloadButton.jsx
react/Viewer/Footer/FooterActionButtons.jsx
react/Viewer/Footer/FooterActionButtons.spec.jsx
react/Viewer/Footer/FooterContent.jsx
react/Viewer/Footer/ForwardOrDownloadButton.jsx
react/Viewer/Footer/Sharing.jsx
react/Viewer/Footer/helpers.js
react/Viewer/Footer/useReferencedContactName.jsx
react/Viewer/Readme.md
react/Viewer/ViewerContainer.jsx
react/Viewer/ViewerInformationsWrapper.jsx
react/Viewer/ViewerInformationsWrapper.spec.jsx
react/Viewer/helpers.js

Refactor the viewer to let the app handle the action buttons.
BREAKING CHANGE: The management of action buttons should now be handled on the application side via the `FooterActionButtons` component
Example:
```
<Viewer {...props}>
<FooterActionButtons>
<SharingButton />
<ForwardOrDownloadButton />
</FooterActionButtons>
</Viewer>
```
You can use a codemods `transform-viewer.js` to automatically handle this breaking change.
[See the codemods documentation](https://github.com/cozy/cozy-libs/tree/master/packages/cozy-codemods).
Using linter js auto-correction can be a good idea after that.
Here a common example (don't forget to change `src` value):
```
jscodeshift -t $(yarn global dir)/node_modules/@cozy/codemods/src/transforms/transform-viewer.js src --parser babel --extensions js,jsx && …
```

Make the Viewer Footer composable

---

react/AppLinker/index.jsx

Previously AppLinker was complaining if no context was found,
as soon as the Amiral App loaded.
This creates a ton of unwanted noise in the console.
Instead it is much more optimal to have that logging in the callback,
that way the error is meaningful when it is printed.

fix: Reduce console spam by AppLinker

---

react/BottomDrawer/Readme.md
react/BottomDrawer/index.jsx
react/BottomDrawer/styles.styl
react/Overlay/index.jsx

Le BottomSheet est censé remplacer le bottomDrawer mais il y a encore pas mal de travail à fournir dessus... en attendant on passe un petit correctif pour avoir un BottomDrawer un peu plus utilisable.
demo : https://jf-cozy.github.io/cozy-ui/react/#!/BottomDrawer

feat(BottomDrawer): Add possibility to use it with  long content

---

react/Input/index.jsx

BREAKING CHANGES: The Input component forwards the reference via the HOC `forwardRef` and no longer via the props.
So, the prop `inputRef` becomes `ref`.
You can use a codemods `transform-input.js` to automatically handle this breaking change.
[See the codemods documentation](https://github.com/cozy/cozy-libs/tree/master/packages/cozy-codemods).
Using linter js auto-correction can be a good idea after that.
Here a common example (don't forget to change `src` value):
```
jscodeshift -t $(yarn global dir)/node_modules/@cozy/codemods/src/transforms/transform-input.js src --parser babel --extensions js,jsx && yarn lint:js --fix
```

fix(Input): Ref must be passed by forwardRef

---

react/BottomSheet/BackdropOrFragment.jsx
react/BottomSheet/BottomSheet.jsx
react/BottomSheet/README.md
react/BottomSheet/helpers.js
react/BottomSheet/helpers.spec.js

Il y a eu également pas mal de petits ajustements, ça été compliqué de séparer les commits. La review risque de ne pas être simple à comprendre.
Comportement testé sur mobile dans une app, validé par Joel.
Pour info il y a quelques soucis de comportement sur le doc cozy-ui (la page qui slide par exemple), ce n'est pas présent dans l'app.
On a déjà passé le temps imparti sur le sujet, je ne peux faire que des corrections mineurs et rapides...
demo : https://jf-cozy.github.io/cozy-ui/react/#!/BottomSheet
ps : histoire d'avancer sur les autres features dans Banks dont dépendent cette PR, je suis d'avis de passer outre le comportement bizarre dans Argos (à cause des animations et donc de l'ouverture du BottomSheet)
fix https://github.com/cozy/cozy-ui/issues/2182
fix …

BottomSheet : Add backdrop and onClose props

---

react/SquareAppIcon/Readme.md
react/SquareAppIcon/SquareAppIcon.spec.js
react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/SquareAppIcon/index.jsx

We lose this feature during the creation on the
SquareAppIcon: A shortcut can have an attached
binary and in that case, we want to display
the IconContent instead of the Letter.
See argos for the visual diff

fix: Shortcut with IconContent

---

.bundlemonrc
react/CozyDialogs/styles.styl

le problème initial : https://github.com/cozy/cozy-ui/pull/1790
sauf qu'on avait une valeur trop élevée, et donc les boutons était par-dessus le backdrop (qui a un zindex moindre). Inutile d'avoir une valeur élevée ici, il suffit juste d'avoir une valeur, même faible, pour passer par-dessus le titre et le content, qui eux n'ont pas de zindex.
testé sur iOS 15.5 et 12.4

fix(CozyDialogs): Close and Back button z-index

---

react/BottomSheet/BottomSheet.jsx
react/BottomSheet/constants.js
react/BottomSheet/helpers.js
react/BottomSheet/helpers.spec.js

On ajoute un bloc de la couleur du Bottomsheet en bas de la page pour éviter de voir le contenu sous le BottomSheet si on bouce celui-ci trop haut. Ce bloc n'était pas supprimé quand on fermait le Bottomsheet en cliquant dans le backdrop, contrairement à quand on le fermait avec un swipe down.

fix(BottomSheet): Remove bouncerSafer when  clicking in backdrop

---

react/BottomSheet/BackdropOrFragment.jsx
react/BottomSheet/BottomSheet.jsx

Now we have to click on the backdrop to close it, instead of clicking outside the BottomSheet. This is all the difference. Now we can have a modal above the BottomSheet, and clicking in it doesn't close the BottomSheet anymore.

fix(BottomSheet): Backdrop click behavior

---

react/MuiCozyTheme/makeOverrides.js

Previously it was also applied to small dialogs which is not right.
We only need it on fullscreen modals when in flagship app.

fix: Apply top/bottom spacing on dialog fullscreen

---

react/Viewer/locales/en.json
react/Viewer/locales/fr.json

The app `mespapiers` was already using this key for the "other documents" but it was not yet defined.

fix: Add missing document date label in the viewer

---

package.json
react/AppLinker/__snapshots__/index.deprecated.spec.jsx.snap
react/AppLinker/__snapshots__/index.spec.jsx.snap
react/AppLinker/index.deprecated.spec.jsx
react/AppLinker/index.jsx
react/AppLinker/index.spec.jsx
yarn.lock

When in Flagship mobile app, `AppLinker` is responsible to call
`openApp` for the specified URL and the specified slug, so the mobile
app can handle navigation to the target app
But if the target slug is the same as the current displayed app, it is
unnecessary to call `openApp` as the mobile app would have to handle
navigation to the same route
Instead we want to use the default `web` behaviour in this scenario.
Which means that the web app would redirect to the target URL by using
classic `window.location` redirection
We only check for the URL's slug. The domain here should not be a
problem because if it is the same, then we stay on the app, and if it
is different, then the mobile app would be responsible to detect it and
to open a dedicated view for the external link
Note: this feature …

fix: Prevent `AppLinker` to call openApp when target link has same slug

---

react/BottomSheet/BottomSheet.jsx

Ce composant n'étant pas fait pour recevoir du contenu dynamique, nous avons besoin de le rafraichir si la hauteur du contenu change

Refresh the BottomSheet when the height of the content changes

---

react/Icons/BillPermissions.jsx
react/Icons/CalendarPermissions.jsx
react/Icons/CertifiedPermissions.jsx
react/Icons/HomePermissions.jsx
react/Icons/LocationPermissions.jsx
react/Icons/SafePermissions.jsx
react/__snapshots__/examples.spec.jsx.snap

Fixed: In "Permissions Icons" section, some icon names were unvalid (missing 'Permissions').

fix(Permissions): Display correct Icon names in readme

---

react/LoadMore/index.jsx

Fix of an error that causes a crash in React 18+ version
When unmount the LoadMore component, `elementRef.current` is null in the cleanup function, which caused an error.
Copy the element contained in the ref to a local variable allows the cleanup function to have the element and not a null value
In addition, the `useEffect` should have an array of dependencies 
(Tested with the CoachCO2 app)

fix: LoadMore component effect

---

react/Viewer/Footer/FooterContent.jsx
react/Viewer/Footer/ForwardOrDownloadButton.jsx
react/Viewer/Footer/Sharing.jsx
react/Viewer/Readme.md

Current implementation of iOS Flagship app doesn't handle files
download correctly
So we want to temporarily disable Download button on this platform
This commit is meant to be reverted when files download is fixed on iOS
Flagship app
---
This commit also refactor margin handling on `FooterContent` items
---
Related PRs:
- https://github.com/cozy/cozy-drive/pull/2672
---
TODO:
- [ ] Apply breaking change on [cozy-mespapiers-lib/SelectFileButton](https://github.com/cozy/cozy-libs/blob/a77d785bd557c73d1bf46509697629a471f972de/packages/cozy-mespapiers-lib/src/components/Viewer/SelectFileButton.jsx#L18) after this PR is merged

fix: Do not display Viewer's Download button on iOS Flagship app

---

react/Viewer/ViewerControls.jsx

An user reported us that he was not able
to select a text from a PDF (https://github.com/cozy/cozy-drive/issues/2673).
After a quick look, it appears that HammerJS
adds a `user-select:none` inline style in
order to be able to add its gestures things.
We can disable this option when creating the
Hammer object. This is what I've done here
for the desktop version.
I also removed the swipe gesture for desktop
because we can have "conflict" between text
selection and swipe. This is why I didn't
remove this behavior on mobile, since I don't
have the time to test it correctly on several
devices.
It also appears that we don't need the tap/
doubletap gesture anymore in order to display
the controls because the control is now
only displayed on hover. Else wehre, the opacity
is set to false. …

feat: Let the user able to select content

---

package.json
react/ContactPicker/index.jsx
react/ContactsList/ContactRow.jsx
react/ContactsList/Contacts/ContactIdentity.jsx
react/ContactsListModal/ContactsListContent.jsx
yarn.lock

Cozy-doctypes is an old project that should not be used
anymore.
Almost all the contact's related methods have been moved
to cozy-client so let's use them.
We lose the Contact's proptype ATM, but it will come
back with cozy-client's types pretty soon.

fix: Don't rely on cozy-doctypes

---

react/AppLinker/native.js

new URL('cozy.tools') rejected errors of invalid url.

docs(AppLinker): explicit correct url to generate web link

---

react/BottomSheet/BackdropOrFragment.jsx
react/BottomSheet/BottomSheet.jsx
react/BottomSheet/README.md
react/CozyDialogs/Readme.md
react/CozyTheme/index.jsx

Le BottomSheet fonctionne maintenant plus logiquement, à savoir comme une modale, à savoir avec Portal et donc par défaut s'attache au body. C'est le comportement des Modal et Dialog de Mui, j'ai repris la même approche.
BREAKING CHANGE: BottomSheet now use Portal by default to work as a modal, and so is attached to the body. If for some reasons you need to use the BottomSheet inside a specific place in the DOM, you can use `disablePortal` prop.
demo : https://jf-cozy.github.io/cozy-ui/react/#!/BottomSheet et https://jf-cozy.github.io/cozy-ui/react/#!/CozyDialogs

Wrap BottomSheet in Portal

---

react/Viewer/Footer/ForwardOrDownloadButton.jsx

This commit is a revert from  db2303da03b4ea445737dad9a5de16bac71fe3b4
In previous commit we removed the Viewer's Download button on iOS
Flagship app as this platform was not able to handle downloads
correctly
Now that we implemented a solution to handle downloads on this platform
we can add this feature back
Related PR: cozy/cozy-ui#2215

feat: Display Viewer's Download button on iOS Flagship app

---

.travis.yml
package.json
yarn.lock

The support of argos-cli has been removed
by argos team. We need to upgrade to this
new cli.
Let's see if it fix our current issue
(errors during uploading screenshots to argos)

chore: Upgrade argos-cli

---

react/Viewer/Footer/FooterContent.jsx

In 22776e2d46a254dd22aca6411e294706952bc696 we chose to handle gap
between items directly in `FooterContent` so child items don't have to
care about this
We forgot to propagate this into BottomSheet version of the Viewer's
footer (i.e: when displaying CarbonCopy data)

fix: Restore BottomSheet items' gap in `FooterContent` container

---

react/Viewer/Footer/useReferencedContactName.jsx

The Query being conditioned by `contactIds.length > 0`,
`isLoadingContacts` must also be.
Otherwise `isQueryLoading(contactsQueryResult)` is always `true`.

fix: isLoadingContacts on useReferencedContactName hook

---

react/MuiCozyTheme/makeOverrides.js

Initialement on avait un souci qui faisait que lorsqu'on cliquait sur un ListItem button, l'effet focus restait présent, particulièrement visible si le button ouvre une modale, qu'on ferme ensuite.
Ici on reprend le style initiale de Mui, ce qui corrige le problème.
demo : https://jf-cozy.github.io/cozy-ui/react/#!/List

fix(ListItem): Focus effect remains after a click on button ListItem

---

react/Viewer/Panel/ActionMenuWrapper.jsx
react/Viewer/Panel/Qualification.jsx
react/Viewer/Panel/QualificationListItemDate.jsx
react/Viewer/Panel/QualificationListItemInformation.jsx
react/Viewer/Panel/QualificationListItemOther.jsx
react/Viewer/Panel/QualificationListItemText.jsx
react/Viewer/Readme.md
react/Viewer/helpers.js
react/Viewer/helpers.spec.js
react/Viewer/locales/en.json
react/Viewer/locales/fr.json

On souhaite maintenant afficher toutes les qualification possible sur un document dans le viewer augmenté. Précédemment lorsqu'ils étaient vides, on ne les affichait pas. Ils sont maintenant affichés avec une valeur par défaut.
demo : https://jf-cozy.github.io/cozy-ui/react/#!/Viewer

feat(Viewer): Show all possible qualification  data, uninformed if empty

---

react/Viewer/ViewersByFile/ImageViewer.jsx
react/Viewer/hoc/withFileUrl.jsx

In React >=18, only the UNSAFE_ name will work.
The "UNSAFE_componentWill*" methods have been added since React 16.3.

fix: Rename componentWill* to UNSAFE_componentWill*

---

.travis.yml

ignore argos si `[skip argos]` est présent dans le titre de la PR.
A utiliser avec des pincettes. C'est par exemple pour faire passer des PR de modif de doc non argosée, ou de refacto de code non argosé comme des tests ou autre

chore: Add skip argos possibility for CI [skip argos]

---

react/Viewer/Panel/ActionMenuWrapper.jsx
react/Viewer/Panel/getPanelBlocks.jsx
react/Viewer/components/ViewerByFile.jsx
react/Viewer/helpers.js
react/Viewer/helpers.spec.js

En plus d'interdire la modification de la metadata `issueDate` d'un fichier si le ce dernier provient d'un Connecteur, j'en ai profité pour enlever quelques doublons dans les helpers du Viewer

The issueDate by a Connector must not be modifiable

---

react/Viewer/Panel/Qualification.jsx
react/Viewer/Panel/QualificationListItemInformation.jsx
react/Viewer/helpers.js

Suite à un refactor précédent, le nom du contact(Titulaire) n'apparaissait plus.
Et ajout du composant `MidEllipsis` afin d'éviter d'avoir des valeurs trop longues qui pourrait gâcher l'UX

Fix contact & country attributes

---

react/Viewer/Panel/QualificationListItemInformation.jsx
react/Viewer/Panel/QualificationListItemInformation.spec.jsx

L'ajout récent du composant MidEllipsys pour limiter (entre autres) le champs `country` à causé un bug dans le cas où le champs n'est pas renseigné..
Ajout de quelques tests pour éviter une régression à ce sujet

fix(Viewer): Do not use MidEllipsys component if text prop is falsy

---

react/BottomSheet/BottomSheet.jsx
react/BottomSheet/helpers.js
react/BottomSheet/helpers.spec.js
react/helpers/getSafeArea.ts
stylus/elements/defaults.styl

On ne prenait pas en compte le safe area sur iOS. On en profite pour agrandir la taille de la poignée

BottomSheet: Add safe area

---

react/CozyDialogs/Readme.md
react/CozyDialogs/useCozyDialog.js

On souhaite pouvoir ajouter des boutons dans le titre d'une modale. Or à cause des padding implicites ce n'est pas possible car le bouton faisant 48px, on se retrouve avec un titre qui a une hauteur de 48px + padding.
L'idée est alors de pouvoir supprimer les padding. Pour ce faire, deux solutions : soit des props spécifiques, soit un prop plus globale. C'est cette solution qu'on retient (explication dans cet article https://mui.com/blog/making-customizable-components/#passing-props ) afin de stopper l'ajout d'un enième prop (il y en a déjà trop) et permettre plus de modularité à l'app qui utilise la Dialog.
J'ai rajouté un exemple dans la doc

feat(CozyDialogs): Add possibility to override DialogTitle props

---

react/I18n/index.jsx
react/I18n/index.spec.jsx

When using createUseI18n, default langage was not loaded. Missing keys were displayed instead of default langage translations.

fix: Load default langage when using createUseI18n

---

react/BottomSheet/helpers.js
react/BottomSheet/helpers.spec.js

If the innerContent is smaller than the mediumHeight, we don't want the BottomSheet to take all the available space. We want to take only the needed place.
The global idea is: 
- App can set the mediumHeight for the BottomSheet 
- But if the content is smaller than this mediumHeight, the BottomSheet size should not be this mediumHeight but should be the content size instead. 
Here is a before / after (this test is already in the Readme...): 
demo here: https://crash--.github.io/cozy-ui/react/#!/BottomSheet (deselect backdrop and play with no long content)

fix: Fix bottomSheet height if the content is pretty small 

---

react/AppSections/search.js
react/AppSections/search.spec.js

```
* add maintenance activated matcher
```
It allows you to filter the applications in the AppSection to display only those that are not under maintenance. 
**Related PRs:**
* https://github.com/cozy/cozy-store/pull/829

feat(search.js): add maintenance activated matcher

---

package.json
react/Viewer/Panel/Qualification.jsx
react/Viewer/Panel/QualificationListItemDate.jsx
react/Viewer/Readme.md
react/Viewer/components/ExpirationAlert.jsx
react/Viewer/components/ExpirationAnnotation.jsx
react/Viewer/locales/en.json
react/Viewer/locales/fr.json
yarn.lock

This will be on top of cozy/cozy-client#1274 and thus will need an update of `cozy-client`.
For consistency, `cozy-harvest-lib` should also be updated after cozy/cozy-libs#1893 is merged, but this is not required by this PR.
Demo link : https://polaritoon.github.io/cozy-ui/react/#!/Viewer

Add expiration panel

---

react/AppSections/search.js
react/AppSections/search.spec.js

Rename underMaintenance to showMaintenance filter to improve understanding into `cozy-store`. This filter now show all apps when it's true and hide apps under maintenance when it's false.

fix(search.js): rename underMaintenance to showMaintenance

---

react/Buttons/Readme.md
react/MuiCozyTheme/makeOverrides.js
react/__snapshots__/examples.spec.jsx.snap

As a result of the changes made to `MuiButton`,
the text is not well centered vertically.
By setting the `line-height` property to `normal`,
we get the correct centering
Before:
https://docs.cozy.io/cozy-ui/react/#!/Buttons
After:
https://merkur39.github.io/cozy-ui/react/#!/Buttons

fix(Buttons): LineHeight property

---

react/AppSections/__snapshots__/search.spec.js.snap
react/AppSections/search.js
react/AppSections/search.spec.js

in this cas it will be ignored, but function will not crash anymore
cas d'usage : dans le store on filtre les app/connecteur en fonction des searchParams. Or si on passe un autre searchParams qui n'a rien à voir avec la recherche, l'app plante car la méthode crash

fix(AppSections): MakeMatcherFromSearch now accept unsupported filter

---

react/BottomSheet/BottomSheet.jsx

This necessitates a call to setFlagshipUi()
This also requires a default offset for the bottomSheet,
which will only be populated in immersive apps

feat: adapt BottomSheet to flagship app

---

react/CozyDialogs/TopAnchoredDialog.jsx
react/GhostFileBadge/index.jsx
react/InfosBadge/index.jsx
react/IntentDialogOpener/IntentDialogOpener.md
react/IntentIframe/Readme.md
react/MuiCozyTheme/Divider/index.jsx
react/MuiCozyTheme/List/index.js
react/MuiCozyTheme/Menus/index.js
react/MuiCozyTheme/index.jsx
react/MuiCozyTheme/makeOverrides.js
react/MuiCozyTheme/makeTheme.js
react/Paper/Readme.md
react/ProgressionBanner/index.jsx
react/UploadQueue/index.jsx
react/Viewer/components/InformationPanel.jsx
react/Viewer/components/ViewerControls.jsx

to stop relying on mui/styles directly. This prepare mui v5 migration

refactor: Replace imports @material-ui/core/styles -> react/styles

---

react/CozyDialogs/IllustrationDialog.jsx

it is now, no matter if there is a back or close button
Il manquait le wrapper de suppression des marges qu'on avait pourtant sur les autres modales avec un titre fluide (non fixe), et on rajoutait une marge s'il y avait un bouton back (ce qui était inutile)
**avant**
**après**

fix(IllustrationDialog): The title was not centered properly

---

jest.config.js
package.json
react/I18n/format.jsx
react/I18n/format.spec.jsx
yarn.lock

On veut afficher le nombre de jour entre une date et la date actuelle, peu importe l'heure de ces dates.
Avant on tombait dans un cas où on pouvait afficher 1 jours alors que 2 jours calendaires séparaient deux dates, car date-fns considère qu'on parle en jour seulement s'il y a entre 23 et 41 heures d'écart entre 2 dates https://date-fns.org/v1.28.5/docs/distanceInWordsToNow
Pour une différence entre 2 jours calendaires mais moins de 41h d'écart, ça affichait donc 1 jours au lieu de 2.
On aurait pu changer la façon de faire un arrondi avec partialMethod ceil de https://date-fns.org/v1.28.5/docs/distanceInWordsStrict mais on se retrouvait avec le même problème dans l'autre sens.
Nous on souhaite simplement parler en jour en fonction du nombre de jour calendaire qui sépare les dates, peu …

Force  formatLocallyDistanceToNowStrict  to use whole number of day

---

react/Alert/index.jsx
react/MuiCozyTheme/makeOverrides.js

This makes sure the message fills all the width available, and adjusts some horizontal margins.
Demo link : https://polaritoon.github.io/cozy-ui/react/#!/Alert

Make sure the message fills all the available width in `Alert` and allow overriding its classes 

---

react/Alert/index.jsx
react/MuiCozyTheme/makeOverrides.js

This forward ports #2333 (identical changes).
Demo link : https://polaritoon.github.io/cozy-ui/react/#!/Alert

Port "Make sure the message fills all the available width in `Alert` and allow overriding its classes" to `next`

---

react/Viewer/helpers.js
react/Viewer/locales/en.json
react/Viewer/locales/fr.json

Port "Show CAF file number and reference tax income in the viewer" to `next`

---

react/ActionMenu/index.spec.jsx
react/Alerter/alerter.spec.js
react/AppIcon/test/AppIcon.spec.js
react/AppLinker/index.deprecated.spec.jsx
react/AppLinker/index.spec.jsx
react/AppLinker/native.js
react/AppTile/AppTile.spec.jsx
react/CipherIcon/index.spec.jsx
react/ContactsListModal/index.jsx
react/DateMonthPicker/index.spec.jsx
react/Field/index.spec.js
react/FileInput/index.spec.jsx
react/FilePicker/FilePickerHeader.jsx
react/I18n/withLocales.jsx
react/Input/index.spec.jsx
react/Modal/index.spec.jsx
react/PieChart/index.spec.jsx
react/Popup/index.spec.jsx
react/PushClientButton/index.spec.jsx
react/Radio/index.spec.jsx
react/SquareAppIcon/SquareAppIcon.spec.js
react/UploadQueue/index.spec.jsx
react/ViewStack/example.jsx
react/ViewStack/index.spec.jsx
react/Viewer/Viewer.jsx
react/Viewer/ViewerExposer.js
react/Viewer/components/ViewerControls.jsx
react/hooks/useConfirmExit/index.spec.js

Port "Use extensionless specifiers when importing JS files" to `next`

---

react/Viewer/ViewersByFile/ImageViewer.jsx

The problem has been encountered when updating a page is too fast for example with an useQuery. Each time thee ImageViewer is unmounted, we also teardown all the gestures. The imageViewer crashes because the Gesture object have not yet been defined. This fix checks if Gesture exists before calling any functions on it.

fix: ImageViewer crashes when render are too fast

---

react/SquareAppIcon/Readme.md
react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/SquareAppIcon/index.jsx
react/SquareAppIcon/styles.styl

- Adds a `"loading"` value to the variant prop in `<SquareAppIcon />`
- A default `"default"` value was needed for a good transition
- Scale has been calculated from design (52px/64px)
- Animation works in and out
- Link to demo: https://acezard.github.io/cozy-ui/react/#!/SquareAppIcon

feat: Add `loading` variant to SquareAppIcon

---

package.json
react/MuiCozyTheme/List/Readme.md
react/MuiCozyTheme/ListItem/ExpandedAttributes/ExpandedAttribute.jsx
react/MuiCozyTheme/ListItem/ExpandedAttributes/helpers.js
react/MuiCozyTheme/ListItem/ExpandedAttributes/helpers.spec.js
react/MuiCozyTheme/ListItem/ExpandedAttributes/index.jsx
react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/ActionMenuWithClose.jsx
react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/ActionsItems.jsx
react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/helpers.js
react/MuiCozyTheme/ListItem/ListItemBase/ActionsMenu/helpers.spec.js
react/MuiCozyTheme/ListItem/ListItemBase/Renaming/RenameDialog.jsx
react/MuiCozyTheme/ListItem/ListItemBase/Renaming/RenameInput.jsx
react/MuiCozyTheme/ListItem/ListItemBase/Renaming/helpers.js
react/MuiCozyTheme/ListItem/ListItemBase/index.jsx
react/MuiCozyTheme/ListItem/ListItemByDoc/index.jsx
react/MuiCozyTheme/ListItem/ListItemContact/index.jsx
react/MuiCozyTheme/ListItem/ListItemFile/ExpirationAnnotation.jsx
react/MuiCozyTheme/ListItem/ListItemFile/ItemIcon.jsx
react/MuiCozyTheme/ListItem/ListItemFile/PrimaryText.jsx
react/MuiCozyTheme/ListItem/ListItemFile/SecondaryText.jsx
react/MuiCozyTheme/ListItem/ListItemFile/index.jsx
react/MuiCozyTheme/ListItem/hoc/withListItemLocales.jsx
react/MuiCozyTheme/ListItem/locales/en.json
react/MuiCozyTheme/ListItem/locales/fr.json

On crée ici un composant très haut niveau ListItemDoc qui va retourner un style de ListItem spécifique selon le type de document (`io.cozy.files` et `io.cozy.contacts` pour l'instant).
Ce ListItem prend en charge les actions, le renommage, le multiselect, et l'affichage d'attributs "augmentés" avec le copy to clipboard dessus
implémentation ici https://github.com/cozy/cozy-libs/pull/2067
démo : https://jf-cozy.github.io/cozy-ui/react/#!/List (paragraphe **Contextualized item**)

ListItem by doctype

---

react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/SquareAppIcon/index.jsx

fix: remove margin on sqAppIcon spinner

---

react/Paywall/OnlyOfficePaywall.jsx

I was using isMobileApp but it's only detect cordova app. So I added a check on isFlagshipApp to detect all mobile app

fix: Detect flagship app on paywall

---

react/CircleButton/index.jsx
react/I18n/format.spec.jsx
react/MuiCozyTheme/TextField/index.jsx
react/helpers/getRandomUUID.js
react/helpers/getRandomUUID.spec.js
test/jestsetup.js

We recently used the `randomUUID` method of `crypto`, and added a special configuration for testing with `Jest`. We should have added a BC at that time, because e2e tests of applications can fail if they also do not have the correct Jest configuration.
I propose here a better approach, which will avoid a BC and changes on the application side

feat: Use helper for get random UUID

---

.travis.yml
package.json
yarn.lock

Notre CI avec Argos était cassé. Argos ne récupérait pas les builds pour faire ses screenshots, donc aucun screenshot n'était créé. C'est un premier correctif fait.
Suite à ça, ça ne marchait toujours pas, il a fallut mettre à jour les libs argos-cli et puppeteer.
Enfin on split les 3 scripts de screenshots argos en 3 jobs différents pour gagner du temps de CI ( on passe de 15min à 7min).
Côté Argos https://app.argos-ci.com/cozy/cozy-ui comme le build de référence sur master est cassé depuis un moment il n'y a aucun screenshot de référence. Donc si on observe le build de cette PR sur Argos on verra qu'il compare des empty avec les screenshots de cette PR.

feat: Make Argos working again

---

react/SelectionBar/Readme.md
react/SelectionBar/SelectionBarAction.jsx
react/SelectionBar/SelectionBarMore.jsx
react/SelectionBar/helpers.js
react/SelectionBar/helpers.spec.js
react/SelectionBar/index.jsx
stylus/components/selectionbar.styl

In cozy-drive, up to 8 or more actions can be displayed at the same time. On both large and tiny screens, the actions overflow behind the close button. To solve this problem, we decided to limit the number of actions displayed for certain screen sizes. Actions exceeding this limit are displayed in an additional menu. 
**Live preview:** https://cballevre.github.io/cozy-ui/react/#!/SelectionBar/
**Some examples on Drive:**
Large screen size:
Medium screen size:
Tiny screen size: 
Large screen size on banks :

fix(SelectionBar): Limit the number of actions displayed

---

react/Viewer/Readme.md
react/Viewer/ViewersByFile/PdfJsViewer.jsx
react/Viewer/docs/DemoProvider.jsx

Quick feature to improve viewer usability for large pdf :
- key up to go to previous page
- key down to go to next page
Live demo : https://zatteo.github.io/cozy-ui/react/#!/Viewer

Navigate between pdf pages with keyboard

---

jest.config.js
package.json
react/ActionMenu/Readme.md
react/BottomSheet/README.md
react/Viewer/Readme.md
react/Viewer/ViewersByFile/PdfJsViewer.spec.jsx
yarn.lock

This update provides version 2.12.313 of pdfjs-dist. This version resolves rendering issues with some PDFs like the screenshot above. There is two breaking change on the way to import react-pdf into final application. All the detail can be found into the commit message of https://github.com/cozy/cozy-ui/commit/c0d74413b572d4b84dbd8159974d388da8132769
**Development notes :**
I tried to upgrade to the latest version of react-pdf which is currently 6.2.2. But I encountered a problem related to this issue: https://github.com/wojtekmaj/react-pdf/issues/1043 from the pdf.js lib. It seems that there is a link with our webpack configuration. I modified the babel configuration to transcompile the pdf.js module without success.

Feat: Update react-pdf to 5.7.2

---

assets/icons/animated/icon-check-animated.svg
assets/icons/animated/icon-cross-animated.svg
react/Icons/IconCheckAnimated.jsx
react/Icons/IconCrossAnimated.jsx
react/SquareAppIcon/Readme.md
react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/SquareAppIcon/index.jsx
react/SquareAppIcon/styles.styl

From variant 'loading' to either variant 'default' or 'error'
https://acezard.github.io/cozy-ui/react/#!/SquareAppIcon

feat: Add success/fail animations to SquareAppIcon

---

react/SelectionBar/index.jsx
react/SelectionBar/useMaxActions.jsx

With the French translation, I encountered a spacing issue with the action lists on wide devices. I added a wide breakpoint to have more granularity in the maximum action displayed. Breakpoints are specific to the selection bar because isTiny, isSmall, isMedium, isLarge will be deprecated in useBreakpoint

fix(SelectionBar): Adapt max actions to extra large device

---

react/MuiCozyTheme/ListItem/ExpandedAttributes/helpers.js
react/MuiCozyTheme/ListItem/ExpandedAttributes/helpers.spec.js
react/MuiCozyTheme/ListItem/ExpandedAttributes/index.jsx
react/MuiCozyTheme/ListItem/locales/en.json
react/MuiCozyTheme/ListItem/locales/fr.json
react/Viewer/Panel/QualificationListItemInformation.jsx

- Add "€" unit on display of `refTaxIncome` metadata
- Add the word "day(s)" to the display of the `noticePeriod` metadata

feat: Add units on certain attributes on ExpandedAttributes component

---

react/SquareAppIcon/index.jsx

This hotfix addresses an issue where the success and failure icons would only display for the first occurrence across different features. The root cause of the problem was found in the animation event handling logic.
Changes:
- Updated the `handleAnimationEnd` function to use `includes` instead of `startsWith` when checking for the `end-animation` event. This change ensures that the animation state is reset correctly after the animation ends, even when the animation name has a prefix, such as in production.
Testing:
- Tested manually the updated implementation to ensure that the success and failure icons display correctly for each occurrence across different features.
This hotfix resolves the issue with the success and failure icons and improves the overall user experience.

Fix Success and Failure Icons Only Displaying for First Occurrence

---

.travis.yml

Il y a parfois des soucis avec les `node_modules` et le cache, qui fait que certains builds plantent car utilisent une version erronés (provenant d'un autre build) des `nodes_modules`. Le vidage du cache résout le souci.
Ici https://stackoverflow.com/questions/42521884/should-i-have-travis-cache-node-modules-or-home-npm on découvre que mettre en cache le dossier `node_modules` est déprécié et qu'il faut préférer `$HOME/.npm`
Cependant à la lecture de ces documents https://docs.travis-ci.com/user/caching/#npm-cache et https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#npm-ci-support je pense qu'on peut d'abord essayer en utilisant le cache par défaut de yarn à savoir `$HOME/.cache/yarn`.
L'idée initiale était de forcer l'install des `node_modules` PAR build, et de n'avoir un …

chore(travis): Use default cache directory for yarn

---

react/CozyDialogs/styles.styl
react/MuiCozyTheme/makeOverrides.js

It only needs to be applied when displayed in a full screen modal,
so we are changing where the style is defined.
This will fix small modals appearing in flagship app with
pushed down buttons

fix: Apply flagship style to closebutton higher

---

react/SelectionBar/index.jsx

This PR fixes a silly mistake. I was using the wrong key between breakpoints (cf: [definitions](https://github.com/cozy/cozy-ui/blob/45bc4bb5b57f58b69fd9c91b06ff7d621d7c639c/react/SelectionBar/useMaxActions.jsx#LL12C3-L12C9)) and max actions for huge device

fix(SelectionBar): Mismatch between max action key

---

react/SquareAppIcon/Readme.md
react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/SquareAppIcon/constants.json
react/SquareAppIcon/index.jsx
react/SquareAppIcon/styles.styl

We want to implement an inverted theme for SquareAppIcon
In previous implementation, SquareAppIcon would be displayed identically on both inverted and normal theme
The new usage is that normal theme should be used on light backgrounds and inverted theme should be used on dark background or on backgrounds that may have many details on theme (i.e. photo based backgrounds)
BREAKING CHANGE: To keep previous SquareAppIcon render, you should display it inside of an inverted Cozy Theme
___
Related PR: cozy/cozy-home#1939

feat: Make SquareAppIcon compatible with normal and inverted themes

---

react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/SquareAppIcon/index.jsx

Previously it was rendered too liberally.
Now it is rendered only when
- Component is in "loading" variant
- Component has an animationState (success or failed),
which triggers after a loading finishes. We need this
because we don't want to hide the spinner as soon as the loading is over
We want to wait for the ending animation too so the transition looks
smooth.
Also refactored the spinner logic out of the main component for clarity

fix: show spinner when needed in squareappIcon

---

.travis.yml

Permet de faire un commit avec les mots clés `[only argos]` afin de ne lancer que le stricte nécessaire pour Argos sur la CI.
Et ce pour pouvoir "rapidement" avoir une comparaison Argos

chore: Add var to launch only Argos on CI

---

react/Viewer/Panel/QualificationListItemInformation.jsx

In the case where the user enters a type of contract manually, the translation key cannot correspond, and in this case we want to display the value entered directly.

fix(Viewer): ContractType metadata must display default value

---

react/Alerter/styles.styl
react/Checkbox/styles.styl
react/CozyTheme/index.jsx
react/Dialog/index.jsx
react/HistoryRow/styles.styl
react/Infos/styles.styl
react/InfosCarrousel/styles.styl
react/InlineCard/styles.styl
react/Modal/styles.styl
react/Nav/styles.styl
react/SelectBox/styles.styl
react/SelectionBar/styles.styl
react/Spinner/styles.styl
react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/Stack/styles.styl
react/Toggle/styles.styl
react/UploadQueue/styles.styl
react/Viewer/ViewersByFile/styles.styl
react/Viewer/components/styles.styl
react/Viewer/styles.styl
react/utilities.js
stylus/components/card.styl
stylus/components/chip.styl
stylus/components/panels.styl
stylus/components/selectionbar.styl
stylus/cozy-ui/utils.styl

Deux css sont utilisées dans la app en provenance de cozy-ui : 
- `cozy-ui/transpiled/react/stylesheet.css`
- `cozy-ui/dist/cozy-ui.utils.min.css`
La première, `stylesheet.css` est une css comportant les class hashé des composants react (legacy ou non, à partir du moment où on utilise du stylus dans le composant). Or il y avait différents problèmes : 
- contenait plusieurs fois les var CozyTheme normal `.styles__CozyTheme``--``normal___xxx` et inverted `.styles__CozyTheme--inverted___xxx` (avec hash)
- contenait plusieurs fois les classes utilitaires (sans hash)
- contenait plusieurs fois les styles sur les tag comme `html`, `:root` etc.
La deuxième `cozy-ui.utils.min.css` contient les classes utilitaires sans hash, ainsi que les class `CozyTheme`
démo pour comparer avec la prod actuel : …

Rework cozy-ui css to avoid massive duplication

---

docs/components/Readme.md
docs/components/Readme/Readme.md
docs/components/Readme/index.js
docs/styleguide.config.js

the `core`, `extra`, `legacy` groups in the documentation contains now a lot of components, so the first load of these pages is very long. This is a quick fix but we need to investigate further (and maybe migrates to storybook...)
démo : https://jf-cozy.github.io/cozy-ui/react/

docs: Add a fake first component to reduce first time loading

---

react/UploadQueue/styles.styl
react/Viewer/ViewersByFile/styles.styl
react/Viewer/components/styles.styl
react/Viewer/styles.styl
react/deprecated/BottomDrawer/styles.styl
stylus/components/alerts.styl
stylus/components/avatar.styl
stylus/components/modals.styl
stylus/components/nav.styl
stylus/components/overlay.styl
stylus/components/popover.styl
stylus/components/selectionbar.styl
stylus/components/table.styl
stylus/cozy-ui/utils.styl
stylus/objects/layouts.styl
stylus/settings/z-index.styl

Prefer to import z-index.styl in utils.styl to avoid duplication.
Follows @JF-Cozy work here https://github.com/cozy/cozy-ui/pull/2454

 fix(css): Avoid importing z-index.styl in each css of legacy component

---

react/Viewer/Panel/styles.styl

Otherwise the style in `action-menu.styl` takes priority.
Waiting for the migration of the ActionMenu on the Viewer

fix(Viewer): Force style of ActionMenuDesktop

---

stylus/components/alerts.styl
stylus/settings/z-index.styl

BREAKING CHANGE: Rename `--zindex-alert` CSS variable to `--zIndex-alert`

fix(Alerts): Use correct CSS variable for z-index property

---

react/ActionsMenu/ActionsItems.jsx
react/ActionsMenu/ActionsMenuWrapper.jsx
react/ActionsMenu/Readme.md

Lors de la construction d'une action, il est maintenant possible de passer un argument à onClick afin de le récupérer dans les actions.

ActionsItems: Add possibility to spread arg  between onClick and actions

---

react/ContactPicker/index.spec.jsx
react/ContactsListModal/Readme.md
react/CozyDialogs/Readme.md
react/CozyDialogs/testing.spec.jsx
react/Dialog/Readme.md
react/I18n/createUseI18n.jsx
react/I18n/index.jsx
react/I18n/translate.jsx
react/NestedSelect/NestedSelect.md
react/SelectBox/Readme.md
react/providers/DemoProvider.jsx

Ceci est une première PR concernant une sujet de déplacement des providers dans un nouveau dossier react/providers.
J'avais corrigé quelques trucs sur les providers I18n et CozyTheme. Comme c'est trop long de tout reprendre d'un coup, je découpe en morceau. Ici cela concerne I18n.
On en profite pour créer le dossier /react/providers et d'utiliser un premier provider `DemoProvider` qui ne sert pour  l'instant qu'à cozy-ui.
Suivra ensuite les PR concernant le déplacement des providers de cozy-ui pour les app.

Add DemoProvider and throw error in useI18n

---

react/Viewer/components/ToolbarFilePath.jsx
react/Viewer/helpers.js
react/Viewer/helpers.spec.js

When the file was at the root and the path ended with a slash, the path displayed to the user was `//`. I've improved the function to avoid this

fix(Viewer): Remove filename on path ending with slash

---

react/NestedSelect/ItemRow.jsx
react/NestedSelect/NestedSelect.jsx
react/NestedSelect/NestedSelect.md

In order to keep the default behavior of ListItem(ListItemtext), we only use the `ellipsis` prop when it is `false`.

feat(NestedSelect)/Manage ellipsis

---

react/BottomSheet/BottomSheet.jsx
react/BottomSheet/helpers.js
react/BottomSheet/styles.styl
react/NestedSelect/BottomSheet.jsx
react/NestedSelect/NestedSelect.jsx
react/NestedSelect/NestedSelect.md

Corrige dans le NestedSelect le fait de cliquer sur l'option B sans que la taille du BottomSheet ne soit changée
demo : https://jf-cozy.github.io/cozy-ui/react/#!/NestedSelect

Add rerendering content compliancy on  BottomSheet

---

react/IntentIframe/IntentIframe.jsx
react/deprecated/IntentModal/IntentModal.jsx

This way, a service can decide if it want to hide or show the cross modale to be closed.
This is usefull when a service can handles its close by itself (like harvest for instance).

feat: Use the new onHide/onShowCross provided by cozy-interapp

---

react/BottomSheet/BottomSheet.jsx
react/BottomSheet/helpers.js
react/BottomSheet/helpers.spec.js
react/NestedSelect/BottomSheet.jsx
react/NestedSelect/NestedSelect.md

pour voir la différence, il faut afficher un long contenu avec une toolbar. La fin du contenu était alors rogné.
demo: https://jf-cozy.github.io/cozy-ui/react/#!/BottomSheet

fix(BottomSheet): Content was not displayed  correctly with toolbar

---

react/Viewer/helpers.js

This attribute is already documented, but since it was not present here it did not appear in the Viewer.

Feat: Add missing bicNumber attribute 

---

react/MuiCozyTheme/makeOverrides.js

Due to some conflicting css rules we had to add !important
modifier to the bottom padding.
Due to layout issues in flex and missing css class if no title,
we now display empty DialogTitle so the Dialog displays as intended.
Removing the padding class since the empty title does the same job,
plus handling top padding in native

fix: Improve IllustrationDialog layout in native

---

react/MuiCozyTheme/helpers.js
react/MuiCozyTheme/makeOverrides.js

- Add default CSS var values for flagship CSS calculations (would break on desktop without it)
- Remove FluidContainer in IllustrationDialog (display icon below top bar)

fix: Handle vertical flow issues in IllustrationDialog

---

react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/__snapshots__/examples.spec.jsx.snap
react/providers/CozyTheme/index.jsx
stylus/utilities/display.styl

BREAKING CHANGE: `CozyTheme` use now `display: contents` by default so as not to change the style of the page, since it's just a wrapper that supports styles and nothing else. If this causes problems in the structure of your app, you can always revert to the previous state by setting `<CozyTheme ignoreItself={false}>`.

feat(CozyTheme): Add ignoreItself prop (add `u-dc` css class)

---

react/Viewer/Panel/PanelContent.jsx
react/Viewer/Readme.md
react/Viewer/components/InformationPanel.jsx
react/Viewer/styles.styl

and then its position is relative to the container, not to the page.
Cela corrige le comportement de l'info panel lorsque disableModal est true et qu'on souhaite donc contenir le viewer dans un wrapper, et non pas le faire poper fullscreen
demo: https://jf-cozy.github.io/cozy-ui/react/#/Viewer

fix(Viewer): InformationPanel doesn't use Drawer anymore

---

.travis.yml

Travis is configured to run on branches and PRs. The problem is that the CI is triggered at force push for all branches even if there is no associated PR, and for those with PRs the CI is therefore triggered twice.

chore: Don't run CI for branches if not master

---

react/utils/color.js
scripts/screenshots/screenshotReactStyleguide.js

Please ensure that variable `process.env.NODE_ENV` is well defined and set to `test` during your tests.

fix: The createNodeWithThemeCssVars must return null in test env

---

package.json
react/ActionsMenu/Actions/helpers.js
react/ActionsMenu/Actions/print.js
yarn.lock

Dans MesPapiers on souhaite pouvoir imprimer suite à une sélection de plusieurs fichiers. Pour se faire on fusionne les docs en un seul pdf, puis on se rabat sur la méthode précédente qui gérait déjà ce cas de fichier unique.

Print action can now deal with multiple docs

---

docs/components/TableOfContentsRenderer.jsx
react/BottomSheet/BottomSheet.jsx
react/BottomSheet/README.md
react/BottomSheet/helpers.js
react/BottomSheet/helpers.spec.js
react/CozyDialogs/Readme.md
react/Dialog/DialogEffects.spec.tsx
react/Dialog/DialogEffects.ts
react/deprecated/ActionMenu/ActionMenuEffects.ts
react/deprecated/Modal/ModalEffects.ts
react/hooks/useSetFlagshipUi/helpers.js
react/hooks/useSetFlagshipUi/useSetFlagshipUI.ts

On ajoute un bouton dans le menu principal qui permet d'activer un mode qui simule le rendu dans l'app flagship. Des fausses barres de status et de navigation apparaissent alors pour simuler le comportement sur mobile. Cela gère le mode immersif / contenu via un switch.
Quelque lien pour se rendre compte de la différence :
https://jf-cozy.github.io/cozy-ui/react/#/BottomSheet (le bottomsheet pop plus haut que la barre de navigation du bas)
https://jf-cozy.github.io/cozy-ui/react/#/CozyDialogs (en mode inverted les barres changent de couleur)

Extend flagship simulation from CozyDialogs to all cozy-ui

---

react/Viewer/Footer/BottomSheetContent.jsx
react/Viewer/Footer/FooterContent.jsx
react/Viewer/Panel/PanelContent.jsx
react/Viewer/Panel/getPanelBlocks.jsx
react/Viewer/Panel/getPanelBlocks.spec.jsx
react/Viewer/ViewerContainer.jsx
react/Viewer/ViewerInformationsWrapper.jsx

Dans une page public(suite à un partage), avec un fichier provenant d'un connecteur, le Viewer affiche toujours le bloc contenant les informations en lien avec ce dernier ([KonnectorBlock](https://github.com/cozy/cozy-libs/blob/0291ee72a7d9c019f926d06c814f272a7d95dff5/packages/cozy-harvest-lib/src/components/KonnectorBlock.jsx#L30)).
Mais dans ce contexte, nous ne souhaitons plus afficher ce bloc.
Cette PR fait en sorte de masquer ce bloc dans ce cas, car non pertinent et améliore l'UX.

feat(Viewer): Add isPublic prop for manage panel blocks displayed

---

package.json
react/ListItem/ExpandedAttributes/helpers.js
react/ListItem/ExpandedAttributes/helpers.spec.js
react/Viewer/Panel/ActionMenuWrapper.jsx
react/Viewer/Panel/getPanelBlocks.spec.jsx
yarn.lock

copy-text-to-clipboard use deprecated command.exec which does not work anymore on some desktop browser.
Copy does not work on Chrome Desktop : https://docs.cozy.io/cozy-ui/react/#!/Core/ListItem
Copy works on Chrome Desktop : https://zatteo.github.io/cozy-ui/react/#!/Core/ListItem

fix: Use navigator.clipboard instead of copy-text-to-clipboard

---

package.json
react/Filename/Readme.md
react/Filename/index.jsx
react/Filename/styles.styl
react/MidEllipsis/Readme.md
react/MidEllipsis/index.jsx
yarn.lock

Il y avait des problèmes de style avec ces composants qui faisait que le midEllipsis avait des espaces en trop, n'était pas placé correctement, ou était présent alors qu'il ne devait pas l'être. On a mis la feature derrière un flag car comme on fait un calcul sur la taille du parent, cela peut avoir une conséquence en terme de perf. Si le test est concluant, on supprimera le flag.
Après vérification dans Drive, le midEllipsis est assez peu utilisé finalement (dans la barre OnlyOffice et sur les chemins des dossiers dans la vue Récents). Ceci est plus pour MesPapiers.
Deux autres libs ont retenu mon attention https://www.npmjs.com/package/react-text-overflow-middle-ellipsis et https://www.npmjs.com/package/react-middle-truncate mais celle choisie a été mise à jour plus récemment, elle est …

Better MidEllipsis and Filename component

---

react/IntentDialogOpener/IntentDialogOpener.jsx
react/deprecated/IntentModal/IntentModal.jsx

This avoids triggering events for elements below the component, for example in Banks there are chips integrated into ListItems

[VO-201] fix: Stop propagation of event

---

react/Viewer/Panel/ActionMenuDesktop.jsx
react/Viewer/Panel/ActionMenuMobile.jsx

We no longer want the action to gray out the URL generation time, because this time is generally short and generates an unpleasant flicker.

feat(Viewer): Changing the behavior of the edit action

---

react/Viewer/Panel/getPanelBlocks.jsx

During this PR #2563, we should have passed the current file as an argument.
The test was therefore always true in non-public view

fix(Viewer): All files have konnector block

---

package.json
react/Filename/Readme.md
react/MidEllipsis/index.jsx
stylus/utilities/text.styl
yarn.lock

Ca ne fonctionnait pas sur Safari, et donc sur iOS, avec la nouvelle lib. J'ai essayé autant que possible d'utiliser le composant `MidEllipsis` dans Filename, et même d'utiliser d'autre lib mais il y a trop de cas particuliers (avec/sans extension/icone) pour que ça fonctionne simplement.
J'ai initialement trouvé une solution de construire à la main un "truncatedFilename" pour avoir un meilleur rendu dans Filename (c'est à ce code dont fait référence le premier commentaire de @Crash-- ), mais ce n'était pas concluant en terme de perf, ni en terme d'homogénéité selon tous les cas d'usages (différents browser, usage particulier dans Drive avec des class css supplémentaires etc.).
Pour info Filename n'est pas utilisé dans Drive, seul `MidEllipsis` l'est.
On a passé beaucoup de temps à …

Fix Filename midellipsis

---

react/MuiCozyTheme/overrides/makeLightNormalOverrides.js

The background contrasts with an opacity which reveals the content behind.

fix: The background of ListSubHeader should use the default background

---

react/Field/styles.styl
stylus/components/button.styl
stylus/components/forms.styl
stylus/generic/animations.styl
stylus/tools/mixins.styl
stylus/utilities/text.styl

Comme les fichiers stylus dans le dossier `utilities` comporte des mixins/var ET les créations des classes css globales (les classes `.u-`), le fait d'importer ces fichiers dans d'autres fichiers stylus duplique les créations des classes utilitaires.
Pour `hide` et `ellipsis` au lieu d'importer la variable depuis le fichier respectif qui contient donc la variable ET la création de la classe utilitaire, on en fait des mixins qui sont alors elles utilisées en remplacement, afin de NE PAS importer le fichier de création des classes utilitaires.
Ceci corrige donc la duplication des classes utilitaires dans le cas où on importe directement c'est fichier stylus dans l'app, ces classes utilitaires se retrouvaient alors dans le css buildé de l'app, entrant donc en conflit (en cas de différence de …

fix(Styles): Remove import of stylus file with global class creation in it

---

react/ListItem/ExpandedAttributes/helpers.js
react/ListItem/locales/en.json
react/ListItem/locales/fr.json
react/Viewer/helpers.js
react/Viewer/locales/en.json
react/Viewer/locales/fr.json

On souhaite pouvoir afficher le nom de l'employeur dans les infos du Viewer.  Préalablement on avait mise sur `contentAuthor` pour stocker cette info, mais finalement il s'avère qu'on y stocke plutôt la source de récupération du doc lorsqu'on le récupère va un connecteur, ce qui ne convient pas au besoin. On a donc créé une nouvelle metadata `employerName` pour ça.
Côté expanded attributes on ne souhaite plus afficher cette info dans cet élément.

Replace `contentAuthor` by `employerName`

---

react/FileImageLoader/index.jsx
react/Viewer/ViewersByFile/PdfMobileViewer.jsx
react/Viewer/ViewersByFile/PdfMobileViewer.spec.jsx
react/Viewer/docs/DemoProvider.jsx

The old route will be removed, we should use the new one.
See https://github.com/cozy/cozy-stack/pull/4344/files

fix: Use /medium for PDF thumbnails

---

react/Viewer/Footer/DownloadButton.jsx
react/Viewer/Footer/FooterContent.jsx
react/Viewer/Footer/ForwardButton.jsx
react/Viewer/Footer/ForwardOrDownloadButton.jsx
react/Viewer/Footer/Sharing.jsx
react/Viewer/Footer/helpers.js
react/Viewer/NoViewer/DownloadButton.jsx
react/Viewer/Panel/QualificationListItemInformation.spec.jsx
react/Viewer/Readme.md
react/Viewer/Viewer.jsx
react/Viewer/ViewerContainer.jsx
react/Viewer/ViewersByFile/PdfMobileViewer.spec.jsx
react/Viewer/components/PrintButton.jsx
react/Viewer/components/Toolbar.jsx
react/Viewer/components/ToolbarButtons.jsx
react/Viewer/components/ViewerByFile.jsx
react/Viewer/components/ViewerControls.jsx
react/Viewer/components/styles.styl
react/Viewer/docs/DemoProvider.jsx
react/Viewer/hoc/withViewerLocales.jsx
react/Viewer/index.jsx
react/Viewer/locales/index.js
react/providers/I18n/index.jsx
react/providers/I18n/translation.jsx

Le besoin initial est d'ajouter un bouton d'impression dans la toolbar du Viewer (en desktop), de modifier le bouton "télécharger" et de pouvoir ajouter depuis l'app des boutons dans la toolbar. On change également le style des boutons dans le footer (le pendant mobile de la toolbar desktop).
Au passage on modifie l'approche concernant les locales. Initialement on importait via un HOC la prop `t` avec un polyglot qui ne contenait que les locales de cozy-ui dans certains composants afin d'avoir la trad de cozy-ui. Sauf que ça ne fonctionne pas si ce composant est appelé également dans l'app en direct. On modifie donc l'approche ici en utilisant un hook plus haut niveau, appelé dans ViewerContainer qui est le composant le plus haut niveau appelable dans l'app pour instancier le Viewer. Ce …

Viewer: modify toolbar/footer buttons

---

react/Viewer/ViewersByFile/PdfMobileViewer.jsx

On mobile, the events must not be on the entire page, otherwise the back arrow also triggers the download for example.

fix(Viewer): Events must be limited on the image

---

react/ActionsMenu/Actions/helpers.js
react/ActionsMenu/ActionsItems.jsx
react/ActionsMenu/Readme.md
react/Viewer/Readme.md
react/Viewer/components/PrintButton.jsx

Le but de cette PR est de montrer qu'il est possible d'utiliser des actions indépendamment du rendu déjà intégrée à l'action dans l'attribut "Component".
Grâce à `makeActions` pour la création puis `ActionsItems` pour le rendu, on peut alors utiliser une action définit comme telle (ici l'action Print) et override le rendu attendu dans l'attribut Component.
L'idée serait d'avoir une approche harmonisée pour ce sujet, donc toujours passer par `makeActions` puis soit un composant clé en main comme ActionsMenu, soit ActionsItems.

Viewer: Use ActionsItems in PrintButton

---

react/Viewer/Readme.md
react/Viewer/ViewerContainer.jsx

In commit 97f28ff, WebviewIntentProvider has been added to ViewerContainer, in order to call intent's methods in the container children.
This is not needed because we expect the webapp to implemented on the root level.
Also, this would produce a bug because WebviewIntentProvider is not mean to be declared twice in a same webapp.
When doing so, the child WebviewIntentProvider would overwrite the parent one on the flagship app side. So when opening the Viewer, the parent provider would stop working.

fix(Viewer): Remove WebviewIntentProvider

---

.travis.yml

Suite à notre changement https://github.com/cozy/cozy-ui/pull/2552 les branches autres que master ne sont plus buildé, et donc Argos n'est plus capable de s'exécuter sur ces branches. Il ne s'exécute alors que sur master lors du build de la PR.
Hors la branche master est la branche de référence pour les screenshots. Et depuis une modification côté Argos il n'est plus possible de valider les screenshot sur la branche de référence.
Après investigation côté Argos lui-même https://app.argos-ci.com/argos-ci/argos il s'avère que les screenshots sont bien comparés entre la branche de la PR et la branche de référence.
Notre configuration est donc mauvaise.
Cette PR revert donc la modification `branches only master`, ainsi les screenshots sont bien comparés entre la branche de la PR et la branche …

fix: Argos screenshots

---

react/Avatar/helpers.js
react/Avatar/index.jsx
react/SquareAppIcon/index.jsx

We need to implement an Avatar like component with Angular for the Cozy Pass extension. We can not reuse the Avatar component from cozy-ui because it is a React component. But we can reuse this nameToColor method to stay as close as we can to cozy-ui.

refactor(Avatar): Move nameToColor in a new helpers file

---

stylus/objects/sidebar.styl

This will handle cases in desktop where the
sidebar was hiding its own content because it was too tall
and not letting the user scroll inside it.
This should have no effect on the mobile sidebar
since it has a fixed height

fix: Add vertical scroll to sidebar when needed (VO-628)

---

react/FilePicker/queries.js

It is not to be displayed in the filepicker, just like the trash dir

feat: Exclude shared drives dir from filepicker (VO-647)

---

react/Buttons/Readme.md

MUI documentation does not describe default button's `type`, nor explain that is it possible to set classic HTML attributes, so it is easy to forget applying the correct button type when inside of a form
This is what happened on a previous PR when migrating from old `react/deprecated/Button` to new `react/Buttons` as those components have opposite default behaviors
Related PR: cozy/cozy-settings#674

chore: Describe default type attribute in Buttons documentation

---

react/Menu/Readme.md
react/MuiCozyTheme/overrides/makeLightNormalOverrides.js

Un MenuItem peut être utilisé dans différents contextes, notamment dans un TextField select qui peut avoir une largeur très grande contrairement à un Menu. C'est donc plus pertinent de déplacer le maxWidth du MenuItem au Menu, pour permettre à un TextField select d'avoir la largeur qu'il veut, mais pour autant avoir un Menu qui ne dépasse pas les 320px.

fix(MenuItem): Remove maxWidth and add it on Menu instead

---

react/MidEllipsis/index.jsx

On avait initialement rajouté les trim sur les string pour limiter les espaces inutiles entre les 2 blocs du midellipsis (une string midellipsée est en fait 2 strings avec un `...` au milieu). Sauf qu'en fait la séparation visuelle est gérée en css donc les probabilités pour que la séparation soit parfaitement entre les deux blocs (au niveau de la séparation des string) est quasi nulle.
De plus pour une string qui n'a pas besoin d'être midellispée, la séparation en 2 blocs est quand même faite. Or s'il y a un espace entre 2 mots, il faut le conserver. Avoir un trim supprime cet espace et concatène donc les 2 strings. C'est cet effet qu'on corrige ici.

fix(MidEllipsis): It should not trim strings

---

react/Layout/Layout.md
react/NestedSelect/NestedSelect.jsx
react/NestedSelect/NestedSelect.md
react/NestedSelect/styles.styl

The search bar in Desktop mode does not overlap the closing cross of the modal
In agreement with @joel-costa 
Demo: https://merkur39.github.io/cozy-ui/react/#!/Extra/NestedSelect

fix(NestedSelect): Search bar on desktop mode

---

docs/README.md
react/SquareAppIcon/Readme.md
react/SquareAppIcon/__snapshots__/SquareAppIcon.spec.js.snap
react/SquareAppIcon/index.jsx

Demo here : https://acezard.github.io/cozy-ui/react/#!/SquareAppIcon
Display mode is either "compact" (current display) or "detailed" (new display)
For now this component is intended for new `cozy-home` features but will probably be used at other places
**Also added a new script to upload demo in a single liner, refer second commit**

feat: Add display mode for SquareAppIcon (VO-719)

---

react/ListItem/Readme.md

Calling the date function generates unnecessary changes in Argos.

docs(ListItem): Use date string instead function

---

react/AppSections/__snapshots__/index.spec.jsx.snap
react/AppSections/__snapshots__/search.spec.js.snap
react/AppSections/_mockApps.js
react/AppSections/categories.spec.js
react/AppSections/locales/en.json
react/AppSections/locales/fr.json
react/mocks/apps.js

The telecom category is still used because konnector installed needs to run to updated there manifest.
This reverts a part of commit d5d45988929961fd076039cdf4bc60b12817bac5.

[VO-758] feat(AppsSection): Change only ISP wording

---

react/ContactsListModal/queries.js

When dealing with thousands of contacts, the default 100 pagination will make dozens of requests, thus making it quite slow.

feat: Improve contacts list performances

---

react/providers/CozyTheme/CozyThemeWithQuery.jsx
react/providers/CozyTheme/Readme.md
react/providers/CozyTheme/index.jsx
react/providers/CozyTheme/queries.js

BREAKING CHANGE: To use `<CozyTheme>` properly, you must have permission in your app to get `io.cozy.settings` documents. The experience would be even better with realtime on this doctypes.

feat(CozyTheme): Use `io.cozy.settings` to determine default type

---

react/ActionsMenu/Actions/print.js

We need to write window.open in a setTimeout because Safari does not allow window.open in an async function.
It was an issue only in the print action in the mobile viewer.

fix: Print in Safari

---

react/BottomSheet/BottomSheet.jsx
react/Dialog/DialogEffects.spec.tsx
react/Dialog/DialogEffects.ts
react/Sidebar/index.jsx
react/Viewer/ViewerInformationsWrapper.jsx
react/deprecated/ActionMenu/ActionMenuEffects.ts
react/deprecated/Modal/ModalEffects.ts
react/providers/CozyTheme/index.jsx

**Fix a bug related to the overlay of the status bar when opening the BottomSheet (not related to dark mode)**
**Set the good colors for the status bar and bottom baar in dark mode** 
It is the front end, and most of the time cozy-ui, that is responsible of setting the good colors for the status bar and bottom bar.
_For example for the BottomSheet_
- when opening it  
- add an overlay to the status bar
- set the status bar icon and text in light
- when closing it 
- remove the overlay 
- set the status bar icon and text in dark ==> in dark mode we want light here
In the second commit of this PR we update every call to setFlagshipUI to take this into account.

Dark mode for flagship app

---

docs/components/IntentExample.jsx
react/IntentDialogOpener/IntentDialogOpener.md
react/IntentHeader/styles.styl
react/IntentIframe/Readme.md
react/IntentIframe/styles.styl
react/Layout/Layout.md
react/deprecated/Modal/index.jsx
react/providers/CozyTheme/index.jsx
stylus/components/modals.styl
stylus/elements/defaults.styl
stylus/objects/layouts.styl

J'ai testé le correctif sur le layout en mobile avec Drive, MesPapiers, Contacts et Store.
Le correctif sur Modal est dû au fait qu'on s'en sert encore (à tort car deprecated depuis longtemps) pour les Intent
Pour la gestion du type/variant du thème, si on manipule le body ou une balise très haute comme ça, on devrait après réflexion avoir 2 composants, ou alors un prop pour distinguer l'usage du type et l'usage du variant. Car le type ne se définit qu'une fois pour toute (pour l'app et pour l'intent), alors que le variant peut être utilisé à l'intérieur de l'app. Si c'est un seul composant qui fait les deux on devrait avoir une prop `<CozyTheme master={true}>` par exemple qu'on utiliserait uniquement dans les providers de l'app/intent et qui s'occuperait de gérer le type du thème.
demo: …

Fix colors for intents and height layout for mobile

---

react/MuiCozyTheme/overrides/makeLightNormalOverrides.js

MUI adds a `-webkit-overflow-scrolling` property to manage scrolling on iOS on the content. This is act as a counter-effect to `overflow-y: visible` of the parent to display the icon beyond the modal.

[VO-889] fix(PermissionDialog): Show overflow icon on iOS

---

jest.config.js
react/Viewer/components/ViewerControls.jsx
react/Viewer/components/ViewerControls.spec.jsx

In the Viewer, we define a variable which can be undefined inside the ViewerControls children. When the ViewerControls matches its children to find out which display it checks for the type that crashed the application because it doesn't exist on undefined.

[VO-903] fix(ViewerControls): children can contain undefined values

---

stylus/objects/layouts.styl

and so to be able to override it with `:root`
utile pour les app qui n'ont pas la nav bar, comme Settings, et donc qui pourrait alors mettre la valeur à `0` pour éviter un espace trop important
relatif au commit https://github.com/cozy/cozy-ui/pull/2661/commits/2bc7e5df1bbb88fbfa5a20f7bf497f9d9d6e9d69 qui fait la modification initiale

feat(Layout): Use var css instead of stylus var to set Main min-height on mobile

---

react/AppSections/locales/en.json
react/AppSections/locales/fr.json

Replace "&" char by their equivalent in each language to uniformize display in store

[SCR-785] typo: Replace commercial '&' by their equivalents

---

react/Buttons/Readme.md
react/Buttons/index.jsx
react/__snapshots__/examples.spec.jsx.snap

demo: https://jf-cozy.github.io/cozy-ui/react/#/Buttons (see Colors section)

feat(Buttons): Support now `default, inherit, secondary` color for Text variant

---

react/AppIcon/index.jsx
react/AppSections/Sections.jsx
react/AppSections/__snapshots__/index.spec.jsx.snap
react/AppSections/categories.js
react/AppSections/categories.spec.js
react/AppSections/components/__snapshots__/AppsSection.spec.jsx.snap
react/AppSections/constants.js
react/AppSections/generateI18nConfig.ts
react/AppSections/helpers.js
react/AppSections/locales/en.json
react/AppSections/locales/fr.json
react/AppTile/AppTile.spec.jsx
react/AppTile/index.jsx
react/AppTile/locales/en.json
react/AppTile/locales/fr.json
react/ShortcutTile/index.tsx
react/types.d.ts

Allow shortcuts doctype to be used in AppsSections in cozy-store (previously only konnectors and apps were set up).

feat: handle shortcuts in appsections VO-777

---

.travis.yml

`skip ci` seems to be ignored...
Depuis un certain moment (non totalement défini) Travis crée un build après la publication d'un tag, sur le commit associé, malgré la présence du `skip ci` sur ce commit 🤷‍♂️ 
On rajoute donc ici une règle pour ignorer ce cas là.

chore: Ignore branches with tag

---

react/SearchBar/index.jsx

SearchBar small improvements

---

react/ShortcutTile/index.tsx
react/Typography/index.jsx

The Storybook for Harvest could not resolve cozy-ui/react/ as it isn't present in the transpiled version. To resolve this, I updated the import to use relative paths consistently with the rest of the codebase. Additionally, as ShortcutTile is a TypeScript file, I needed typed versions of all components it relies on, so I added JSDoc to Typography to ensure compatibility.

fix: Import resolution problem inside Storybook of cozy-harvest

---

react/SquareAppIcon/Readme.md
react/SquareAppIcon/index.jsx

By default, the badges are displayed for the shortcut variant, but in some cases you want to be able to hide them so that they look more like applications
**Demo :** https://cballevre.github.io/cozy-ui/react/#!/Extra/SquareAppIcon

[VO-1194] feat(SquareAppIcon): Hide shortcut badges for a more app-like feel

---

.bundlemonrc
.github/workflows/deploy.yml
package.json
react/BarContextProvider/index.spec.jsx
react/DateMonthPicker/index.jsx
react/FilePicker/FilePickerBodyItem.jsx
react/ListItem/ListItemFile/SecondaryText.jsx
react/providers/I18n/format.jsx
react/providers/I18n/index.spec.jsx
yarn.lock

See breaking changes [here](https://github.com/date-fns/date-fns/blob/main/CHANGELOG.md#200---2019-08-20)

feat: Upgrade date-fns to 2.30.0

---

react/providers/I18n/format.jsx
react/providers/I18n/format.spec.jsx

Following version [115.0.0](https://github.com/cozy/cozy-ui/releases/tag/v115.0.0), the format of 3 locales has changed:
- `en -> en-US`
- `zh_cn -> zh-CN`
- `zh_tw -> zh-TW`
More details here: https://github.com/date-fns/date-fns/blob/main/CHANGELOG.md#200---2019-08-20
The constant `DEFAULT_LANG=“en”` is not changed because it is used by Polyglot, which must not change. This is directly related to the folder names in our apps..

fix: Ensure use correct format locales

---

react/providers/I18n/format.jsx

Since version 115.0.0, the new version of `date-fns` throws an error if no date has passed.
In order to maintain the same behavior on our apps, we make sure we don't throw any errors in the apps.

fix(initFormat): Ensure do not crash if no date is passed

---

react/ActionsBar/Readme.md

Il semblerait que quelque chose ait changé côté argos car tous les screenshots sont détectés comme ayant changé, alors qu'aucune modification n'a été apportée. Cette PR fait un changement mineur afin de revalider tous les screenshots et de repartir sur une base saine pour les prochaines PR.

chore: Trigger Argos to verify false positive 

---

package.json
react/ActionsMenu/Readme.md

pdf-lib adds 381KB to an app bundle and is rarely used so let's set it as a peer dep.
BREAKING CHANGE: If you use print action, please add pdf-lib as a dep in your app because it is now a peerDep in cozy-ui

feat: Set pdf-lib as a peerDep

---

package.json
react/ActionsMenu/Readme.md

This reverts commit 15604af04a8f68b77d9ae4c42612e81f04b4f31c.
Setting pdf-lib as a peerDep makes bundles errors when building even if do not need pdf-lib. I need to understand better how it works to propose a better solution.
BREAKING CHANGE: Remove pdf-lib as a dep in your app if you added it in cozy-ui 120.0.0

feat: Revert "feat: Set pdf-lib as a peerDep"

---

react/SquareAppIcon/index.jsx
react/SquareAppIcon/styles_twake.styl

See https://zatteo.github.io/cozy-ui/react/#/Extra/SquareAppIcon

feat(SquareAppIcon): Dark mode in Twake theme

---

react/helpers/isTwakeTheme.js

We decided to remove Cozy theme completely and relies only on Twake theme. So we have to remove `isTwakeTheme` condition everywhere in the Cozy codebase. To be able to do that by taking the time to do it well, we simply return `true` to begin with.

feat: Update isTwakeTheme condition to force it to `true`

---

docs/styleguide.config.js

The main goal is this PR https://github.com/cozy/cozy-ui/pull/2791 but because of font modification, Argos is triggered everywhere.
Here we just modify the documentation font (not the font used in components), update Argos, and then we will see better on the other PR if we broke something or not.
In the documentation we use now sans-serif to be agnostic and so to avoid triggering Argos if we change font again (it will still be sans-serif in the doc).

feat: Change default font from Lato to Inter

---

package.json

Follow our convention about internal peer deps.
Will allow apps to have only version of cozy-device-helper because here we ask a 2.x version whereas other libs ask >= 2.x (so 3.x as of now).
No change needed on apps.

fix: Allow cozy-device-helper >= 2.0.0

---

react/ActionsMenu/ActionsMenuWrapper.jsx

With previous implementation, useActionMenuEffects() would call SetFlagshipUI even if the menu is not open
This would result with incorrect top bar color in Flagship app
By moving the hook call in a custom component under the `open` condition, we ensure the hook will register/unregister correctly when the ActionsMenu opens or closes

fix: Don't register Flagship UI on ActionsMenu until opened

---

react/ActionsMenu/index.jsx

By default the menu stays open when clicking right mouse button outside of it. It doesn't anymore but if you don't want to close the menu on right-click you have to set `autoCloseOnContextMenu` to `false`.
We need this because now we have right-click menu on apps (Drive) and we don't want to have too many menus open at the same time.

feat(ActionsMenu): Add autoclose on context menu event

---

react/ActionsMenu/Actions/viewInDrive.js

[cozy/cozy-drive#3436](https://github.com/cozy/cozy-drive/pull/3436)
Update action `viewInDrive` to get `driveId` from `docs` to open files in shared drive.

feat: Adjust view in drive to adapt shared drive :sparkles:

---

package.json

When installing cozy-ui with Yarn 4, we get the following errors :
command not found: if
command not found: then
command not found: fi
Fixing it following this advice https://stackoverflow.com/questions/70805712/command-not-found-if-when-running-package-json-script-with-yarn-v3-berry

fix: Postinstall hook not working using Yarn 4

---

docs/styleguide.config.js
react/providers/ConfirmDialog/Readme.md
react/providers/ConfirmDialog/index.jsx

We don't use routes for confirm modal, so we need to create simple components in app to show them. However it's not possible easily to trigger them in pure js code without creating components. It's a bit fastidious also to create many of theme everywhere we want them.
With a provider, I think it will be easier to deal with these cases.
demo: https://jf-cozy.github.io/cozy-ui/react/#/Providers/ConfirmDialogProvider

feat(Providers): Add ConfirmDialog providers

---

docs/README.md
react/DatePicker/Readme.md

We are thinking about maybe splitting cozy-ui somehow to lower deep depencies and use components in different technical context... the first step is to list dependencies and usage.

docs: Add list of package usage

---

react/Contacts/AddModal/ContactForm/FieldInput.jsx
react/Contacts/AddModal/ContactForm/FieldInputAccordion.jsx
react/Contacts/AddModal/ContactForm/FieldInputArray.jsx
react/Contacts/AddModal/ContactForm/FieldInputLayout.jsx
react/Contacts/AddModal/ContactForm/contactToFormValues.js
react/Contacts/AddModal/ContactForm/fieldsConfig.jsx
react/Contacts/AddModal/ContactForm/index.jsx
react/Contacts/AddModal/ContactForm/locales/en.json
react/Contacts/AddModal/ContactForm/locales/fr.json
react/Contacts/AddModal/types.js

We want to hide some "not so important" fields in the contact form.
One way is to add a sort of accordion in the main field (like Company) to show its subfields (like Job Title).
Other way is we added a new button at the bottom of the form to show secondary fields (Twake URL, Related contacts ...).
Small subtlety: the hidden fields are still in the DOM, we just not displaying them, to be more compliant with old way.
demo: https://jf-cozy.github.io/cozy-ui/react/#/Contacts/AddModal
**behavior validated by Swann** ✅

ContactForm: Hide some fields with 2 different ways
