stylus/index.js
This PR brings an `embed` method that can be called to, well… embed assets in final CSS :). It uses and extended lookup path, so it first tries to load the assets relatively to the cozy-ui's _assets_ folder and then fallback to a relative way from the CSS.
You can pass it `utf8` as a second arg, so it'll uses a utf-8 encoding rather than a base64 (useful with SVG) for embeding.
=> Use cozy-ui assets in project

stylus/ui-base/icons.styl
I guess this is a typo and it seems to fix the error on `yarn run build` (which I did not get with `yarn run watch`, cannot know why) with an error like below (@kosssi faced earlier):
```
ERROR in ./~/css-loader?importLoaders=1&modules!./~/postcss-loader!./~/stylus-loader!./src/styles/table.styl
Module build failed: TypeError: /Users/enguerran/Development/Cozy/cozy-files-v3/src/styles/table.styl:82:1
78| 
79|     td.fil-content-file
80|       left-padded(61px)
81|       background-position em(16px) center
82| 
-------^
Path must be a string. Received undefined
```
PS : I do not know stylus' syntax, so I may be wrong.
See https://github.com/cozy/cozy-ui/commit/43e9580d264aca15148cab95f5b51b867ba4643a and https://github.com/cozy/cozy-ui/commit/be098ea574ca07888a2a40688290d2b9cc924d12 for …
=> Fix 'Path must be a string. Received undefined' embed ⟹ embedurl

stylus/cozy-ui/defaults.styl, stylus/ui-app/alerts.styl, stylus/ui-base/palette.styl, stylus/ui-components/button.styl
* __Class changes__: I didn't noticed but the previous class `.coz-alerter--hidden` was not compatible with a way to stack alerts (the hiding system worked by 'hiding' the alerter instead of just the alert). So I changed to use `.coz-alert--hidden` and `.coz-overlay--hidden` instead of `.coz-alerter--hidden`.
It's now compatible with a generic alerts system introduced in `cozy-settings` in this [PR](https://github.com/cozy/cozy-settings/pull/2/files#diff-6ff124af85549596cf89cf814b4de476)
* Improve overlay fadeout transition by using `visibility` property
* Add buttons classes for `info` (grey) and `success` (green) alert types.
=> Better alerts

stylus/cozy-ui/defaults.styl, stylus/ui-app/layouts.styl
This PR assumes that cozy apps always uses a `[role=application]` root element, and enforces it to be set to all viewport, rather than relying on the `$app-2panes` ruleset for this.
=> Set viewport to [role=application]

stylus/ui-app/forms.styl
At least Chrome applies a default blue outline when focusing an input; this outlines covers the border color we define on hover, focus and error, making them all look the same. 
This PR removes the outline on focus.
=> [fix] remove input css outline on focus

stylus/ui-components/modals.styl
- Adds the proper `pointer` cursor on the close button
- Use a natural width of 90% for small screens (gets bumped up via a media-query for bigger screens)
=> [fix] Modal improvements

react/Alerter/index.jsx
As discussed with @jsilvestre, this PR reduces the alerter's default duration to 3.5 seconds.
=> [fix] Reduced alerter delay

react/Alerter/index.styl, stylus/ui-app/layouts.styl, stylus/ui-components/alerts.styl
Update the alerter style to work on mobile.
The `coz-overlay` class is removed because it is never actually used.
Just a head's up, when this PR is merged I'm going to need a new published version of cozy-ui :-)
=> [feat] Added mobile styles for alerts

stylus/ui-components/popover.styl
Some elements in popover menus are not links, they are buttons, but they all look the same.
=> Labels in pop overs

CHANGELOG.md, stylus/ui-app/sidebar.styl, stylus/ui-components/selectionbar.styl
There was an issue on photo in mobile mode, a little gap between selection bar and side bar. This commit fixes the problem.
=> [fix] Arrange sidebar height and selectionbar bottom offset on mobile

stylus/ui-app/layouts.styl, stylus/ui-components/selectionbar.styl
⚠️ Do **NOT** merge now, wait for more reported bugs if needed ⚠️
=> Last minute fixes

react/Modal/index.jsx
To accept retro-compatibility, I had a `console.warn` for future deprecated props.
I also change two things:
- a new props: `withCross` as a bool to control the cross display
- the default value for props
=> feat: s/validate/primary/ & s/cancel/secondary/

CHANGELOG.md, stylus/ui-components/empty.styl
As there was a similar empty view on Files, Photos and now Settings apps, I added it as a shared component. 
You then just need to specify the path to the icon you want in a `background-image` on the `:before`  when you extend it in your app.
=> Add Empty component style

stylus/ui-components/modals.styl
Because of the `position: relative` on [role=contentinfo] the overlay wasn't taking all the viewport.
=> [fix] Overlay position to absolute to fixed

CHANGELOG.md, react/Toggle/index.jsx, react/Toggle/styles.styl
This PR adds a very simple toggle component, such as this:
It's designed to be an inline-element that scales with the `font-size` of it's parent. It binds to a simple js value and calls a callback whenever it changes.
=> Toggle component

stylus/ui-components/button.styl
Removed white background from "more button" as it is mostly used in parents with already a white background and can cause some inconvenience in some case
Basically, the more button doesn't have a white background by default anymore.
=> fix: remove white background-color from more button

stylus/ui-components/modals.styl
Media query rule was dumb, allowing us to only have a tiny modal not responsive to its content width.
This PR can have side effects on existing code in photos, please check that everything is still correct @enguerran <3
=> fix: modal width

react/Modal/Content.jsx
Using this component helped me to avoid repeating CSS code from `.coz-modal-content`.
For example I have not been able to retrieve padding properties from `.coz-modal-content` class, like this :
```jsx
<Modal>
<div className='{styles['coz-modal-content']}'>
My content
</div>
</Modal>
```
But now with this component I can do :
```jsx
<Modal>
<ModalContent>
My content
</ModalContent>
</Modal>
```
And I got the correct padding, it works like a charm.
I think we could do the same for example the modal sections used in cozy-photos.
After discussing with @GoOz, to make CozyUI usable, I think we need to aim a "two flavor Cozy UI" :
* One usable as a bootstrap CSS framework
* Another one based on React Components libraries, usable as it, based on the CSS framework part.
This PR tries to make a …
=> feat: add ModalContent component

react/Button.jsx
The production build breaks since React was not imported.
It is a bit problematic that the linter does not catch this problem.
If the linter cannot be configured to detect this, maybe the ProvidePlugin could be used ?
```
new webpack.ProvidePlugin({ React: 'preact-compat' })
```
=> fix(button): missing import

react/Modal/index.jsx
I though I already fix that, but it seems to be back.
`s/primary/regular/` to fit button's classes.
=> fix: there is no button.primary style :lipstick:

react/Modal/index.jsx
To be able to get styles['coz-modal-content'] from external components.
import Modal, { styles as modalStyles } from 'cozy-ui/react/Modal'
=> chore: export styles so that external components can use it

react/Modal/index.jsx, stylus/ui-components/modals.styl
Must be merged this afternoon.
Modal now stick to top when the viewport height is too tiny.
Requesting review from @GoOz at least for information.
I think that this PR should not trigger regression but I prefer to request reviews for the most people using the modal component as possible.
=> feat: Avoid overflowing for modal

CHANGELOG.md, assets/icons/ui/spinner-red.svg, stylus/ui-base/icons.styl, stylus/ui-components/button.styl
- Remove hover style on `[disabled]` and `[aria-disabled=true]` attribute for buttons: `$button--danger`, `$button--danger-outline` and `$button--highlight`
- Add a new icon variable: `$icon-spinner-red`
- Add white spinner on buttons `$button--danger` and `$button--highlight` with `[aria-busy=true]` attribute
- Add red spinner on `$button--danger-outline` with `[aria-busy=true]` attribute
=> Improve danger, danger-outline and hightline buttons

stylus/ui-components/modals.styl
The modal should not let its content overflow on its border-radius.
Before
After
=> fix: overflow on .coz-modal

CHANGELOG.md, react/Modal/Content.jsx, react/Modal/index.jsx, stylus/ui-components/modals.styl
The goal is to avoid default vertical paddings and let <ModalContent> component add them.
=> feat: remove vertical paddings in modal

stylus/ui-components/button.styl
I am currently working on the responsive version of the EDF app.
The height of the button is hard-coded here
https://github.com/cozy/cozy-ui/blob/632a397076b2794953b26e5918457f68db17d7f1/stylus/ui-components/button.styl#L19
I think we can rely on the text setting the height of the button.
Problem
Solution
=> fix: no hard-coded height for buttons

stylus/cozy-ui/defaults.styl, stylus/ui-base/fonts.styl
Fixes https://github.com/cozy/cozy-ui/issues/127
To be clear : when the font is bolder (and ugly), font-smoothing is not active.
=> feat: font smoothing 💄

package.json, react/I18n/format.js, react/I18n/index.jsx, react/I18n/translation.js, yarn.lock
With `cozy-ui/react/I18n` you can:
- import a I18n component : `import { I18n } from 'cozy-ui/react/I18n'`
- import default lang of cozy : `import { DEFAULT_LANG } from 'cozy-ui/react/I18n'` is `en`
- import translate décorator : `import { translate } from 'cozy-ui/react/I18n'`
A small example to use I18n component:
<I18n lang={lang} dictRequire={(lang) => require(`./locales/${lang}`)}>
With context:
const dictRequire = (lang, context) => context
? require(`./contexts/${context}/locales/${lang}`)
: require(`./locales/${lang}`)
...
<I18n context={context} lang={lang} dictRequire={dictRequire}>
With defaultLang:
<I18n defaultLang='fr' lang={lang} dictRequire={(lang) => require(`./locales/${lang}`)}>
In mobile context you can require directly polyglot with `import { _polyglot } from …
=> feat: Add I18n component :construction_worker:

react/SelectionBar/index.jsx, react/SelectionBar/styles.styl
This is the SelectionBar on Cozy Drive:
This is the SelectionBar on Cozy Drive mobile:
With `cozy-ui/react/SelectionBar` you can:
```javascript
// import component
import { SelectionBar } from 'cozy-ui/react/SelectionBar'
// use component
<SelectionBar t={t} selected={seleted} actions={actions} hideSelectionBar={hideSelectionBar} />
// define actions
const mapDispatchToProps = dispatch => ({
actions: {
download: {
action: selections => dispatch(downloadSelection(selections))
},
rename: {
action: selections => dispatch(startRenamingAsync(selections[0])),
displayCondition: selections => selections.length === 1
},
yourOwnAction: {
action: selections => dispatch(yourOwnAction(selections),
},
...
}
})
```
=> feat: Add SelectionBar component :shell:

stylus/ui-components/selectionbar.styl
The new cross is bigger than the old one so I forced its size when in background of the closing button in the selection bar.
=> fix: closing cross size in selection bar

stylus/ui-base/animations.styl
This PR fixes the keyframes name scope, so they aren't mangled in output CSS
=> CC-13 | Fix keyframes w/ css modules

CHANGELOG.md, react/Spinner/index.jsx, react/Spinner/styles.styl, stylus/ui-base/icons.styl
Added a spinner component because it's used everywhere but never in a same way.
Available options so far:
- colors (default blue)
- size (default 1em (16px))
- noMargin — removes the default left and right margins
- middle — center the whole component both vertically & horizontally like it's used when loading a content view
- loadingType — if you want a message below the Spinner (to be consistent with locales files obviously)
=> Add Spinner component

stylus/ui-components/forms.styl
After I click on select:
Before:
After:
=> feat: Add ▼ on focus select :art:

stylus/ui-components/alerts.styl
=> fix: alert position on mobile

stylus/ui-components/selectionbar.styl
We will need to deploy another _-betaXX_ version to let cozy-drive be able to share one file.
See https://github.com/cozy/cozy-drive/pull/322 and https://github.com/cozy/cozy-drive/pull/307
=> feat: enable share button on small devices

react/Modal/index.jsx, stylus/ui-components/modals.styl
@ptbrowne I tried to find another solution but I couldn't… :/
`overflow: hidden` is too restrictive for every use case. We'll have to find something else for PDF display.
=> fix: remove overflow hidden on modal

stylus/cozy-ui/defaults.styl
Fixing #161 
After : 
The Drive text staying fixed as we scroll is another bug.
=> fix: overflow error on html

react/I18n/index.jsx
You can get `lang` like this:
```jsx
class MyLang extends Component {
render ({lang}) {
return <div>{lang}</div>
}
}
export default translate()(MyLang)
```
=> feat: Add lang on translate :globe_with_meridians:

react/Modal/index.jsx, react/index.js
Makes things like : 
```jsx
import { Modal, Icon, Toggle } from 'cozy-ui/react' 
```
possible.
Added documentation also. Fixes https://github.com/cozy/cozy-ui/issues/163
=> Exports react components

react/Tabs/index.jsx
Sometimes you do not want the `<TabPanel />` active parameter to be controlled by the parent `<TabList />`. You want to force it.
Example in https://gitlab.cozycloud.cc/labs/cozy-bank/blob/master/src/ducks/settings/Settings.jsx
There are 3 tabs but only 1 panel since the children is passed from the routes so we know this panel will be the only one active
You want to provide an onClick handler. Example: you can change route after click on Tab
=> feat: ability for TabPanel to be forced activated

stylus/ui-components/button.styl
Made the default `.coz-btn` class more consistent with the other button variants so now we can use it on its own.
Basically it's a transparent button with white border & text, and I added behavior for some pseudo-classes (It was already transparent with white borders, I just added the text color).
I'm pretty sure none of all the Drive & Photos' buttons use only the default class but @y-lohse if you could take a quick look in case I missed something, that would be nice of you.
Same for @CPatchane & @ptbrowne, I (almost) never worked on platformers or gangstas projects, could you assure me that this PR won't break anything on your side?
=> fix: make default coz-btn more consistent with other button styles

loaders/strip-fill-loader.js, src/icons.jsx
- Use `svg-sprite-loader`
- Remove warning that nobody reads
=> Fix bug : cannot use loader if full name is not specified

stylus/ui-components/modals.styl
Modal on mobile are now vertically centered.
=> fix: mobile modal centered

react/Icon/index.jsx
`svg-sprite-loader` has a new export format.
=> fix: handle new svg-sprite-loader format

stylus/ui-app/nav.styl
Nav icons are now bigger on mobile and default text color is a little bit darker.
NB: From now on, the nav style in apps only need to specify the background-image (the icon path actually) on the `.coz-nav-link` element. The remaining properties are handled by Cozy-UI.
=> feat: new color & bigger icons on mobile

stylus/components/nav.styl
Nav items had a way too big min-width so I removed it along with useless padding and used flex-basis instead. Now you can have 5 items easily.
=> fix: nav layout on mobile with several items

package.json
Since it's necessary for I18n component usage, it's could be better to have it directly in cozy-ui.
It avoid to add it in the app without directly using it (confusing).
=> Make date-fns a dependency instead of a devDependency

stylus/components/nav.styl
So I used the MQ parameter `pointer:fine` and `not` which means that ~~every~~ **any** device with**out** an accurate pointing device, such as a mouse, trackpad or pen, should**n't** show an hover effect in this case.
Pretty efficient on iPad & other tablets.
=>  🚑  Fix the annoying double tap on nav links on iPad 

stylus/components/alerts.styl
The removal of `padded` mixin didn't go well. I missed two commas that invalidated `padding`'s syntax and so didn't apply any padding on alerts.
=> 🚑 Fix alert's padding

react/Spinner/Readme.md, react/Spinner/index.jsx, react/Spinner/styles.styl
Like described in the title, nothing fancy but just a fix: using another color than blue wasn't possible.
=> default Spinner color prevented other colors to be used

stylus/settings/breakpoints.styl
Thanks to the direction parameter we can change the direction of the media query if we want.
=> Add direction to breakpoints

react/I18n/index.jsx
On utilise pas le paramètre `locale` mais `lang`.
La cozy-bar arrive à faire le changement puisqu'il surcharge la fonction : https://github.com/cozy/cozy-bar/blob/7f60e84e75d21fe3313776aa6eb34eb95a8f9958/src/lib/I18n.js#L69
Vu que je suis entrain de supprimer cette surcharge, je me dis que c'est mieux d'avoir le fix dans le fichier que tout le monde utilise ;)
=> fix: locale is deprecated, parameter is lang

CHANGELOG.md, package.json, react/I18n/index.jsx
- Use babel-preset-cozy-app in .babelrc
- Modal improvements:
- Cannot scroll while Modal is opened
- Modal content is scrollable
- Buttons are correctly displayed on mobile
- Exports <ModalDescription/> and <ModalTitle /> for complex usages
- Modal title can be a node
- Default Spinner color prevented other colors to be used
- Visited links color
- Add direction parameter to breakpoints
- Add shortcut to access breakpoints helper
- Add back & forward icons
- Add `<ActionMenu />` component: see on [style guide](https://cozy.github.io/cozy-ui/react/#actionmenu)
- Add `<Overlay />` component: see on [style guide](https://cozy.github.io/cozy-ui/react/#overlay)
- Remove i18n duplicate file
=> 💎 Release v4.1.0

react/helpers/withBreakpoints.jsx, stylus/settings/breakpoints.styl
Il y avait 2 erreurs sur les breakpoints :
=> fix: Size is incoherent for breakpoints

stylus/components/modals.styl
=> fix: ligter margins for modal elements on mobile

CHANGELOG.md, package.json, react/Alerter/styles.styl, react/Button/styles.styl, react/Modal/styles.styl, stylus/components/button.styl, stylus/components/nav.styl, stylus/cozy-ui/build.styl, stylus/objects/sidebar.styl, stylus/utilities/display.styl, stylus/utilities/spaces.styl, stylus/utilities/text.styl
Replaced CSS classes with placeholders to gain performance.
Used a `build.styl` file to replace those missing classes (for the styleguide or people who wants vanilla CSS).
=> feat: use placeholders instead of .classes

react/Modal/Readme.md, react/Modal/index.jsx, react/helpers/migrateProps.jsx
=> Deprecate with cross

assets/icons/ui/icon-paperplane.svg
Fixes https://github.com/cozy/cozy-ui/issues/210
This icon is not used in our codebase since drive uses two custom paperplane icons : 
- drive/mobile/assets/icons/icon-paperplane-blue.svg
- drive/mobile/assets/icons/icon-paperplane-white.svg
In the future, I think drive should used colorless icons with the `Icon` components which lets you control the color of the icon without duplicating the file.
Occurences of paperplane
```bash
cozy $   rg paperplane
cozy-ui/src/icons.jsx
20:    'icon-paperplane',
cozy-ui/react/README.md
45:* paperplane
cozy-ui/stylus/components/button.styl
149:    background-image     embedurl('../assets/icons/ui/icon-paperplane.svg')
drive/src/drive/mobile/styles/feedback.styl
20:.c-btn--paperplane
21:    background-image …
```
=> Paperplane icon

react/ActionMenu/index.jsx, react/Menu/Readme.md, react/Menu/index.jsx, react/Menu/styles.styl, stylus/components/popover.styl
https://ptbrowne.github.io/cozy-ui/react/#menu
Prop name | Type | Default | Description
-- | -- | -- | --
position | string | left | Use position='right' to display the menu to the right
disabled | bool | false | Disables the menu
component | element | null | Specifies a custom component for the opener
onSelect | func | null | onClick handler for non disabled items
onSelectDisabled | func | null | onClick handler for disabled items
=> ✨ feat: add doc for <Menu /> and improvements

react/IntentOpener/IntentIframe.jsx, react/Modal/Readme.md, react/Modal/index.jsx
- Ability to pass `crossClassName` to `<Modal />` that gets applied to the `<ModalCross />`
- Add doc
fixing https://github.com/cozy/cozy-ui/issues/248
=> Modal cross classname

react/IntentOpener/IntentOpener.jsx, react/IntentOpener/styles.styl
~~⚠️ Wait for #249 to be merged~~ EDIT: merged ✅
Use the new crossClassName to apply a specific class to intent modals cross since they need to be displayed inside the collect bar.
Before
After
=> Intent modal cross

stylus/objects/layouts.styl
Removed `display: flex` on `.main` & `[role=contentinfo]` so the layout doesn't break on iOS 9-10 Safari.
=> fix: New layout on iOS 9-10

react/Overlay/index.jsx, stylus/elements/defaults.styl, stylus/objects/layouts.styl
Made sure that if the body is taller than the viewport, content behind the modal doesn't scroll and if the body is smaller then the modal isn't cropped by an overflow.
=> Overflow hidden only if body taller than viewport

stylus/settings/breakpoints.styl
[`large-screen`](https://cozy.github.io/cozy-ui/styleguide/section-settings.html#kssref-settings-breakpoints-large) media query mixin documentation was indicating that "large-screen('**min**') Refers to (**max**-width: 1201px)".
=> 📚 doc: fixed max instead of min in breakpoint stylus styleguide

stylus/objects/layouts.styl
What fatigue does to us…
The previous fix was good, just not at the right place, causing desktop view to scroll entirely when it obviously shouldn't.
=> fix: oops didn't code on the right selector

stylus/scripts/deprecate.js, stylus/tools/mixins.styl
The environment variable flag is `SHOW_STYLUS_DEPRECATION`. If you launch your app watcher with this variable, you'll have deprecation warnings.
```js
env SHOW_STYLUS_DEPRECATION=1 yarn watch:browser
```
=> Deprecate font size em

stylus/elements/defaults.styl
Without that import I had a very weird error : 
```
ERROR in ./src/styles/main.styl
Module build failed: ModuleBuildError: Module build failed: Unknown word (44:19)
42 | /**
43 |  * Correct the font size and margin on `h1` elements within `section` and
> 44 |  * `article` contexts in Chrome, Firefox, and Safari.
|                   ^
45 |  */
46 |
47 | h1 {
at runLoaders (/Users/pbrowne/code/cozy/bank/node_modules/webpack/lib/NormalModule.js:195:19)
at /Users/pbrowne/code/cozy/bank/node_modules/loader-runner/lib/LoaderRunner.js:364:11
at /Users/pbrowne/code/cozy/bank/node_modules/loader-runner/lib/LoaderRunner.js:230:18
at context.callback (/Users/pbrowne/code/cozy/bank/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
at Object.<anonymous> …
```
=> ✨ feat: add missing import

stylus/cozy-ui/build.styl, stylus/elements/defaults.styl
Padding utilities were extending margin placeholders.
=> Fix paddings

stylus/components/empty.styl
also transformed `em` in `rem`
=> fix: center empty view on tablet

stylus/objects/layouts.styl
On Firefox when a content with `white-space: nowrap`, even if its parent has `overflow:hidden`, is longer than its parent size, the flebox parent will push its width.
This fix prevents the growth of the flexbox parent.
=> fix: layout with long overflowed content

react/I18n/index.jsx, react/IntentOpener/IntentIframe.jsx, react/Menu/index.jsx, react/README.md, react/Tabs/index.jsx, react/Toggle/index.jsx, react/helpers/withBreakpoints.jsx
Since in our tests we use React (I plan to try to use preact with enzyme but wanted to have something running quick), we need to have cozy-ui compatible with React. We also advertise cozy-ui as a React library of components so it should anyway be compatible.
- `props` and `state` are not passed in the `render()` of `Component`s in React so we use `this.props`, `this.state`
- `context` properties are not passed to `CustomComponent` if you do not add a static property `contextTypes` to `CustomComponent`
=> React compatible

react/Modal/index.jsx, react/Modal/styles.styl
=> fix: modal rendering + buttons

react/SelectionBar/index.jsx, stylus/components/selectionbar.styl
Removed obsolete instructions due to the use of `<Icon />` component instead of CSS backgrounds
=> fix: selection bar's icons on mobile

react/Menu/Readme.md
That caused the Styleguide to break. Wasn't showing any source code anymore and this example of `<Menu />` didn't show up too.
=> fix: react styleguide was broken

stylus/components/alerts.styl
Don't know exactly why but on Photos, the `@media all and (min-width alert-width)` turned into `@media all and (min-width: 480em)` which is… bad. With rem, everything is in order.
=> fix: alerts MQ for desktop

stylus/components/table.styl, stylus/cozy-ui/build.styl
Refactoring of Table's styles.
Preview: https://gooz.github.io/cozy-ui/styleguide/section-components.html (at the end of the page) 
⚠️You just can't use table's styles by extending `$table` anymore, you'll have to explicitely declare every part of the table you need now. e.g. `$table-head`, `$table-row`, `$table-cell`, etc
There's still predefined classes in the build of UI though.
=> feat: refactoring Table styles

react/Sidebar/Readme.md
NavLink is no longer a component but merely a container for classes, this is why, only in the doc, we have to write it by hand.
=> 🐝 fix: repair nav doc

stylus/components/nav.styl
Forgot to take a look at the nav with `<Icon />` only on mobile… 😕
=> fix: nav mobile was misplaced with smaller icons

package.json, react/Modal/Readme.md, react/Modal/index.jsx, yarn.lock
Now, Modals are rendered exactly like other components and their DOM node is rendered inside the DOM node of the component rendering it. It can cause problems when the parent node has `overflow: hidden` or is `position: fixed`. We experienced this first hand in Bank when we rendered a Modal inside a Menu : the UI was broken since the Modal was rendered inside the Menu instead of being rendered inside the body.
Portals solve this problem in React world by transporting their children where you want (most of the time body).
You can see the result on https://ptbrowne.github.io/cozy-ui/react/#modal : 
Fixes #301
=> ✨ feat: Modal is rendered into a Portal

stylus/components/button.styl
Wide buttons on safari 10 had their text aligned to the left instead of being centered due to a wrong implementation of flexbox in the browser.
This trick fix this issue.
https://trello.com/c/EhgqPVkX
=> fix: center text in buttons on Safari 10

stylus/components/table.styl, stylus/cozy-ui/build.styl
Added a "divider"  style in table-like layout. (Used in Contacts, Bank and/or Health apps too I think)
Preview on the [KSS Styleguide](https://gooz.github.io/cozy-ui/styleguide/section-components.html) in the Table section.
Also, due to recent Design Styleguide changes, padding inside table cells has been decreased.
=> Add divider + lowered paddings between cells

react/Button/Readme.md, react/Button/index.jsx
…instead of a boolean
It was decided to just pass the target's value as the HTML spec allows and let HTML do its job.
=> feat: ButtonLink's target attribute becomes a string

react/IntentOpener/styles.styl
Cross button in Intent modal was misplaced.
=> fix: repositionned Intent modal cross button

react/Button/styles.styl
It turns out that, for some reasons I quite don't understand, sometimes CSS builders don't necessarily respect the classes order in the component's styles.
In this case, the base class is `.c-btn` is overwritten by modifier classes like `.c-btn--small` or `.c-btn--narrow`. In order to work properly, the basic class should be at the top of the file and modifier classes beneath it. As CSS builders don't always respect this, modifiers classes that appear before the basic class are overwritten by it. 
So I added a little more weight on modifer classes specificity in order to keep the overwrite effect even if the order is not respected.
=> fix: size overwrite classes have more specificity to avoid conflict

docs/styleguide.config.js, docs/template.html
I couldn't stand the lack of Lato font on Styleguidist anymore, so I added it. 
/me feels better 😀
=> fix: add Lato font on Styleguidist

stylus/components/button.styl
Padding-top and bottom was wrong on the normal size of a button but it wasn't really noticable because it's a button. It was clearly noticable on ButtonLink though.
So here's the fix.
Fix #343
=> fix: normal button padding was wrong

react/Button/index.jsx
[The conventional way](https://reactjs.org/docs/typechecking-with-proptypes.html) to declare propTypes is with a lower-case "p", and we have a linter complaining about this.
=> fix: lowercase propTypes

react/Textarea/Readme.md, react/Textarea/index.jsx
Just like `Input`, forwards any remaining props to the underlying element. useful for things like a `name` prop.
=> feat: forward props to textarea

stylus/settings/breakpoints.styl
Renamed breakpoints variables size to avoid some potential conflicts.
I had this use case. In the Stylus file of a component I had something like this:
```styl
@require '../settings/breakpoints'
large = 100rem
small = 50rem
.class
width large
+small-screen()
width small
```
Nothing's chocking so far, but my MQ `+small-screen` wasn't working as expected. It was working though BUT the function `small-screen()` uses a var inside `breakpoints.styl` to do the math, a var named `small`. As it turned out, in my use case, the function was using the `small` var from the component's stylus file, not the breakpoints' one.
So I renamed the one in `breakpoints.styl` to avoid this, It's not perfect but I don't know what else to do. If you have better ideas, I'm all ears.
=> fix: renamed BP sizes variable to avoid potential conflicts

CHANGELOG.md, react/Button/Readme.md, react/Button/index.jsx, stylus/components/button.styl
In order to have more control over the rendering of the basic usage of Button, I added two props `icon` and `label`. That way you can easily have a button with single text, icon+text or single icon.
You don't have to build those kind of buttons by yourself by sending the component the children node you need. 
That being said, you still can choose to send node children but you may have to add your own style if it doesn't render as you wish.
=> feat: Deprecated children and added label & icon in Button

stylus/settings/palette.styl
`.u--paleGrey`, `.u--dodgerBlue` etc... are now available.
I put !important since they are utility classes and we will always want this behavior.
```css
....
.u--paleGrey {
color: #f5f6f7 !important;
}
.u--silver {
color: #d6d8da !important;
}
.u--coolGrey {
color: #95999d !important;
}
.u--slateGrey {
color: #5d6165 !important;
}
....
```
fixes #353
=>  Add utility classes for colors

react/Modal/index.jsx
The `required` property does not exist on the proptypes. `isRequired` must
be used'
=> 🐝 fix: fix is required

react/Modal/index.jsx
The latest release notes say `ModalTitle` is deprecated, but actually it was not exported at all so the modals that use `ModalTitle` are broken.
=> fix: export modal title

react/Button/index.jsx
TIL: this test is useless, and even harmful, since preact creates a `<undefined>` element around the children.
[Here's](https://codesandbox.io/s/pjvwxpwjzx) a codesandbox with a demo, make sure you inspect the renderer page to see the extra element (highlight through css).
=> fix: button children

react/Button/index.jsx
Unfortunate side-effect of the fix from earlier : if a button has no icon, the `icon` variable is `null` and reading `icon.id` produces a type error and crashes the whole thing :(
=> fix: svg symbol detection

react/Modal/Readme.md, react/Modal/index.jsx, stylus/components/modals.styl
But still works if `children` is just a string.
Fix: #387
=> modalHeader have h2 only if title props defined

react/Modal/Readme.md, react/Modal/index.jsx, react/Modal/styles.styl, stylus/components/modals.styl
=> feat: Center modal on mobile & add fullscreen option on mobile

react/Input/Readme.md, react/Input/index.jsx, react/Input/styles.styl, react/Textarea/Readme.md, react/Textarea/index.jsx, react/Textarea/styles.styl, stylus/components/forms.styl, stylus/cozy-ui/build.styl
Added `size` prop on inputs & textareas with `tiny` & `medium` options.
Inputs & textareas are large by default but can be smaller now.
=> feat: Add input & textarea different sizes

stylus/objects/layouts.styl
Background gradient in elastic layout was buggy on Safari.
Apparently, for Safari, `rgba(0, 0, 0, 0)` ≠ transparent… 
Thankfully, it works better with `rgba(255, 255, 255, 0)` 🎉
=> fix: elastic layout background on Safari

react/Button/index.jsx, react/Hero/index.jsx, react/Icon/Readme.md, react/Textarea/index.jsx
=> fix: some underlying errors & warnings

stylus/components/forms.styl
As discussed with the designers, checkbox and radio should have the same size.
=> fix: input radio size

CHANGELOG.md, react/Button/Readme.md, react/Button/index.jsx
This PR adds a `disabled` attribute for `<ButtonLink />`. In a few case we may display a `<ButtonLink />` having an `href` fetched asynchronously. Or an `href` with no value. In those case, the `<ButtonLink />` could be displayed as disabled an the `onClick` handled ignored.
Example : in [Cozy-Collect](http://github.com/cozy/cozy-collect/) we are fetching the cozy-store URL. In some environment this app may not be installed, so the `<ButtonLink />` is disabled.
=> feat: add disabled attribute for ButtonLink ✨

react/Input/index.jsx
React defaults undefined to "" automatically.
Additionally, setting id to "" would cause errors in the styleguide.
=> 🐝 fix: remove default props that are defaulted by react

loaders/strip-fill-loader.js
Some icons (such as `rename`) were not properly stripped of their fill color because they use lower-case color values.
=> fix: fill strip loader lowercase

react/Media/Media.styl
This just add `overflow: hidden` in the `Bd` component.
In general, since this component must constraint its content's width, I think it should hide what's overflowing.
More particulary, in banks we use the `ListItemText` component inside a `Bd` component. Since the `ListItemText` has `white-space: nowrap`, it expands to fit the wider line of text is contains. But in that case, if `Bd` doesn't have `overflow: hidden`, its content may overflow : 
You may think this is a particular case we have here. But on the contrary I think it's very generic : `Bd` must fill the available space, and what it contains must never overflow.
=> feat: hide overflowing content from Bd component

react/IntentModal/IntentModal.jsx, react/IntentModal/test/__snapshots__/intentModal.spec.js.snap
Spent one hour tonight dealing with this.
In the future we shoud improve this fix, by separating the logic between modal closing and intent cancellation. But it implies deprecating properties like `dismissAction`, ensure legacy and avoid regression.
I think we should wait for the release of cozy-interapp to make Cozy-UI components up to date and improve this fix.
=> 🚑  fix: avoid IntentModal dismissAction to be called twice

react/ActionMenu/index.jsx
The gestures handler must be attached to the wrapper node instead of the menu itself, so that the user can swipe from wherever he wants on the screen (today it's necessary to begin the swipe on the menu).
=> Fixed swipe down on ActionMenu

stylus/components/button.styl
I updated the compact version of the `ButtonAction` component to make it match the requirements banks.
It means : 
* Remove the border on the left (we need to handle it at the application level since even if a transaction row does'nt have an action, it shows this border)
* Remove specific size for the compact variant
See https://drazik.github.io/cozy-ui/react/#buttonaction , and the result in banks :
=> feat: remove dimensions and border on compact version of ButtonAction

docs/styleguide.config.js, react/Badge/Readme.md, react/Badge/index.jsx, react/Badge/styles.styl, react/index.js, stylus/components/badge.styl, stylus/components/button.styl
This adds a `<Badge />` component that can wrap any other component to add a little circle with some content to it.
See https://drazik.github.io/cozy-ui/react/#badge
=> feat: add Badge component

stylus/components/list.styl
Following @joel-costa review, I added 3px top margin on the captions inside `ListItemText`
=> feat: add 3px margin on caption inside ListItemText

stylus/components/button.styl
There was previously some dimensions on `ButtonAction`, but I wrongly removed it. I re-added some dimensions that fits our needs.
See https://drazik.github.io/cozy-ui/react/#buttonaction
=> feat: add width and height to compact ButtonAction

package.json
This PR disable the eslint '--fix' option, to detect incorrectly formatted code. It avoids to get a lot of changes in other unrelated PR due to changes on code format. See https://github.com/cozy/cozy-ui/commit/750df30a69ec74a986f4ff8cf71e2f148c0669eb
=> chore: disable lint fix

react/Toggle/index.jsx, react/Toggle/test/toggle.spec.js
The toggle was always returning `!props.checked` instead of returning the real new toggle state.
=> Fix toggle state return from onToggle + add tests

react/Button/Readme.md, react/Button/index.jsx, react/Button/styles.styl, react/__snapshots__/examples.spec.jsx.snap, stylus/components/button.styl
WOOPS
First part of this feature was accidentaly (but safely) committed in 4a957d4, as I was working on it when feeling like it was time to add Prettier (#440).
~I started by encaspulating a regular `<Button />` but the CSS styles were too much specific, and the button text should be looking almost like something which is not a button. So I have been needing to inject a specific `baseClassName` into the <Button /> component.
The first solution was to add a prop, but exposing it was upsetting me. So I made an `abstractButton()` wrapper which encapsulate all the mechanism for styling a whole new button. I also guess it could be useful in the future.~
This PR adds a `<Button />` variant, named _subtle_ as discussed with @Claiw 
> un subtle button c'est un bouton qui se la ramene pas, il est …
=> enhancement: Adds "subtle" <Button /> variant

react/I18n/index.jsx, react/I18n/translation.jsx
Expose an `extend(dict)` method to be able to extend locales dictionnary. It could be useful for adding locales related to an app or a konnector.
Usage:
```js
import { extend } from 'cozy-ui/react/I18n'
// [...]
extend({
'such': {
'useful': 'very i18n'
}
})
// [...]
console.log(t('such.useful'))
// very i18n
```
=> Expose I18n extend() method

stylus/components/button.styl
Was
Instead of 
EDIT: I also move the theme to use it also for the regular default button.
https://cpatchane.github.io/cozy-ui/react/
=> Fix visited button overwritting styles

stylus/utilities/spaces.styl
`.u-mv-1` will have vertical margins of 1rem
`.u-ph-2` will have horizontal paddings of 2rem
=> ✨ feat: add horizontal/vertical directions to spacers

react/SelectionBar/styles.styl, react/Spinner/styles.styl, stylus/components/chip.styl
No need to import twice ;)
> Disclaimer: In all places the @import is used with Stylus sheets, the @require could be used
> Along with @import, Stylus also has @require. It works almost in the same way, with the exception of importing any given file only once.
http://stylus-lang.com/docs/import.html
=> 🚀 perf: use require instead of import

react/Button/index.jsx
The call to `btnClass()` was still made with several arguments instead of an object. The tests did not spot this because of a bug in it, see #485.
=> Fix <ButtonLink /> className prop format

react/Chip/index.jsx
We may want to style the separator slightly differently from the original. In that case, the `className` prop is needed.
=> feat(Chip): add className prop on Chip.Separator

react/__snapshots__/examples.spec.jsx.snap, react/testFromStyleguidist.js
The test will pass when #486 will be merged.
Examples code chunks wer always rendered with the first code chunk https://github.com/cozy/cozy-ui/pull/485/files#diff-57b7a5e12d97c30c13de5396a4d16c89R163, so for example all Button examples were rendering the same.
=> Fix examples jest and snapshots

react/Modal/Readme.md, react/Modal/index.jsx, react/Modal/styles.styl, stylus/components/modals.styl
fix https://github.com/cozy/cozy-ui/issues/491
The cross is positioned absolutely so it has no effect on the layout of the header. For the header not to overflow on the cross, I added right padding on the header when the modal is showing the cross (= when it is closable). 
View on https://ptbrowne.github.io/cozy-ui/react/, the complex modal has a long title.
=> fix: add padding for cross in modals

react/Button/index.jsx
Edit: Let's just add the `button` value for prop `type` in `<Button />`.
~~Default type should be `button`, to avoid having several button with type `submit` in the same form, for example. The type `submit` is supposed to send form data.~~
From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button:
> The type of the button. Possible values are:
> * `submit`: The button submits the form data to the server. This is the default if the attribute is not specified, or if the attribute is dynamically changed to an empty or invalid value.
> * `reset`: The button resets all the controls to their initial values.
> * `button`: The button has no default behavior. It can have client-side scripts associated with the element's events, which are triggered when the events occur.
=> Add 'button' value for 'type' in Button

react/SelectionBar/index.jsx, stylus/components/selectionbar.styl
On mobile, the button to close the selection bar was hidden.
This is because there was a rule hiding `span` inside `button`, which was meant to target the text labels in the selection bar, but accidentally also targeted the `span` inside our `Button` component.
I hope I'm somewhat clear? Anyway, it's fixed.
=> fix: close button in selection bar

react/Badge/index.jsx
oneOf is used to check the prop against values whereas oneOfType is
to check the type of the variable.
=> 🐝 fix: use oneOfType

package.json, react/Button/Readme.md, react/Button/index.jsx, react/__snapshots__/examples.spec.jsx.snap, yarn.lock
It is useful for a Button to render with a different tag.
Another solution for #484 that does not extend the API of Cozy UI.
For example if you want a Button to render with a NavLink : 
```
<Button tag={NavLink} to='/toto' />
```
It is a breaking change since `<AsButton />` is removed.
=> feat: Button can render with a different Tag [breaking]

react/IntentModal/styles.styl
Edit : Potentially breaking for [cozy-store](http://github.com/cozy/cozy-store/) and [cozy-interapp-sandbox](http://github.com/cozy/cozy-interapp-sandbox/)
These are the only two applications using `<IntentModal />`, which is relatively new, at this time.
A CSS `width` property is overriding default modal sizes.
=> Remove IntentModal width CSS property

stylus/objects/layouts.styl
=> fix: Mono-Column layout have a padding at the end of page on mobile

react/SelectBox/styles.styl
In the selectBox, the checkmark is placed too far below in Firefox.
When a node is floated and one of the ancestor has `whitespace: word-wrap`, in Firefox the float element is wrapped.
By resetting the value to whitespace value to normal in the select-box `option`, the correct behavior (check mark on the same line as
the label) is ensured.
=> 🐝 fix: reset white-space so the tick is well placed in Firefox

stylus/components/selectionbar.styl
=> fix: hide selection bar labels on mobile

react/IntentOpener/IntentOpener.jsx, react/IntentOpener/IntentOpener.md
The `IntentOpener` uses `IntentModal`, and since #499 the default size of the `IntentModal` has changed.
This change allows to configure the `IntentModal` through the `IntentOpener` component.
=> feat: configure modal through IntentOpener

react/Label/index.jsx, react/__snapshots__/examples.spec.jsx.snap
It will avoid these warnings in console `Empty string passed to getElementById().` when we just want to use `<Label/>` without the `for` attribute.
=> Default `htmlFor` to undefined for `<Label/>`

package.json
Previously it was an `import` statement for `normalize.css` from `node_modules`, broking usage in apps. Now the required content of `normalize.css` is correctly imported.
=> Correctly import css code to build

package.json, yarn.lock
Using [commitlint](https://github.com/marionebl/commitlint) and [husky](https://github.com/typicode/husky), we ensure that the commit messages are well formatted. The rules are the one from [Conventional Commits](https://conventionalcommits.org/), that we already follow.
Failing : 
Success :
=> chore: use commitlint to ensure all commit messages are valid

stylus/components/button.styl
There was a problem when these buttons were focused and/or hovered : 
This fixes it:
=> fix(action button): fix focus styles

.stylintrc, react/MidEllipsis/index.jsx, react/MidEllipsis/styles.styl, react/Text/index.jsx, react/Text/styles.styl, stylus/utilities/display.styl, stylus/utilities/spaces.styl, stylus/utilities/text.styl
Made utility classes global so you don't have to create classes and extend them anymore. You can just use the class without CSS-Modules now.
Before:
```jsx
<Element className={styles['u-ellipsis']}>
{children}
</Element>
```
After:
```jsx
<Element className='u-ellipsis'>
{children}
</Element>
```
📌  [previous merge](https://github.com/cozy/cozy-ui/pull/524)
=> feat: add global utility classes

stylus/components/button.styl
In https://github.com/cozy/cozy-ui/pull/523 I fixed a part of a problem we had with ButtonAction hover/focus styles, but it was not totally in sync with what was designed.
Also, we had a focus ring on chrome, which we can remove since we handle focus state properly.
=> Fix hover/focus styles on ButtonAction

stylus/cozy-ui/build.styl, stylus/cozy-ui/index.styl, stylus/tools/mixins.styl, stylus/utilities/display.styl, stylus/utilities/spaces.styl, stylus/utilities/text.styl
`:global()` shouldn't appear in CSS files as this is not a valid CSS syntax and therefore browsers would ignore the entire declaration making the utility classes for the standalone build ignored.
Instead I used a mixin `global()` to output a normal utility class for the standalone build and a version with `:global()` when used with CSS-modules.
`global()` takes two parameters:
- `selector` which should be a string for the CSS class you want
- `placeholder` which is the placeholder you want the class to `@extend`
=> fix: global styles are compiled only when used with CSS-modules

stylus/cozy-ui/build.styl, stylus/utilities/cursor.styl
Add several utility classes for cursor.
- `.u-c-default` - Force default cursor
- `.u-c-help` - help cursor for help and/or tips
- `.u-c-pointer` - pointer cursor showing the element is clickable
- `.u-c-wait` - wait cursor to express that an action is pending
- `.u-c-not-allowed` - not allowed cursor, often used on a disabled element, to express your inhability to make an action
Fixes issue #478
=> feat: add cursor utility classes

package.json, react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/__snapshots__/examples.spec.jsx.snap, yarn.lock
`react-select` new version enables `className` customization for each component.
I exported the components from `react-select` because if the host application has another version of `react-select` and start passing components from a newer version of `react-select` to "our" `react-select`, it causes very hard to debug problems.
=> Update react select

react/SelectBox/SelectBoxWithFixedOptions.jsx, react/__snapshots__/examples.spec.jsx.snap
Radius is now on fixed elements too !
Before | After
-------|------
=> fix: Select box bottom border on fixed element 🐛

stylus/components/modals.styl
=> fix: modal width which can exceed the window 🌽

stylus/components/table.styl
There shouldn't be a border between a `table-row` & a `table-divider`.
Preview: https://gooz.github.io/cozy-ui/styleguide/section-components.html#kssref-components-table
Fixes #515
=> fix: border on table divider

react/I18n/index.jsx
In Drive, we want to have a `t` instance in the redux context. Therefore, we need to init i18n first to get our polyglot instance, and then pass it to the `I18n` provider. Thus these changes ;)
=> Exposed initTranslation() and allowed polyglot prop for I18n

stylus/components/modals.styl
The rem() part in the string "calc( rem() )" is not interpreted by stylus
hence it reach the browser, and cannot be interpreted.
IMHO, it's better to do the calculation directly in Stylus. 
fix #542 
https://ptbrowne.github.io/cozy-ui/react/#!/Modal/1
=> fix: modal header no longer has padding

react/SelectBox/SelectBox.jsx, react/SelectBox/styles.styl
On mobile, the select has a before element covering all the page.
Clicks happen on the element on not on outside elements -> the user can
more easily close the menu without inadvertently triggering something.
different approach than https://github.com/cozy/cozy-ui/pull/521 since here
we use a pseudo element covering all the page.
=> feat(selectbox): adds overlay for outside clicks not to trigger anything

stylus/settings/z-index.styl
Made sure the drawer of the bar always goes over the nav on mobile.
=> fix: bar z-index just over nav z-index

stylus/components/modals.styl
Because `100vh` unit **is not** 100% of the viewport's height on mobile devices but more than that and we don't want that behaviour.
=> fix: Use % instead of vh unit in modal-wrapper

commitlint.config.js
Small fix to allow capital letters anywhere in the git commit message. 
You can actually use lowercase, camelCase, or whatever case you want.
=> fix: Allow capital letters in git messages

react/IntentModal/test/__snapshots__/intentModal.spec.js.snap, react/Modal/index.jsx
Add two new props to the Modal component: `height` and `width`. The need was to be able to customise an interapp Modal.
=> Handle width/height in Modal:wq

react/Modal/Readme.md, react/Modal/index.jsx, stylus/components/modals.styl
* this.props is old props in componentWillUpdate
* no need to use state for computed properties
* modified animated header example to use state (so that we can see the bug if it comes out again)
=> fix: modal update

stylus/components/button.styl
A secondary single text on white background, so without the "box" of a button, seemed way too bright for a good readability, so I darkened it according to @Claiw's recommendation.
Fixes #566
=> fix(Button): Darken secondary subtle button for readability

stylus/elements/defaults.styl
Fix a layout issue on menu that occured when the content is not long enough on tablet.
=> fix: layout overflowing on tablet and smaller

react/I18n/index.jsx
This feature is useful in the Store to know if there is some text to display or not since the `t()` will return the key by default if the local doesn't exist.
=> Add t or nothing helper in I18n

docs/styleguide.config.js
Since we start to have a lot components in the styleguide, it takes
a lot of time to load. Not showing code blocks simplifies greatly
the loading and feels much smoother.
=> perf: no usage/code in styleguide

react/I18n/index.jsx
Reverts cozy/cozy-ui#581
Finally the needed feature is now handled by `t` using the `{ _: ""}` option.
See the [`t()` documentation](http://airbnb.io/polyglot.js/#polyglotprototypetkey-interpolationoptions) :
> If you like, you can provide a default value in case the phrase is missing. Use the special option key “_” to specify a default.
=> Revert "Add t or nothing helper in I18n", already handled by t()

stylus/components/alerts.styl
Alerts have a full width transparent wrapper that was preventing clicks on Cozy-Bar items.
=> fix: Alerts' wrapper doesn't prevent click throught it anymore

react/Modal/index.jsx
It doesn't broke the modal but we have an error in the console saying that the contentHeader doesn't exist if we don't use the animated header here.
=> Check for animated header for scrolling event

react/AppIcon/Readme.md
The first implementation of the component was using directly an instance of CozyClient, but in the final version it only needs a `fetchIcon` method.
=> Fix use of CozyClient in AppIcon documentation

react/I18n/translation.jsx
Since `cozy-home` is using context with the `I18n` component, a missing locales file was not caught correctly and was breaking the whole application (blank page).
It should be fixed by this PR.
=> Catch context locales missing error

react/Button/index.jsx, react/__snapshots__/examples.spec.jsx.snap
- It's useless on a button, it's already a defined button
- It's deceptive on a link, it sure looks like a button but it's
not and it should not behave like one
Refs  #601
=> fix: Remove `role="button"` from Button Component

react/Accordion/index.jsx, stylus/components/accordion.styl
Previously, Accordion was using Tabs logic for accessibility.
This PR cleans this up.
Refs #601
=> fix: Better a11y on Accordion

react/Button/Readme.md, react/Button/index.jsx, react/__snapshots__/examples.spec.jsx.snap, stylus/components/button.styl, stylus/utilities/display.styl
Refs  #601
**BREAKING CHANGE:**
- `label` props is now required
- `iconOnly` props is required if you want to get a button with only an icon
So allow me to explain a little bit.
We need buttons to always, in any way, display a label explicitely describing what the actions of the button does.
There's two cases when you consider having an icon in your button, and either way the icon must be hidden with `aria-hidden` set to `true`, but there's some differences:
1. The Icon is with a text. Nothing special to do here. It's like before. 
2. The Icon is on its own. In this case, as the icon is hidden, we must add some label for screen readers by using the same DOM for a normal button except we're hiding it visually; then you should also have a `title` on your button so people that don't …
=> feat: Make Button component more accessible

package.json, yarn.lock
Required to handle svg icons with Webpack 4
~~Should not break the webpack 3 compatibility. It was the version used by the Store since now.~~
Finally it requires that cozy-ui use Webpack 4 too, I think __it can be considered as a breaking change__ so
=> Upgrade svg-sprite-loader for webpack 4

stylus/components/modals.styl
Even if the content of a Modal is not long enough, a Modal will take 100% of the available space until it reaches its own max width
Fixes #490
=> fix(Modal): 💄 Modal width 100% on small screens

react/Modal/index.jsx, react/Modal/styles.styl
`c-app-icon` class used in Modal was causing conflict issue and visual regression on cozy-home and bar.
Surprisingly, this issue just appeared recently, and everything was working well at the date of the different commits related to this bug.
=> Avoid conflict with c-app-icon

react/AppIcon/styles.styl
The goal is to ensure that App icons are keeping their dimensions, even in a flex context.
This also fix this litte gap between labels in the cozy-bar.
=> Prevent flex side effects

react/Layout/Layout.jsx
We cannot use a stateless as ref in React, 
since we use `<Content />` to reset the scroll
in the Store, we have to make it a stateful component
=> Fix: Make <Content /> a stateful component

react/Alerter/index.jsx
this.base is specific to Preact and was undefined with React
=> fix: Alerter not compatible with React

react/Menu/styles.styl
Reseting the complete background property means you also loose any background images, positions, etc. Which isn't what we want.
=> fix(MenuButton): Hover background

react/Portal/index.jsx
@CPatchane I wouldn't mind a second check for this PR — for me, `require('preact-portal')` gives me the module right away, whereas `require('preact-portal').default` returns `undefined`.
(The alerts still worked but weren't portal anymore.)
=> fix(Portal): Import the main module

stylus/components/alerts.styl
Alert messages are not clickable, so the cursor here was wrong.
=> fix(Alerts): Default cursor

docs/styleguide.config.js, react/Tabs/Readme.md, react/Tabs/index.jsx
`getInitialState` does not work in newer versions of React. Replaced with state in constructor. Added example.
=> fix: Make tabs work with React

react/Modal/index.jsx, react/Overlay/index.jsx
Using the Overlay component to open a modal would result in the page being scroll-locked, because `body-scroll-lock` would restore the `overflow` property to `hidden` when the Modal closes, as set in the Overlay.
Using the lib in both cases fixes the issue.
=> fix(Overlay): Use lib to lock scroll

stylus/utilities/spaces.styl
BREAKING CHANGE: U-* classes are now !important by default
When you decide to have no-padding, you should have no-padding ;).
=> feat: U-* classes are now !important by default

docs/styleguide.config.js, react/Circle/Readme.md, react/Circle/index.jsx, react/Circle/styles.styl, react/Counter/Readme.md, react/Counter/index.jsx, react/index.js, stylus/components/circle.styl
A new component to show a simple counter. [Here's a link to the demo and the docs!](https://yannick-lohse.fr/cozy-ui/react/#counter)
There are potentially more things that could be done, like coupling the `max` and the `size` properties, an easier way to change the font color, etc. I don't really know what the needs are at the moment, so I think we can expand it later, but le me know if you think something essential is missing.
There's only one size for now — I think we'll be using the same ones as in #650 once it's settled.
=> feat: Counter component

stylus/components/button.styl
The `position: absolute` of `.u-visuallyhidden` class in a button was messing with the height of the scrollable container because the absolute had no origin inside the button.
=> fix: 🐛 Scrolling table when icon button inside

docs/webpack.config.js, package.json, react/Portal/index.jsx, yarn.lock
Since we use `preact-compat` as alias for `react-dom` there already a `createPortal` compatibility so we don't need to use `preact-portal` anymore. And same thing for the `USE_REACT` variable.
See 
https://github.com/developit/preact-compat/pull/486
=> Use portal from preact-compat

react/Input/index.jsx
We expose an `inputRef` to pass a ref to the native input. With that, we ca : 
```jsx 
//createRef
this.textInput = React.createRef()
///focus
this.textInput.current.focus()
///
<Input
inputRef={this.textInput}
type="text"
placeholder="Nom du groupe"
onClick={this.onClick}
onFocus={this.onFocus}
onBlur={this.onMainInputBlur}
size="tiny"
/>
```
=> feat: Add inputRef to Input

package.json, yarn.lock
ATM we're on a beta... So I upgraded to the latest stable. 
I didn't have any issue but regarding the changelog we can have one issue but I don't know if we are concerned
`[BREAKING] innerRef assignments in custom components must now be made from the root of the prop object, as opposed to reaching into innerProps. This is part of the work to normalize the behaviour circa custom components. #2824`
=> feat: Upgrade to react-select 2.1.1

react/IntentModal/test/__snapshots__/intentModal.spec.js.snap, react/Modal/index.jsx
I propose to add this prop so we can customize the style of the root element when we need it.
It is useful for example in banks in which we want to show a `Modal` when we click on the logout button. But it that case, since the `z-index` of the `Modal` is lower that the cozy-bar one, the modal is always behind it.
=> feat(Modal): Add containerClassName prop

react/Modal/index.jsx
Button styles were loaded after the Modal styles, making some unreasonable conflicts.
=> fix: 🐛 Changed Modal CSS order to avoid conflicts

react/IntentIframe/styles.styl
Intents display was broken due to aria-busy attribute always present
with a 'false' value.
This iframe was working since 7 months without changes and we
were not able to determine why it suddenly started to fail.
We suppose that an 'aria-busy' attribute to undefined was previously not
rendered at all, and a recent change made it rendered with a 'false' value.
=> Fix intents display

react/AppIcon/Preloader.js, react/AppIcon/Readme.md, react/AppIcon/__mocks__/Preloader.js, react/AppIcon/index.jsx, react/AppIcon/test/AppIcon.spec.js, react/AppIcon/test/Preloader.spec.js, react/AppIcon/test/__snapshots__/AppIcon.spec.js.snap
This PR ~~deprecates the fetchIcon prop for AppIcon~~ use directly icon sources
an `<img />` tag if no `fetchIcon` prop is passed, now that all icon served by the stack are accessible
without permissions on doctype `io.cozy.apps`.
=> AppIcon: Prefer img element over fetchIcon method

react/Modal/index.jsx
`has-modal` class was only added when `ModalContent` was used and
IntentModal don't use this component so I moved the `has-modal` toggle
to `Modal` component instead.
=> fix: 🐛 IntentModal can have has-modal class

package.json, react/Alerter/index.jsx, react/Avatar/index.jsx, react/Modal/index.jsx, react/SelectBox/SelectBox.jsx, react/SelectBox/SelectBoxWithFixedOptions.jsx, yarn.lock
`babel-cli` should be a dev dependency, not a regular one. At least for me, installing it as a regular dependency meant I couldn't run the `transpile` command because the `babel` command could not be found.
=> chore: Install babel-cli as a devdep

react/AppIcon/Preloader.js, react/AppIcon/test/AppIcon.spec.js, react/AppIcon/test/Preloader.spec.js, yarn.lock
AppIcon was not usable without a domain prop,
making fetchIcon prop impossible to use.
=> AppIcon: Allow undefined domain

package.json
Since `commitlint/cli` is imported by `commitlint-config-cozy` https://github.com/cozy/cozy-libs/blob/master/packages/commitlint-config-cozy/package.json#L28  we don't need to depend on it
=> chore: Commitlint cli is not needed

react/Input/Readme.md
Added an exemple to show how to focus programmatically an `<Input />`
=> docs: Set focus programmatically

react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/SelectBox/index.jsx, react/SelectBox/styles.styl, react/__snapshots__/examples.spec.jsx.snap
I needed to add some buttons *inside* an `Option`. I doubt anyone will need the same buttons, so I added an option that allows us to render extra elements inside the Option. Please [see the new documentation for more details](https://yannick-lohse.fr/cozy-ui/react/#selectbox) ("Further control over options" section).
=> feat(Select): Extra render prop in Option

package.json, react/Portal/index.jsx, yarn.lock
En gros, React / Preact ont une différence, c'est que si tu fournis un composant vide à Preact, il va remplacer complètement le target... Alors que react va juste ajouter un truc vide à la target. 
Sur Drive, on a le souci avec l' `Alerter` et du coup ça nous remplacé tout le body par un truc vide. Donc plus de `div role="application"` avec tous les inconvénients que ça engendre...
L'issue Preact https://github.com/developit/preact-compat/issues/515
=> fix: React preact compatibility with Portal

package.json, yarn.lock
We currently can't `yarn install` because npm-run-all uses the deleted npm package `event-stream`.
=> chore: Upgrade npm-run-all

package.json, yarn.lock
We do not want to have preact installed in the host application when
installing cozy-ui.
See how material UI does that : https://github.com/mui-org/material-ui/blob/master/package.json#L55
=> chore: Put preact and react as peer deps

stylus/components/table.styl, stylus/settings/z-index.styl
Removed the problematic pseudo-element `::before`
=> fix: 🐛 table divider z-index & color

react/Modal/index.jsx
It was supposed to help giving the focus when opening the modal but it's
not needed anymore since we plugged FocusTrap
Also, it will remove the outline style when header is clicked.
=> fix(Modal): Removed useless tab-index

stylus/tools/mixins.styl
So it's always applied, since it's meant to override.
=> fix: 🐛 Add !important to .u-hide utility

react/AppIcon/index.jsx, react/AppIcon/test/__snapshots__/AppIcon.spec.js.snap
Fix also an issue about icon cube not found in the last version of Cozy-UI
=> fix(AppIcon): Use cube icon instead of import

stylus/components/wizard.styl
Oops. I unfixed a fix. Here is the fix fixed.
The text from a select shouldn't go over the arrow now.
=> fix: Wizard select padding

react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/__snapshots__/examples.spec.jsx.snap
Add classNamePrefix on Option class.
On Banks app we add `classNamePrefix='needsclick cz'` but the Option component don't use it, it's a bug we can display only on iOS ;)
https://kosssi.github.io/cozy-ui/react/#!/SelectBox
=> Select option with prefix

package.json
By doing this we ensure that running 'yarn jest' will use the expected
transpilation environment variable, and we avoid differences in jest
snapshots.
=> Wrap jest command

react/Field/Readme.md, react/Field/index.jsx, react/Input/Readme.md, react/Input/index.jsx, react/Input/styles.styl, react/__snapshots__/examples.spec.jsx.snap, stylus/components/forms.styl, stylus/cozy-ui/build.styl
This PR adds `size` prop to Field component, which is passed to Input component.
We chose to explicitly set the default Input size to `large` and use a new dedicated placeholder `input-text-size--large`.
Next step should be to change the default size to `medium` to avoid CSS property duplications between `input-text` and `input-text-size--large`. It will cause breaking changes.
=> Add size prop for Field

react/AppIcon/Preloader.js, react/AppIcon/Readme.md, react/AppIcon/index.jsx, react/AppIcon/test/Preloader.spec.js
Currently we can only get an app icon by giving an object with slug and latest_version properties to `AppIcon`. In Banks, we will need to get konnectors icons from their slug.
The idea here is to make `AppIcon` accept a string as its `app` prop. If we pass a string, it will always fetch the icon url from the registry via the [`/registry/:app/icon` route](https://github.com/cozy/cozy-stack/blob/master/docs/registry.md#get-registryappicon).
=> feat(AppIcon): Add possibility to get the icon from an app slug

stylus/components/wizard.styl
Fix the height of the onboarding wrapper to 100% when using a bleeding wrapper on desktop.
=> fix: 🐛 height of onboarding bleeding wrapper

stylus/components/forms.styl
Checkbox was vertically centered with multiline label and we want it to stay to the top whatever the number of lines
Also it fixes https://github.com/cozy/cozy-stack/issues/1697
=> fix: 🐛 checkbox position with multiline label

react/Checkbox/Readme.md, react/Checkbox/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Useful to pass much complicated text with bold parts or links
=> fix(Checkbox): Allow children for Checkbox component

react/MuiCozyTheme/Menus/Readme.md, react/MuiCozyTheme/Menus/index.js, react/MuiCozyTheme/theme.js
[Styleguidist preview](https://gooz.github.io/cozy-ui/react/#menus)
Still glitching and/or missing:
- ~~The `Grow` transition only works when opening but not when closing.~~
- Z-index issue on the `Popper`, I'm still trying to figure out if there's a way to get a higher z-index without using styles like the legacy `MuiMenu` that "uses" Modal styles… ¯\_(ツ)_/¯
- Getting the drawer on mobile
- Put styles in `theme.json` only
=> feat: Ui theme for MUIMenu

react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/SelectBox/test/SelectBox.spec.js, react/__snapshots__/examples.spec.jsx.snap
In Cozy-Harvest-Lib we faced an overflow issue with the SelectBox component:
This issue could be resolved in several way:
* Limit the height
* Use a React Portal to show the menu list below all the other element in the DOM
There is already an height limitation in PR #795.
Portaling does not work with preact, and Cozy-Home is still in Preact.
In this PR we propose another solution: give an element as boundaries, and
not expand the menu list outside those boundaries.
With this PR, our first issue is resolved and our SelectBox in Cozy-Harvest-Lib
now looks like this:
You can have a preview [here](https://gregorylegarec.github.io/cozy-ui/react/#!/SelectBox/5).
=> SelectBox: Add boundaries prop to avoid overflow

stylus/components/forms.styl
It now shows the red borders for `:invalid` inputs only when your're not focus in it. 
That way it doesn't get red prematurely, like when you're typing the first letters of your email in a mail input and it gets red right away even if you're not finished. That sent the wrong UX message.
=> fix: 🐛 Invalid input show style only on blur

stylus/components/button.styl
All buttons should have a bold text, since… forever actually.
Preview: [KSS](https://gooz.github.io/cozy-ui/styleguide/section-components.html) & [styleguidist](https://gooz.github.io/cozy-ui/react/#button)
=> fix: 🐛 Buttons should have bold text

react/Text/styles.styl, stylus/components/button.styl, stylus/cozy-ui/build.styl, stylus/utilities/text.styl
Button variants with different sizes have now a matching font-size.
Normal button size -> font-size = 14px
Small button size -> font-size = 13px
Tiny button size -> font-size = 12px
Large button size -> font-size = 16px
Also added utility classes to handle font-size to a given text:
```
.u-fz-tiny - Sets a tiny font-size (12px)
.u-fz-xsmall - Sets a xsmall font-size (13px)
.u-fz-small - Sets a small font-size (14px)
.u-fz-medium - Sets a medium font-size (16px)
.u-fz-large - Sets a large font-size (18px)
```
And finally, I fixed text-alignment utility classes by moving them to the right place and renaming them more clearly.
=> feat: ✨ Button font-size matches its size

stylus/components/forms.styl, stylus/components/wizard.styl, stylus/cozy-ui/build.styl
Multiple bugfix and enhancements for the wizard:
- Some design fix such as list items indentation or checkbox padding
- Make sure content is not centered but top aligned on mobile
- Reforge dualfield class to be more extensible
- Renamed `.wizard-password` to `wizard-input` since it's used for every input.
=> fix: Late wizard bugs

package.json, stylus/components/alerts.styl, stylus/cozy-ui/build.styl
By transforming normalize.css to a stylus file and loading this file, stylus can remove the comments from this file. It makes the CSS file in dist/ 7kb lighter (from 84kb to 77kb).
=> feat: Make the CSS in dist 7kb lighter ✨

stylus/components/empty.styl, stylus/objects/layouts.styl
So I removed the fixed positionning and added a `margin-top` to the Empty element according to the viewport height (minus the height of the cozy-bar and the navigation to be a little more precise), which basically should render exactly the same as before but without overlapping any other element so no more "pointer-events" issue.
The fix in Drive about that would be removable but won't break things if it stays (which it shouldn't obviously) so you have time to clean this up.
Also reduced the `margin-bottom` of the icon as requested by the designers.
=> refactor: Refactored style for Empty view

react/Field/Readme.md, react/Field/index.jsx, react/Field/styles.styl, react/__snapshots__/examples.spec.jsx.snap
The position of the side element should be align on the right of the input.
With or without fullwidth option.
=> fix(field): Right position different with & whithout fullwidth

react/Field/index.jsx, react/Input/index.jsx, react/Textarea/index.jsx
In cozy-harvest-lib we are using field which are not inside
a `<form />` tag.
This prevent us for having the login and password automatically
filled by browsers.
By the way we still need to detect Enter key and so we need
an `onKeyUp` prop on Field.
As soon as every harvest application will have its own
domain dedicated to its related konnector, we will be
able to use a `<form />` tag again.
=> Add prop onKeyUp on Fields

stylus/components/wizard.styl
Wizard's fixed header is a little bit smarter.
Margins are handled by the children elements instead of the parent.
=> fix(wizard): Fluid fixed header

react/Field/index.jsx, react/Input/index.jsx
To manage autocompletion behavior in cozy-harvest-lib, we
need to be able to specify the `autocomplete` attribute of
`<input />` elements.
See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
=> Field: Expose autocomplete

react/Button/Readme.md, react/Button/index.jsx, react/__snapshots__/examples.spec.jsx.snap
We had a lot of discussion during the rewrite of `Avatar` concerning the default & explicit props (https://github.com/cozy/cozy-ui/commit/fad19337e8ee9522d70c4200f520d5a35b372328) 
I applied the same behavior for `Button`
=> fix(Button): Expose size===normal

stylus/objects/layouts.styl
Add padding-bottom to `main` in order display correctly on iPhone X.
This is a relive of https://github.com/cozy/cozy-ui/pull/822 
This time this commit is well tested on native & web (drive)
=> fix: Layout issue on iPhone X

stylus/cozy-ui/build.styl, stylus/settings/breakpoints.styl, stylus/utilities/flexbox.styl
Added flexbox utility classes [inspired by Tachyons](https://github.com/tachyons-css/tachyons/blob/master/src/_flexbox.css).
Basically there's a class for every flexbox related properties.
Each one of them is also available for every basic Media Query.
For example, the class `u-flex` that displays an element with flexbox property goes like this
```css
.u-flex {
display: flex;
}
@media (max-width: 23.438rem) {
.u-flex-tt {
display: flex;
}
}
@media (max-width: 33.938rem) {
.u-flex-t {
display: flex;
}
}
/* Etc, for every breakpoint */
```
[Documentation preview](https://gooz.github.io/cozy-ui/styleguide/section-utilities.html#kssref-utilities-flexbox-display)
~~📌 NB: Couldn't find a way (yet) to generate those classes with a function due to Stylus limitations.
See the [Stack Overflow …
=> feat: Add flexbox utility classes

react/utils/color.js
Stack themes are overriding CSS variable on body. So getting it from
html can lead to incorrect values when using a theme from the stack.
For example, in an app that uses a stack theme, I can be in the
following situation:
```
:root {
--primaryColor: black;
}
body {
--primaryColor: white;
}
```
In that case, if we get the variable value from `html`, we will get
`black`, where we want to get `white`. With this fix, we will get
`white`.
I tried to write tests for this helper, but JSDOM doesn't handle `:root` and `setProperty`, so I couldn't (see https://github.com/jsdom/jsdom/issues/1895)
=> feat(utils): Get CSS variable value from body

react/Modal/Readme.md, react/Modal/index.jsx, react/Modal/styles.styl, stylus/components/modals.styl
Fixes: #653
`ModalContent` has a new props `fixed` that turn this scrollable (by default) element into a non-scrollable one making it look like a fixed element of the modal.
[Preview](https://gooz.github.io/cozy-ui/react/#modal)
=> feat(Modal): ✨ Add ModalContent fixed props

react/Field/Readme.md, react/Field/index.jsx, react/Input/Readme.md, react/__snapshots__/examples.spec.jsx.snap
It's pretty convenient to have this prop available in Field. It allow us to give them focus, for example in https://github.com/cozy/cozy-libs/pull/316.
=> feat(Field): Expose Input's inputRef prop ✨

react/Field/index.jsx
Add `date` and `select` to list of valid values for prop `type`.
This was causing warnings in Jest tests.
=> Field: Add missing values for prop type 📝

react/Field/index.jsx
The idea is just to clean what Field component is passing to a SelectBox. It follows [this comment](https://github.com/cozy/cozy-libs/pull/316/files/93a0f641e1508f0d3f1b99e12e6697c43501345e#r264004244) from @ptbrowne.
A ideal solution would rely directly on `SelectBox.propTypes`, but they cannot be exhaustive as they must provide all props `ReactSelect` needs, and as the main component does not expose propTypes, I was not able to find a way to properly do that.
=> Field: Do not pass Input propTypes to SelectBox

react/Field/index.jsx, react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/SelectBox/styles.styl, react/__snapshots__/examples.spec.jsx.snap, stylus/components/forms.styl
Solves #857
This PR adds a `disabled` prop to SelectBox, which is mapped to react-select `isDisabled` prop.
I kept `disabled` to be consistent with Field and Input API.
There is still an issue left: the `cursor: not-allowed` property does not work because of the `pointer-events: none` property on the SelectBox's `container` element. Removing the `pointer-events` declaration make react-select unable to position its `menu`.
I see two options to have this `cursor: not-allowed` to work:
* Investigate into react-select code how we may fix this, make a PR
* Wrap our `<ReactSelect />` into an element which will get the `cursor: not-allowed` (potentially breaking changes in our side). By the way it's not the first time that a wrapper on SelectBox could help us, I should need it to handle `KeyUp` …
=> SelectBox: Handle disabled prop

stylus/settings/palette.styl
Necessaire chez les Gangsters pour la background-color d'un bouton disabled.
=> wip feat: Add primaryColorLighter and primaryColorLightest

babel.config.js, package.json, react/Field/index.jsx, yarn.lock
The idea behind this PR is to enable apps to use tree-shaking with cozy-ui. As of now it is not possible for several reasons : 
- import/exports are transformed into require calls which prevents webpack to do static analysis and to flag unused exports
- sideEffects false is not present
The changes in this PR : 
- Do not touch import/export when transpiling otherwise webpack cannot use tree shaking in downstream apps (this is done via a config flag of babel-preset-cozy-app)
- sideEffects: false enables webpack to eliminate re-exports that are unnecessary in downstream apps. It has to be put on the lib side to tell webpack that the files of the package do not have side effects.
Additionally:
- transformRuntime helpers are imported from babel-runtime instead of being copied each time. This …
=> Enable tree shaking

.npmignore
Here's what we actually ship: https://unpkg.com/cozy-ui@19.12.0/
I kept some of the babel configuration and helper files, I'm not entirely sure they are useful though.
=> chore: Avoid shipping extra files to npm

stylus/cozy-ui/build.styl, stylus/settings/breakpoints.styl, stylus/tools/mixins.styl, stylus/utilities/display.styl, stylus/utilities/flexbox.styl
Added some  `display` utility classes.
- `.u-dn` - Display none
- `.u-di` - Display inline
- `.u-db` - Display block
- `.u-dib` - Display inline-block
- `.u-dit` - Display inline-table
- `.u-dt` - Display table
- `.u-dtc` - Display table-cell
- `.u-dt-row` - Display table-row
- `.u-dt-row-group` - Display table-row-group
- `.u-dt-column` - Display table-column
- `.u-dt-column-group` - Display table-column-group
Also I cleaned up a bit flexbox utilities, moving its stylus loop to `mixin.styl` so it is reusable.
=> feat: Add Display utility classes

stylus/utilities/spaces.styl
Added responsive utility classes for spacing (padding & margin).
Basically, it's the same classes name as before, you just need to add the breakpoint suffix matching your breakpoint of choice. 
| Breakpoint (px size) | Suffix |
| --- | --- |
| `BP-teeny`  (375) | `tt` |
| `BP-tiny`  (543) | `t` |
| `BP-small`  (768) | `s` |
| `BP-medium` (1023) | `m` |
| `BP-large` (1200) | `l` |
| `BP-extra-large` (1439) | `xl` |
e.g. You want an element with `1rem` of margin all around on desktop and only `.5rem` on devices below tablets. 
You will have to set it like this: `<div class="u-m-1 u-m-half-s">My beautiful element</div>`
NB:
This seems a little verbose, I agree, but I had to repeat myself because:
- Stylus doesn't allow extending `$placeholders` inside Media Queries.
- Can't use `{block}` …
=> feat: Add responsive spacing utility classes

stylus/utilities/spaces.styl
Before, the loop was creating classes in this order:
```css
.classA { … }
@media (…) { 
.classA-s {…}
}
.classB { … }
@media (…) { 
.classB-s {…}
}
```
Which meant that a responsive class such as `.classA-s` wouldn't be able to override a basic class like `.classB` defined after it and since responsive class are pretty much used to override some style it was unconvenient.
Now it outputs the classes like this:
```css
.classA { … }
.classB { … }
@media (…) { 
.classA-s {…}
}
@media (…) { 
.classB-s {…}
}
```
=> fix: Change loop order to override basic spacing classes

react/Empty/index.jsx, react/Text/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Dans un composant Empty, le "text" affiché est complètement différent d'un `Text` car on vient surcharger la couleur, les marges etc https://github.com/cozy/cozy-ui/blob/master/stylus/components/empty.styl#L38).
Donc vu qu'on surcharge via des classes, on est dépendant de l'ordre dans lequel les classes arrivent dans le fichier css généré, et ça, c'est pas cool. 
Plutôt que de se baser là-dessus, il est préférable de faire un propre composant pour ça.
=> fix: Create EmptySubtitle component

stylus/cozy-ui/build.styl, stylus/utilities/dimensions.styl
Add dimensions utilty classes to deal with `width`, `height`, `max-width`, `min-width`, `max-height`& `min-height` based on a given scale according to our design guidelines which would is:
1st step => 16px
2nd step => 32px
3rd step => 64px
4th step => 128px
5th step => 256px
6th step => 512px
7th step => 768px
8th step => 1024px
9th step => 1536px
extra step => 100%
Also you can cancel dimensions with canceling classes such as `u-w-auto` or `u-maw-auto`
=> feat: Add dimensions utility classes

react/IntentOpener/IntentOpener.jsx
Since we're checking if the props are here, we don't need to make them required.
=> chore(IntentOpener): Make onComplete & onDismiss optional

stylus/cozy-ui/build.styl, stylus/utilities/opacity.styl
Inspired by tachyons. https://tachyons.io/docs/themes/opacity/
I expect `u-o-100` and `u-o-0` to be the most useful.
=> feat: Add opacity utility classes

stylus/cozy-ui/build.styl, stylus/utilities/border.styl
Added those utility classes (obviously responsive)
- .u-bdrs-1 - Small border-radius (2px)
- .u-bdrs-2 - Medium border-radius (3px)
- .u-bdrs-3 - Large border-radius (4px)
- .u-bdrs-4 - Extra large border-radius (8px)
- .u-bdrs-circle - Round element with border-radius (100%)
[Preview](https://gooz.github.io/cozy-ui/styleguide/section-utilities.html#kssref-utilities-border)
Refs #867
=> feat: Add border-radius utility classes

react/Modal/index.jsx
To fix the warnings
```
Warning: Expected `onClick` listener to be a function,
instead got `false`.
If you used to conditionally omit it with onClick={condition && value},
pass onClick={condition ? value : undefined} instead.
```
=> fix: Cannot pass boolean for function

react/Field/index.jsx
Passing InputPassword props to Input was making React apps like Banks or Store throw errors.
=> Avoid "unrecognized props" for InputPassword

react/I18n/format.jsx, react/I18n/format.spec.jsx
An error is thrown if the date-fns locale corresponding to the default
lang can't be found, and it make the whole app crash. It should warn the
user that the locale can't be found in date-fns, but not crash the app.
=> feat(I18n): Don't crash if the default lang can't be found

react/MuiCozyTheme/theme.js
On cozy-banks we use material-ui theme from cozy-ui and we show this
warning every time we launch this app:
> Warning: Material-UI: you are using the deprecated typography
> variants that will be removed in the next major release.
> Please read the migration guide under
> https://material-ui.com/style/typography#migration-to-typography-v2"
=> fix: Remove warning of deprecated typography

stylus/components/forms.styl
We must make the CSS selector more accurate to avoid styling as disabled input with attribute `aria-disabled` to `false`.
=> Avoid styling form element when `aria-disabled` is `false`

stylus/utilities/flexbox.styl
These rules were interfering with other `min-height` and `min-width` rules without us being in the clear about what problem they solve.
=> fix: Remove unused rules on u-flex-auto class

docs/styleguide.config.js, package.json, react/AppLinker/Readme.md, react/AppLinker/__snapshots__/index.spec.jsx.snap, react/AppLinker/expiringMemoize.js, react/AppLinker/index.jsx, react/AppLinker/index.spec.jsx, react/AppLinker/native.js, yarn.lock
We need to open apps throughout the cozy platform. The rules to open an app vary depending on whether we are on mobile, whether the native app is installed etc...
It is a refactor from AppItem in the bar. It is more low level than AppItem as it only deals with the logic of what to do onClick. The presentational logic is left to the implementer. This way we can use it for AppItem or for simple links.
=> feat: Add AppLinker

react/Popover/Popover.jsx
Prevents an error when used with react.
@Crash-- This component is used in Drive, but is otherwise marked as not ready; what is missing from it to be ready for broader use ?
=> fix: Default popover state

react/Field/Readme.md, react/SelectionBar/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Now that `label` prop is required in `Button` component, we have warning in our apps because `SelectionBar` renders a `Button` without `label`. We could add an empty string as `defaultProp` for `label` but I think that the idea is to force users to make it explicit.
=> fix: label prop is required in Button

react/SelectionBar/index.jsx
Since `Button` has to have a `label` for accessibility, we should add a label to the selection bar. 
We have to create a new translation string in our app that use SelectionBar
=> fix: SelectionBar button label

react/SelectionBar/index.jsx
This reverts commit 882efa8664a4fca213bf7a1ce025f1e8fa013346.
It was already done before and was breaking the CI.
=> Revert "fix: Selectionbar button label (#897)"

react/AppLinker/native.js, react/AppLinker/native.spec.js
Native `URL` is way better than me.
=> fix: AppLinker use native URL to construct url

react/Field/Readme.md, react/Field/index.jsx, react/SelectBox/SelectBox.jsx, react/__snapshots__/examples.spec.jsx.snap
Until now, we were not passing `name` prop to `Input`, `TextArea`, and `SelectBox` components.
Having it allows us a better management of inputs from ancestor component, like in Harvest were we need to know which fied has focus.
Inject name prop into Input, Textarea and SelectBox
components.
Related to https://github.com/cozy/cozy-libs/pull/396
=> Field: Inject name prop

react/Infos/index.jsx, react/__snapshots__/examples.spec.jsx.snap
If no button, before:
After
Nothing changes if there is a button
=> fix(infos): Better handling text bottom margin

react/AppLinker/index.jsx
I test new cozy-banks on custom mobile and I found this error: `Cannot read property 'slug' of undefined`.
=> fix(AppLinker): Slug is in props

react/Field/index.jsx, react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/__snapshots__/examples.spec.jsx.snap
Provide an `inputRef` prop which will retrive the input ref from `ReactSelect` component.
The `SelectBox now provides the same API as `Input` components.
In harvest, it will allow us to manage focus and focus event from input fields.
Related to https://github.com/cozy/cozy-libs/pull/396
=> SelectBox: Retrieve input ref from ReactSelect

react/Field/index.jsx
Fullwidth prop has been accidentally removed in 05bce5d31d0530ee845c3beddae3003024db5923
Before this PR
After this PR
=> Fix fullwidth prop for InputPassword

react/Menu/index.jsx
Closes https://github.com/cozy/cozy-ui/issues/898
=> fix(Menu): Don't pass non-DOM props to div

stylus/utilities/text.styl
Change valid color to `emerald`. It was a mistake from a long time ago.
- `emerald` is the base color for valid elements
- `malachite` is the hover color for valid elements (if there's any hover state)
=> fix: Update valid color to emerald

docs/IconSpriteInjector.jsx, docs/styleguide.config.js
We currently have a small bug in our styleguidist, noticed [here](https://github.com/cozy/cozy-ui/pull/962#issuecomment-490662542), where icons for the example page of an individual component don't show up, for example the [Badge component here](https://docs.cozy.io/cozy-ui/react/#!/Badge).
The icons only show up in the list because the `IconSprite` component is renderer (but not documented). This PR properly adds the `IconSprite` on the page, including standalone examples.
=> chore: Add icon sprite on all styleguidist examples

react/Chip/index.jsx
Chip component will break automatically is its content doesn't contain any space.
=> fix: Add breakword utility class to Chip component

react/Infos/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Before:
After:
Preview: https://gooz.github.io/cozy-ui/react/#infos
=> fix: Remove margin-top on text when no title

react/AppLinker/index.jsx, react/AppLinker/index.spec.jsx
We need to override the behavior in some context. Having static methods makes it easier
=> feat: Use static method for AppLinker

react/Viewer/ViewerExposer.js
The current export exports the whole Viewer module, so we can't do `import { Viewer } from 'cozy-ui/react/transpiled'`.
=> fix: Export the default viewer module

react/SelectBox/Readme.md, react/SelectBox/SelectBox.jsx, react/__snapshots__/examples.spec.jsx.snap
Pretty urgent, needed to update the cozy-store in our customizations.
Following 57d6c62342c515f1b883cd57337597fa7e120eba, we now need to set a default background for SelectBox when it is not disabled. (We specified a transparent background to React-Select to be able to style the disabled state.)
=> feat(SelectBox): Add default white background 📝

stylus/components/forms.styl
I missed something. The delete line button should be placed according to the line it is supposed to delete.
That'll do it.
=> fix: Double-field line button position

package.json, yarn.lock
This is a way to standardize how our libs consume our other libs.
I've put "*" for cozy-client since we don't have any blocker in terms of API yet (we just use withClient()).
=> fix: CozyClient is now a peerDep

react/Field/Readme.md, react/Field/styles.styl, react/__snapshots__/examples.spec.jsx.snap
* Fix show/hide position on password Field
* Fix side position on Field
* Update the styleguidist example:
Those are some quick fixes, we have an issue since the two (show/hide and side) has the same visual result but use different DOM outline and CSS rules, I opened an issue to clean this #988
=> Fix show/hide and side on Field component

react/PushClientBanner/index.jsx
`<p>` HTML tag cannot contain block elements like `<figure>`, it triggers a DOM warning in some browsers console, hence the `<div>` replacement.
=> fix: PushClientBanner component's DOM

stylus/utilities/position.styl
Made the position utility classes responsive, it kinda make sense since `position` is clearly a property that could change on different viewport sizes… and… I actually need it :x
=> feat: Responsive position utils

react/AppIcon/index.jsx
I had a few warnings about : 
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in AppIcon (created by AppLinker)
```
=> fix: Don't use setState if unmouting

stylus/components/forms.styl
The compiler sends us a warning : 
```
start value has mixed support, consider using flex-start instead
```
=> fix: Use flex-start instead of start

stylus/components/forms.styl
Checkbox and label have now a much better alignment.
=> fix: Checkbox alignment

stylus/settings/breakpoints.styl
- 480px (tiny)
- 768px (small)
- 1023px (medium)
There now should be 4 versions of a utility class: `foo`, `foo-t`, `foo-s`, `foo-m` instead of the previous 7.
=> feat: Add Standard breakpoints for utility classes

react/AppIcon/index.jsx
- app is not required in AppIcon, it can omitted if fetchIcon is provided
=> Fix app propType

babel.config.js, react/AppSections/Sections.jsx
It is convenient to be able to give Sections an initialSearch and then let it
manage it internally. This way we have a middle ground before controlled and
uncontrolled.
=> feat(Sections): Add initial search prop

react/Chip/Readme.md, react/Chip/index.jsx, react/Chip/styles.styl, stylus/components/chip.styl
This PR introduces 3 new props for the `Chip` component:
* `size`: add the `small` size. Existing size is `normal`
* `variant`: add `outlined` and `dashed` variants. Existing styles are `normal` variant
* `theme`: add `primary` and `error` variant. Existing colors are `normal` variant
You can see all this on https://drazik.github.io/cozy-ui/react/#chip
=> Add sizes, variants and themes to Chip

react/AppIcon/styles.styl
=> Add object-fit contain on app icons

react/Chip/index.jsx, react/Chip/styles.styl, stylus/components/chip.styl
Some updates to normal and error themes for outlined variant on the Chip component. We want special colors for these cases, so I added specific classes for them.
See https://drazik.github.io/cozy-ui/react
=> feat(Chip): Update outlined themes

react/I18n/withLocales.jsx, react/I18n/withLocales.spec.jsx
It is useful to be able to pass a function that requires the locale so
that require contexts in webpack and "normal" dynamic require from node
can be used instead of listing all locales that have to be required.
Now withLocales can be used with an object or a function.
```jsx
// static require, need to list manually all langs
const locales = { en: require('en.json') }
withLocales(locales)
// dynamic require (automatic webpack context or via node)
withLocales(lang => require(lang + '.json'))
```
=> feat: Ability to use a function for withLocales arg

react/Chip/index.jsx, react/Chip/styles.styl, stylus/components/chip.styl
Add hover and focus states for Chips. Only outlined and dashed variant have these states.
See https://drazik.github.io/cozy-ui/react
=> feat(Chip): Add hover and focus states

react/AppLinker/native.js, react/AppLinker/native.spec.js
It is easier for apps to provide only the cozyURL and not the fallback URL.
Now the fallback URL is generated automatically if `options.cozyUrl` is passed.
=> feat: Fallback URL is generated automatically

react/Chip/Readme.md, stylus/components/chip.styl
We had an alignment issue on the `Chip` component when the content of the Chip was taller than the real content area:
The solution I used here is to remove the vertical paddings. Since we already have a fixed `height` and use `display: flex` and `align-items: center` to vertically center the content, this padding was not really useful.
You can see it on https://drazik.github.io/cozy-ui/react/#chip. I added an example using 2 `Icon`s and a `Chip.Separator` so we can easily test alignment. I tested it on a lot of configurations in Browserstack and didn't see any issue.
=> fix(Chip): Better alignment

react/AppLinker/native.js
Native path is an optional argument.
Loudly throws if neither cozyUrl or fallbackUrl is not there.
=> feat: Native path is optional in UL helper

react/Radio/Readme.md, react/Radio/index.jsx, react/__snapshots__/examples.spec.jsx.snap, stylus/components/forms.styl
If the height of the label is customised, for example to have a larger
clic area, the text was not aligned with the checkbox circle.
View it on http://ptbrowne.github.io/cozy-ui/react/#!/Radio
=> feat: Keep radio elements centered

react/SelectBox/SelectBox.jsx, react/__snapshots__/examples.spec.jsx.snap
Using an utility class makes it impossible to override bg color.
=> fix: Use style to assign bg color to select box

react/Text/index.jsx
dangerouslySetInnerHTML can be used instead, for example when displaying markdown.
In Banks we had a warning because we were using `<Text/>` without children, I changed the Text to a `<p>` but drazik made the point that the isRequired could also be removed from the `children` . https://github.com/cozy/cozy-banks/pull/1240#discussion_r290489849proptype.
=> fix: Do not require children for Text

docs/styleguide.config.js, react/ListItemText/styles.styl, react/MuiCozyTheme/List/Readme.md, react/MuiCozyTheme/List/index.js, react/MuiCozyTheme/ListItem/index.js, react/MuiCozyTheme/ListItemIcon/index.js, react/MuiCozyTheme/ListItemSecondaryAction/index.js, react/MuiCozyTheme/ListSubheader/index.js, react/MuiCozyTheme/theme.js, react/__snapshots__/examples.spec.jsx.snap, react/examples.spec.jsx
Added the `List` component based on Mui's `List`.
With it I updated the style of `ListItem`, `ListItemIcon`, `ListItemSecondaryAction` and `ListSubheader`
Thought I didn't change [ListItemAvatar](https://v3-9-0.material-ui.com/api/list-item-avatar/) because I didn't need it and it's kinda buggy.
[Preview](https://gooz.github.io/cozy-ui/react/#!/List)
=> feat: Add List component based on MUI

react/Checkbox/styles.styl
When a checkbox have a label long enough to be on multiple lines, the `check` icon is misplaced (it's actually top aligned and white on white so you can't see it)
Before:
After:
=> fix(Checkbox): Check icon position when multiline label

react/Field/index.jsx, react/Field/index.spec.js
The Field value props should be a string for all types except for the `select` where the value should be an object.
Add also a test for that.
=> fix(Field): Correctly handling select value proptype

react/I18n/index.jsx, react/I18n/withLocales.jsx, react/I18n/withLocales.spec.jsx
Get exposed prop-types is useful when you want to check or get an exhaustive list of provided props and the related types for developing or for testing
=> fix(I18n): Improve hocs proptypes handling + expose proptypes

react/Input/Readme.md, react/Input/__snapshots__/index.spec.jsx.snap, react/Input/index.jsx, react/Input/index.spec.jsx
`Input` component now supports `number` type: https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/number
No fancy stuff here. See https://cedricmessiant.github.io/cozy-ui/react/#input for an example
=> Support input[type=number]

react/Text/Readme.md, react/Text/index.jsx, react/Text/styles.styl, react/__snapshots__/examples.spec.jsx.snap, react/index.js, stylus/generic/typography.styl
Also add u-uppercase utility class.
As seen with @GoOz, we concluded that it was a good thing to do to make a new component as we made for `<Bold />`
=> Text: Add Uppercase component ✨

stylus/components/empty.styl
Add max-width to Empty so that it cannot grow larger than its container.
Fix #1064
=> fix: Limit expansion of Empty

.npmignore
When an app developer needs to execute a codemod on his codebase, (s)he
doesn't want to clone the cozy-ui repository to get them. Publishing the
codemods on npm allows him to reach it from
`node_modules/cozy-ui/codemods` in his project directory.
This way we could give a command like the following in the release notes:
```
npx jscodeshift --parser babel -t ./node_modules/cozy-ui/codemods/new-icons.js --extensions js,jsx src/
```
And the developer would just have to copy/paste it instead of cloning cozy-ui or copy/pasting the codemod code from github.
=> chore: Don't ignore codemods directory when publishing on npm

react/Modal/index.jsx
Move the `style` prop (which contains `width` & `height` props) from the Modal wrapper to the Modal itself.
Originally, those props were added to force a modal height for Intent and it worked for them but it couldn't be used for regular modals.
Now it can & still works for Intent modals.
Fixes #899
=> fix: Move dimension props from wrapper to modal

stylus/components/modals.styl
In banks, we needed to add vertical padding on a `Modal` with `mobileFullscreen` prop set to `true`. But it made the modal overflows because the paddings were added to the `100%` height. The easiest solution is to add a `box-sizing: border-box` to the fullscreen modals, so the height and width include the padding.
=> fix(Modal): Use border-box box-sizing on fullscreen variant

package.json
This way, the icon sprite is always up to date in the styleguidist.
=> chore: Create icon sprite before running styleguidist

react/Accordion/index.jsx, react/ActionMenu/Readme.md, react/AppSections/components/DropdownFilter.jsx, react/Button/Readme.md, react/Chip/Readme.md, react/Icon/Readme.md, react/SelectBox/SelectBox.jsx, react/Viewer/ViewerControls.jsx, react/__snapshots__/examples.spec.jsx.snap
Fix all icons used in components & styleguidist examples.
[Preview](https://gooz.github.io/cozy-ui/react/)
Fixes: #1073
=> fix: Icons used in React components & examples

stylus/components/nav.styl
Icons in nav were not correctly aligned.
**Avant:**
**Après:**
=> fix(nav): Fix Icon alignment

stylus/components/nav.styl, stylus/cozy-ui/build.styl
#1083 introduced a regression on mobile navigation. Icons weren't correctly aligned anymore.
So here's the fix. 
Also the styleguide example wasn't using the right classnames, so It's fixed too.
=> fix(Nav): Icon alignement on mobile

stylus/cozy-ui/build.styl, stylus/tools/mixins.styl, stylus/utilities/text.styl
Adds utilty classes for line-height :
- `u-lh-tiny` - Sets a tiny line-height (1)
- `u-lh-xsmall` - Sets a xsmall line-height (1.1)
- `u-lh-small` - Sets a small line-height (1.2)
- `u-lh-medium` - Sets a medium line-height (1.3)
- `u-lh-large` - Sets a large line-height (1.4)
- `u-lh-xlarge` - Sets a large line-height (1.5)
Fixes: #1074
=> feat: Add line-height utility classes

react/Viewer/ImageLoader.jsx
I think client.options.uri works when we're not in an OAuth client, but let's use StackClient to be able to get the uri anytime ?
=> fix(Viewer): Use getStackClient().uri to get uri

react/Field/styles.styl, stylus/components/forms.styl
BREAKING CHANGE
[Styleguidist](https://gregorylegarec.github.io/cozy-ui/react/#!/Field)
Fixes https://github.com/cozy/cozy-libs/issues/629
In https://github.com/cozy/cozy-libs/pull/625 we hacked the whole form by setting a negative top-margin, as cards should define a bottom margin.
The objective of this PR is to avoid using a default top-margin on Field's labels element.
It implies to decrease the top position of side elements as well.
List of components potentially impacted by this change:
* https://github.com/cozy/cozy-banks/blob/4306a26d4b297ae56ecbfcef914256adfa156db4/src/ducks/transfers/steps/Amount.jsx 
* https://github.com/cozy/cozy-libs/blob/b5f3840001627846395dcffc410ae8fb0074d27a/packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
* …
=> Field: Remove Field label top-margin

react/Label/index.jsx
It seems that `for` is not mandatory in the HTML Spec. In some case, we use the label without any input.
=> fix(label): Remove required for htmlFor

react/AppLinker/index.jsx
If the global `__TARGET__` variable is non existant, the AppLinker simply crashes.
Sadly no unit test to cover the fix, because the bug is only in the transpiled version as far as I can tell.
=> fix: Don't crash when TARGET is missing

react/Avatar/Readme.md, react/Avatar/styles.styl, react/Circle/Readme.md, react/Circle/index.jsx, react/Circle/styles.styl, react/__snapshots__/examples.spec.jsx.snap, stylus/components/avatar.styl, stylus/components/circle.styl
Adds different sizes to `Circle` component.
`Circle`'s styles become the base the `Avatar` component relies on.
[Preview](https://gooz.github.io/cozy-ui/react/#circle)
Fixes: #784
=> feat: Add different sizes to Circle component

stylus/components/wizard.styl
We had two problems with the wizard styles in cozy-authentication:
* The badge on the logo was misaligned: 
|Before|After|
|------|-----|
|![image](https://user-images.githubusercontent.com/1606068/61056873-6f875a80-a3f4-11e9-8d85-ba1e30bb58fc.png)|![image](https://user-images.githubusercontent.com/1606068/61057126-f3d9dd80-a3f4-11e9-9c05-f40930ad1dfa.png)|
We want to logo on this page to look like the mobile app's logos where the badge is aligned on the right
* The fixed back arrow was misaligned:
|Before|After|
|------|-----|
|![image](https://user-images.githubusercontent.com/1606068/61056892-7a41ef80-a3f4-11e9-8402-62eae1cf6e59.png)|![image](https://user-images.githubusercontent.com/1606068/61057188-0c49f800-a3f5-11e9-85a9-cf1a2ea28c2c.png)|
This arrow was just weirdly placed.
=> Fixes in wizard styles

package.json, postcss.config.js, yarn.lock
In postcss config, we gave the browsers list to autoprefixer plugin
directly. But the `browsers` property is deprecated and will be removed
in next major version (see
https://github.com/postcss/autoprefixer/releases/tag/9.6.0).
We also use autoprefixer through autoprefixer-stylus, but it uses a very
old version of autoprefixer (7.1.0) that doesn't understand the `dead`
query that our browserslist config uses. A PR fixing this have been
merged and will hopefuly be released soon, see
https://github.com/jescalan/autoprefixer-stylus/pull/180. That's why I
left the custom browserslist config for autoprefixer-stylus in
`build:css`, `build:css:utils` and `build:css:kss` scripts for now. But
we should upgrade this module and stop using a custom browserslist
config for it as soon as possible.
This …
=> fix: Use browserslist-config-cozy instead of custom autoprefixer config

react/utilities.js
This should fix #1119. But some utility classes are likely to be
duplicated (since some of them were already present). More work is
needed to deduplicate them, but this fixes our base promise (transpiled
stylesheet contains everything the components use).
=> fix: Transpiled stylesheet contains utility classes

stylus/utilities/bgcolor.styl, stylus/utilities/text.styl
Most of our utility classes for colors are broken at the moment, as is visible on the [styleguide](https://docs.cozy.io/cozy-ui/styleguide/section-utilities.html) for example. This PR fixes the problem.
=> fix: Color utilities

stylus/components/forms.styl, stylus/tools/mixins.styl
In Radio and Checkbox components, inputs were hiddden using
`display: none` and `visibility: hidden`, which totally hide the
element. For accessibility reason, we actually want the inputs to be
only visually hidden, but still accessible to screen readers.
Fix #1122
For information, the technique used is from https://cloudfour.com/thinks/see-no-evil-hidden-content-and-accessibility/
I also added styles for the focused state.
See https://drazik.github.io/cozy-ui/react/#!/Checkbox and https://drazik.github.io/cozy-ui/react/#!/Radio
=> feat: Make radio and checkbox accessible

react/Field/Readme.md, react/Field/index.jsx, react/Label/index.jsx, react/__snapshots__/examples.spec.jsx.snap
The Field component renders a Label and an Input, but we don't have a lot of control over them. We already had a `fieldProps` prop that allowed to pass props down to the Input, and this PR does the same for the label.
Not super fond of piling on props like this, but the Field also has a built-in logic to toggle a password field between password and plain text that we would have to reimplement otherwise :(
=> feat: Customize Field label props

react/Text/Readme.md, react/__snapshots__/examples.spec.jsx.snap
Currently it's a bit confusing when we search about a `Caption` exemple in the doc.
=> docs(Text): Rename note to Caption

react/Field/Readme.md, react/Field/index.jsx, react/Field/styles.styl, react/__snapshots__/examples.spec.jsx.snap
We can now pass a secondaryComponent prop to InputPassword
in order to manage ourself the component.
Also edited a few css lines, to fix an issue where the
"hide"/"show" was capturing the click on the all width
https://crash--.github.io/cozy-ui/react/#!/Field/21
=> feat(Field): Custom secondaryComponent

react/Toggle/styles.styl
Problem: Toggles were grey even if checked.
We used emerald instead of var(--emerald), this bug was hidden previously since
the bar embarked its own UI and the CSS of UI inside the bar had a fallback
to var(--emerald) (IDK why).
=> fix: Use the correct variable

react/SelectBox/styles.styl, react/Spinner/styles.styl, react/Viewer/controls.styl
In #1134, we fixed an issue where we did not use the CSS variable and it caused a visible
bug in the toggle. I tried to automatically detect cases like that with csslint. Fortunately, there were not many cases.
---
```bash
$ yarn transpile
$ npx css-beautify transpile/react/stylesheet.css /tmp/beautified.css # must run csslint on a non-minified CSS
$ csslint /tmp/beautified.css --warnings="known-properties"| python /tmp/reformat.py | grep -v "var"
```
reformat.py (to have each error on oneline to be able to ignore lines with grep, see above)
```
import sys
data = sys.stdin.read()
errors = data.split('\n\n')
for e in errors:
lines = e.split('\n')
print "\t".join(lines)
```
=> fix: Use var() to access CSS variables

stylus/cozy-ui/build.styl, stylus/utilities/dimensions.styl
[`none` is not a valid value for `min-width` and co.](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width). I've replaced `none` with `auto`. The previous `u-miw-none` classes will work now, but are deprecated — please use `u-miw-auto` instead.
=> fix: Min/max none

react/Field/Readme.md, react/Field/index.jsx, react/__snapshots__/examples.spec.jsx.snap
ATM, `Field` is a controlled component since we set a value and onChange props. Because of that, we can't type something in a Field component without having to deal with setState etc. So it was not usable in our styleguidist. 
This PR should fix this issue. 
https://crash--.github.io/cozy-ui/react/#field
=> feat: Add uncontrolled Fields. Can use it in docs

.npmignore
If we ship `postcss.config.js`, parcel will try to transform CSS files
with the config shipped. This config is meant for transpilation, before
publishing, not for consumption by bundlers down the line.
The problem experienced was that in cozy-keys-lib, when trying to 
```
import 'cozy-ui/transpiled/react/stylesheet.css
```
we had an error "preset advanced cannot be found". This error stemmed from
the fact that the postcss.config.js is configured with `cssnano-preset-advanced`, and `cozy-ui`
does not declare `cssnano-preset-advanced` as a dependency, hence it was not in the node_modules of `cozy-keys-lib`.
By removing postcss.config.js from the npm package, we ensure that bundlers will not
try to load a config that is meant to be before publication, NOT for consumption by bundlers
down the …
=> fix: Do not ship postcss.config.js

react/Infos/index.jsx
In a few use cases, we pass to infos a ReactMardown component
So it's not a string but an object
=> fix(Infos): Fix the text propTypes

react/Stack/Readme.md, react/Stack/index.jsx, react/Stack/styles.styl, stylus/utilities/spaces.styl
Stack spacing values were so close that they were useless. I figured that since it is still very new, we could do a breaking change here.
@joel-costa  I am interested in your input here for vertical spacing.
The styleguide is visible here: https://ptbrowne.github.io/cozy-ui/react/#/Stack
BREAKING CHANGE: sparse/dense spacing values are no longer recognized
=> feat: Spacing values are a bit more spaced

stylus/cozy-ui/build.styl, stylus/utilities/position.styl
This is useful in combination with position utilities. For example if I have:
```html
<div class="u-pos-relative">
<div class="u-pos-absolute"></div>
</div>
```
And I want to position the children inside its parent, I can now use the new utilities:
```html
<div class="u-pos-relative">
<div class="u-pos-absolute u-right-0 u-bottom-xs"></div>
</div>
```
See https://drazik.github.io/cozy-ui/styleguide/section-utilities.html. I'm not quite happy with the visual examples in the styleguide. If you have ideas to show the result in a better way, please tell me.
For info, the CSS sizes:
cozy-ui.min.css: 122K => 123K
cozy-ui.utils.min.css: 73K => 73K
=> feat: Add position direction utilities

react/utils/color.js
fix #1153
If by any chance we change CSS variable values, the cache of the lodash memoized function
is accessible through memoizedFn.cache.
> Note: The cache is exposed as the cache property on the memoized function. Its creation may be customized by replacing the _.memoize.Cache constructor with one whose instances implement the Map method interface of clear, delete, get, has, and set.
https://lodash.com/docs/4.17.15#memoize
=> feat: Memoize getCSSVariableValue

react/IntentModal/test/__snapshots__/intentModal.spec.js.snap, react/Modal/index.jsx
After [2 years](https://github.com/cozy/cozy-ui/blame/master/react/Modal/index.jsx#L468) of warning, it's time to move on — modals will now be rendered in a portal all the time. The portal default value is `body`, but of course custom into values will still work.
I've made this a breaking change, because I guess if you rely on the modal's position in the DOM it might break something ?
=> feat: Always portal the modal

react/AppIcon/styles.styl, react/AppSections/components/SmallAppItem.styl, react/SelectBox/styles.styl, react/Toggle/styles.styl, react/Viewer/controls.styl, react/Viewer/styles.styl, stylus/components/alerts.styl, stylus/components/badge.styl, stylus/components/button.styl, stylus/components/circle.styl, stylus/components/forms.styl, stylus/components/modals.styl, stylus/components/selectionbar.styl, stylus/components/wizard.styl, stylus/cozy-ui/build.styl, stylus/elements/defaults.styl, stylus/objects/layouts.styl
We style used in a few place an harcorded version of our color. Since cozy-ui 22.3.1, we don't import our `palette.json` file. It results to have undefined color like `charcoalGrey`. To fix this issue, we need to use them as css var
=> fix(colors): Use css var instead of color

docs/styleguide.config.js, react/Page/Readme.md
The example had not been added to the styleguide.
Since the behavior is only shown on mobile, I only provided
a static example.
EDIT: Add viewable example URL https://ptbrowne.github.io/cozy-ui/react/#/PageLayout
=> fix: Add example for PageLayout in styleguide

scripts/screenshots.js
When using `fullPage` option on puppeteer's Page::screenshot method, the
viewport is automatically adapted to the entire page, no matter what
viewport we previously set.
=> chore: Don't specify viewport for screenshots

react/I18n/index.jsx
I didn't take the time to dig on this one, but in Drive, we had a failing test because of that error. I don't know how we can have an `undefined` as `WrappedComponent` but this is the case 
This is a TMP fix, but since this regression was introduced by this commit https://github.com/cozy/cozy-ui/commit/91aa079 I'll dig into it later
=> fix: Can not read propTypes of undefined

stylus/components/nav.styl
Since https://github.com/cozy/cozy-ui/pull/1083/files
there is a regression with the bottom nav bar on mobile.
SVG and text were not correctly displayed.
So this fix is basically a kind of revert for medium_screen()
=> fix(navitem): SVG is now well displayed on mobile

react/ActionMenu/Readme.md, react/ActionMenu/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Before this commit, if we attached an onClick to an
ActionMenuItem, the onClick was not called since
the propagation of the event was not stopped
resulting in the close of the menu instead of the
call of the onClick props.
With this fix, we stop the propagation if an onClick
is here, and we call it after.
https://crash--.github.io/cozy-ui/react/#actionmenu
=> fix(ActionMenuItem): Handle onClick on Item

stylus/cozy-ui/build.styl, stylus/utilities/dimensions.styl
For the needs of the password manager's read-only identifier field, we need  an icon with a `1.5rem` width (see https://zpl.io/VD1N3rr). This step was not existing on the dimensions scale, which surprised me since we have it in margin/padding scales. This PR adds it.
I didn't add others « half » steps that are present for margin and padding but not for dimensions (`half` and `2-half`). Do you think we should add it now?
See https://drazik.github.io/cozy-ui/styleguide/section-utilities.html#kssref-utilities-dimensions
=> feat(utilities): Add 1-half to dimensions scale

react/Modal/index.jsx
BREAKING CHANGE: ModalButtons now have default props
for primaryType & secondaryType same to Modale
ATM if we use `ModalButtons` manually, we have to set `primaryTheme` and `secondaryTheme`. It should be set by default to the same as `Modal`
=> fix: Set defaultProps to ModalButtons

docs/false.js, docs/isTesting.js, docs/styleguide.config.js, docs/utils.js, react/Menu/Readme.md, react/Menu/index.jsx, react/Menu/styles.styl, react/SelectBox/Readme.md, react/__snapshots__/examples.spec.jsx.snap, react/helpers/migrateProps.jsx, scripts/screenshots.js, stylus/components/menu.styl, stylus/components/popover.styl, test/testFromStyleguidist.js
- Fix the colors (fix #1170), charcoalGrey for text, slateGrey for icon
- Menu used in examples was the one from material-ui, styleguidist got confused when
auto-providing the `Menu` variable inside the examples. Requiring explicitly fixes
it (fix #1169).
- Have the menu automatically opened for Argos (provided the isArgos() util that can
be used in examples for this kind of behavior. Based on user-agent)
Preview here : https://ptbrowne.github.io/cozy-ui/react/#/Menu
=> feat: Menu improvements

react/InputGroup/Readme.md, react/InputGroup/index.jsx, react/__snapshots__/examples.spec.jsx.snap
Currently there is no way to pass a classname to our `InputGroup` component. 
I needed it to customize the border radius of this component 
https://crash--.github.io/cozy-ui/react/#inputgroup
=> fix(InputGroup): Now accept a classname

react/BarButton/Readme.md, react/__snapshots__/examples.spec.jsx.snap
We used an outdated icon in a BarButton example. This just fixes it.
https://drazik.github.io/cozy-ui/react/
=> chore(styleguide): Fix icon in BarButton examples

stylus/components/alerts.styl
Currently, our Alerter doesn't deal with safe-bottom-area on mobile. 
The result is pretty easy guessable. If the text is only on one line, we don't see it.
=> fix(Alerter): Add the safe-area-bottom

.npmignore, docs/README.md, package.json, scripts/screenshots.js
This is helpful for other applications that want to take
screenshots of their styleguide. Banks has a styleguide for
example.
=> feat: Expose react-styleguidist screenshot binary

stylus/components/button.styl
A small update to our ghost button style, including missing hover styles, curtesy of @joel-costa 
Before: 
After:
=> feat: Update ghost button style

docs/components/Variants.jsx, docs/styleguide.config.js, docs/webpack.config.js, react/CompositeRow/Readme.md, react/CompositeRow/index.jsx
Add to styleguide different variants of composite row layouts that Joel has on Sketch/Zeplin.
Visible on https://ptbrowne.github.io/cozy-ui/react/#/CompositeRow
~~I find the implementation a bit verbose, I will try to use utility classes instead of Bd/Img/Media to have less nesting.~~ With the help of utility classes, nesting is reduced, see https://github.com/cozy/cozy-ui/pull/1190/commits/4d76fc38209eb98d6b308431563e29de53d4949c
I also want to gather feedback on the following API: 
Proposition of names for the component (with my preference next to it):
- ComplexRow -
- RichRow +
- InfoRow -
- CompositeRow ++
- ListItem ++ (coherence with MaterialUI)
Proposition of props:
<p align='center'><img width="532" alt="image" src="https://user-images.githubusercontent.com/465582/66806029-c6865980 …
=> Composite row

react/Field/Readme.md, react/Field/index.jsx, react/__snapshots__/examples.spec.jsx.snap
'' is falsy thus value='' was not passed to the underlying input. As soon
as value changes, the input becomes controlled and this is not possible
with React, an input cannot become controlled if it started as uncontrolled.
This resulted in red errors in the console if changing the value of an
initially empty field. It also resulted in the field being uncontrolled
which meant that any value passed as a prop was not repercuted in the DOM,
the input did not reflect its props.
=> fix: Make controlled input without initial content possible

react/Tabs/Readme.md, react/__snapshots__/examples.spec.jsx.snap, stylus/components/tabs.styl
Using `overflow-x: scroll` causes a scroll gutter to be always rendered
on some platforms, even if scroll is not needed because nothing
overflows. Using `overflow-x: auto` prevents this, but we also need to
use `display: flex` on the parent instead of `display: inline-block` on
children, otherwise they wrap.
See https://drazik.github.io/cozy-ui/react/#!/Tab/0
=> fix(Tabs): Overflow scroll only when needed

react/Textarea/Readme.md, react/Textarea/index.jsx
```
<Textarea ref={domRef} />
```
=> feat: Allows `ref` forwarding in Textarea

react/Menu/index.jsx
> React does not recognize the `initialOpen` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialopen` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
Since we don't want to pass this props to the DOM, we add it to the destructured list..
=> fix(Menu): Warning initialOpen

react/CompositeRow/index.jsx
Since CompositeRows have a margin-bottom, we have to add style to them if we want to render multiple ones as a list. I think CompositeRow should not take care of its margins. The context in which we render them should take care of that (using a Stack, for example).
See https://drazik.github.io/cozy-ui/react/#!/CompositeRow
BREAKING CHANGE: CompositeRow no longer have bottom margin. You can add
the `u-mb-2` class name to you CompositeRows if you want to keep the
previous style
=> feat(CompositeRow): Don't set margins

react/helpers/withBreakpoints.jsx
withBreakpoints did not add a display name to the wrapped component, it
does now by keeping the display name of the wrapped component and wrapping
it with "withBreakpoints()" (can you wrap your head around this sentence ?).
=> feat: Add display name to withBreakpoints components

react/CompositeRow/index.jsx
Sometimes we need to pass basic props to CompositeRow. For example
onClick. It was not possible.
=> feat(CompositeRow): Spread props

docs/styleguide.config.js, react/MuiCozyTheme/TextField/Readme.md, react/MuiCozyTheme/TextField/index.js, react/MuiCozyTheme/theme.js, stylus/settings/palette.styl
Re-export component and add theme overrides.
I deployed on but it does not seem to have been received by GitHub pages. https://ptbrowne.github.io/cozy-ui/react/#/TextField
=> feat: Add TextField from MUI

stylus/components/forms.styl
This is important since it sets its width to 100% and has
a border. If box-sizing is not set, the border can be
drawn outside the parent which can be a problem if the
parent has overflow: hidden
=> fix: Border box for input group

react/PercentageBar/styles.styl
It seems after transpilation the PercentageBar CSS is before the PercentageLine one (maybe for an alphabetic order ?). Since `.PercentageBar__line` and `.PercentageLine` selectors have the same specificity, then the later "wins", and the line in `PercentageBar` dont take the full height.
=> fix(PercentageBar): Force line to take full height

docs/styleguide.config.js, react/Labs/IconGrid/Readme.md, react/Labs/IconGrid/index.jsx, react/Labs/IconGrid/styles.styl
This PR adds the IconGrid component, seen below:
It's in the Labs section because in an upcoming task, we will introduce a Grid component in cozy-ui, and my hope is that this Grid component is flexible enough to replace the IconGrid. In the meantime we have this component that displays a 2x2 grid of icons. Update documentation is [here](https://yannick-lohse.fr/cozy-ui/react/#!/IconGrid).
=> feat: Added IconGrid component

react/AppLinker/native.js, react/AppLinker/native.spec.js
So far when using AppLinker, we only supported the flat subdomains configuration. We can now support both, by using this PR and https://github.com/cozy/cozy-stack/pull/2172
=> Handle flat and nested subdomains

react/Tabs/Readme.md, react/__snapshots__/examples.spec.jsx.snap, stylus/components/tabs.styl
I'm still not sure *why*, but when specifying `flex 0 0`, the elements flex-basis is set to 0% instead of the default `auto`. This caused a problem when adding icons to tab names for example:
Specifying `flex 0 0 auto` solves the issue.
=> fix: Flex basis for tab names

react/Labs/IconGrid/styles.styl
Stylus compiles `grid-gap rem(1)` to… `grid-gap rem(1)`, which the browser obviously doesn't understand.
=> fix: Fix grid gap value

react/MuiCozyTheme/theme.js, stylus/settings/palette.styl
We have to use pomegranate right now instead of an indirection
since we cannot pass to mui a css variable.
=> fix: Cannot use var referencing another var

react/Labs/ExperimentalModal/index.jsx
Currently we display the Footer (there is no button, but we have a border / box-shadow)  even if we don't have any action. With this commit, we only display the footer if we have at least a primaryAction
=> feat(ExpModal): Don't display Footer if no footer

react/AppIcon/Readme.md, react/AppIcon/index.jsx, react/AppIcon/test/AppIcon.spec.js, react/AppSections/components/__snapshots__/SmallAppItem.spec.jsx.snap
This change comes from the [Home app](https://github.com/cozy/cozy-home/blob/master/src/components/AppIcon.jsx) where I made a wrapper that avoided needing `domain` and `secure` props all the time, since they can be detected by cozy-client.
It's a breaking change because if `AppIcon` is not inside the cozy-client context, it won't work anymore. That said other components in Ui already rely on this behavior so it's not a big stretch.
=> feat: AppIcon doesn't require secure and domain props anymore

react/BarButton/index.jsx, react/IntentModal/test/__snapshots__/intentModal.spec.js.snap, react/helpers/migrateProps.jsx
Two unrelated changes grouped under 1 PR for convenience 😇
- Allow BarButton to receive a custom class name.
- migrateProps puts the same displayName on the wrapped component as the component it wraps
=> Custom class name for BarButton + migrateProps displayName

react/Modal/ModalCross.jsx, stylus/components/modals.styl
We've had an issue for a while with the crosses in the modals of the styleguidist, more details can be found on [this thread](https://github.com/cozy/cozy-ui/issues/335#issuecomment-487582163) but basically it was a conflict of css classes.
With this fix, the cross doesn't use the `Button` component anymore, which means they don't try to override each others styles anymore.
My online preview repo is currently used by #1244 so I'll update this PR once the other one is merged.
=> fix: Use a regular button for the modal cross

babel.config.js, docs/build-utils.js, docs/webpack.config.js, package.json
When launching the styleguidist in watch mode, we add an environment
variable that babel and webpack use to disable extraction of CSS.
=> fix: HMR for CSS works in styleguidist

react/DateMonthPicker/styles.styl
There was still a little blue outline after clicking the buttons for prev/next
year in the DateMonthPicker.
=> fix: Remove outline for focused buttons in DateMonthPicker

package.json, react/Modal/index.jsx, react/Modal/index.spec.jsx
We had a bug since when several modals were mounted, if removing the
deepest one, it would remove the has-modal class on the body, when
the class should in fact remain since the first one is already there.
Another solution would be to bring react-side-effect to properly do this
=> fix: Presence of has-body when (un)mounting several modals

package.json
`react-swipeable-views` was added as a dev dep, which means it's not installed when installing cozy-ui elsewhere.
=> fix: Change react-swipeable dep type

react/PushClientButton/index.jsx
Since we have this icon in our Icon's palette, let's use it. 
Also removed the now unused icon
=> feat: Use laptop Icon from UI icon
